clang++ called with: --version
superenv added:    -pipe -Os -march=core2 -std=c++11 -stdlib=libc++ -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/opt/X11/include -isystem/opt/X11/include/freetype2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers -I/usr/local/opt/icu4c/include -I/usr/local/opt/gettext/include -L/usr/local/opt/icu4c/lib -L/usr/local/opt/gettext/lib -L/usr/local/opt/libffi/lib -L/usr/local/lib -L/opt/X11/lib -L/System/Library/Frameworks/OpenGL.framework/Versions/Current/Libraries -Wl,-headerpad_max_install_names
superenv executed: clang++ -pipe -Os -march=core2 -std=c++11 -stdlib=libc++ --version -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/opt/X11/include -isystem/opt/X11/include/freetype2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers -I/usr/local/opt/icu4c/include -I/usr/local/opt/gettext/include -L/usr/local/opt/icu4c/lib -L/usr/local/opt/gettext/lib -L/usr/local/opt/libffi/lib -L/usr/local/lib -L/opt/X11/lib -L/System/Library/Frameworks/OpenGL.framework/Versions/Current/Libraries -Wl,-headerpad_max_install_names

clang++ called with: -v
superenv executed: clang++ -v

clang++ called with: -V
superenv added:    -pipe -Os -march=core2 -std=c++11 -stdlib=libc++ -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/opt/X11/include -isystem/opt/X11/include/freetype2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers -I/usr/local/opt/icu4c/include -I/usr/local/opt/gettext/include -L/usr/local/opt/icu4c/lib -L/usr/local/opt/gettext/lib -L/usr/local/opt/libffi/lib -L/usr/local/lib -L/opt/X11/lib -L/System/Library/Frameworks/OpenGL.framework/Versions/Current/Libraries -Wl,-headerpad_max_install_names
superenv executed: clang++ -pipe -Os -march=core2 -std=c++11 -stdlib=libc++ -V -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/opt/X11/include -isystem/opt/X11/include/freetype2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers -I/usr/local/opt/icu4c/include -I/usr/local/opt/gettext/include -L/usr/local/opt/icu4c/lib -L/usr/local/opt/gettext/lib -L/usr/local/opt/libffi/lib -L/usr/local/lib -L/opt/X11/lib -L/System/Library/Frameworks/OpenGL.framework/Versions/Current/Libraries -Wl,-headerpad_max_install_names

clang++ called with: -qversion
superenv added:    -pipe -Os -march=core2 -std=c++11 -stdlib=libc++ -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/opt/X11/include -isystem/opt/X11/include/freetype2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers -I/usr/local/opt/icu4c/include -I/usr/local/opt/gettext/include -L/usr/local/opt/icu4c/lib -L/usr/local/opt/gettext/lib -L/usr/local/opt/libffi/lib -L/usr/local/lib -L/opt/X11/lib -L/System/Library/Frameworks/OpenGL.framework/Versions/Current/Libraries -Wl,-headerpad_max_install_names
superenv executed: clang++ -pipe -Os -march=core2 -std=c++11 -stdlib=libc++ -qversion -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/opt/X11/include -isystem/opt/X11/include/freetype2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers -I/usr/local/opt/icu4c/include -I/usr/local/opt/gettext/include -L/usr/local/opt/icu4c/lib -L/usr/local/opt/gettext/lib -L/usr/local/opt/libffi/lib -L/usr/local/lib -L/opt/X11/lib -L/System/Library/Frameworks/OpenGL.framework/Versions/Current/Libraries -Wl,-headerpad_max_install_names

clang++ called with: -L/usr/local/opt/icu4c/lib conftest.cpp
superenv added:    -pipe -Os -march=core2 -std=c++11 -stdlib=libc++ -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/opt/X11/include -isystem/opt/X11/include/freetype2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers -I/usr/local/opt/icu4c/include -I/usr/local/opt/gettext/include -L/usr/local/opt/gettext/lib -L/usr/local/opt/libffi/lib -L/usr/local/lib -L/opt/X11/lib -L/System/Library/Frameworks/OpenGL.framework/Versions/Current/Libraries -Wl,-headerpad_max_install_names
superenv executed: clang++ -pipe -Os -march=core2 -std=c++11 -stdlib=libc++ -L/usr/local/opt/icu4c/lib conftest.cpp -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/opt/X11/include -isystem/opt/X11/include/freetype2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers -I/usr/local/opt/icu4c/include -I/usr/local/opt/gettext/include -L/usr/local/opt/icu4c/lib -L/usr/local/opt/gettext/lib -L/usr/local/opt/libffi/lib -L/usr/local/lib -L/opt/X11/lib -L/System/Library/Frameworks/OpenGL.framework/Versions/Current/Libraries -Wl,-headerpad_max_install_names

clang++ called with: -o conftest -L/usr/local/opt/icu4c/lib conftest.cpp
superenv added:    -pipe -Os -march=core2 -std=c++11 -stdlib=libc++ -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/opt/X11/include -isystem/opt/X11/include/freetype2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers -I/usr/local/opt/icu4c/include -I/usr/local/opt/gettext/include -L/usr/local/opt/gettext/lib -L/usr/local/opt/libffi/lib -L/usr/local/lib -L/opt/X11/lib -L/System/Library/Frameworks/OpenGL.framework/Versions/Current/Libraries -Wl,-headerpad_max_install_names
superenv executed: clang++ -pipe -Os -march=core2 -std=c++11 -stdlib=libc++ -o conftest -L/usr/local/opt/icu4c/lib conftest.cpp -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/opt/X11/include -isystem/opt/X11/include/freetype2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers -I/usr/local/opt/icu4c/include -I/usr/local/opt/gettext/include -L/usr/local/opt/icu4c/lib -L/usr/local/opt/gettext/lib -L/usr/local/opt/libffi/lib -L/usr/local/lib -L/opt/X11/lib -L/System/Library/Frameworks/OpenGL.framework/Versions/Current/Libraries -Wl,-headerpad_max_install_names

clang++ called with: -o conftest -L/usr/local/opt/icu4c/lib conftest.cpp
superenv added:    -pipe -Os -march=core2 -std=c++11 -stdlib=libc++ -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/opt/X11/include -isystem/opt/X11/include/freetype2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers -I/usr/local/opt/icu4c/include -I/usr/local/opt/gettext/include -L/usr/local/opt/gettext/lib -L/usr/local/opt/libffi/lib -L/usr/local/lib -L/opt/X11/lib -L/System/Library/Frameworks/OpenGL.framework/Versions/Current/Libraries -Wl,-headerpad_max_install_names
superenv executed: clang++ -pipe -Os -march=core2 -std=c++11 -stdlib=libc++ -o conftest -L/usr/local/opt/icu4c/lib conftest.cpp -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/opt/X11/include -isystem/opt/X11/include/freetype2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers -I/usr/local/opt/icu4c/include -I/usr/local/opt/gettext/include -L/usr/local/opt/icu4c/lib -L/usr/local/opt/gettext/lib -L/usr/local/opt/libffi/lib -L/usr/local/lib -L/opt/X11/lib -L/System/Library/Frameworks/OpenGL.framework/Versions/Current/Libraries -Wl,-headerpad_max_install_names

clang++ called with: -c conftest.cpp
superenv added:    -pipe -Os -march=core2 -std=c++11 -stdlib=libc++ -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/opt/X11/include -isystem/opt/X11/include/freetype2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers -I/usr/local/opt/icu4c/include -I/usr/local/opt/gettext/include
superenv executed: clang++ -pipe -Os -march=core2 -std=c++11 -stdlib=libc++ -c conftest.cpp -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/opt/X11/include -isystem/opt/X11/include/freetype2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers -I/usr/local/opt/icu4c/include -I/usr/local/opt/gettext/include

clang++ called with: -c conftest.cpp
superenv added:    -pipe -Os -march=core2 -std=c++11 -stdlib=libc++ -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/opt/X11/include -isystem/opt/X11/include/freetype2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers -I/usr/local/opt/icu4c/include -I/usr/local/opt/gettext/include
superenv executed: clang++ -pipe -Os -march=core2 -std=c++11 -stdlib=libc++ -c conftest.cpp -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/opt/X11/include -isystem/opt/X11/include/freetype2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers -I/usr/local/opt/icu4c/include -I/usr/local/opt/gettext/include

clang++ called with: -c -g conftest.cpp
superenv added:    -pipe -Os -march=core2 -std=c++11 -stdlib=libc++ -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/opt/X11/include -isystem/opt/X11/include/freetype2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers -I/usr/local/opt/icu4c/include -I/usr/local/opt/gettext/include
superenv executed: clang++ -pipe -Os -march=core2 -std=c++11 -stdlib=libc++ -c -g conftest.cpp -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/opt/X11/include -isystem/opt/X11/include/freetype2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers -I/usr/local/opt/icu4c/include -I/usr/local/opt/gettext/include

clang++ called with: -E conftest.cpp
superenv added:    -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/opt/X11/include -isystem/opt/X11/include/freetype2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers -I/usr/local/opt/icu4c/include -I/usr/local/opt/gettext/include
superenv executed: clang++ -E conftest.cpp -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/opt/X11/include -isystem/opt/X11/include/freetype2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers -I/usr/local/opt/icu4c/include -I/usr/local/opt/gettext/include

clang++ called with: -E conftest.cpp
superenv added:    -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/opt/X11/include -isystem/opt/X11/include/freetype2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers -I/usr/local/opt/icu4c/include -I/usr/local/opt/gettext/include
superenv executed: clang++ -E conftest.cpp -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/opt/X11/include -isystem/opt/X11/include/freetype2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers -I/usr/local/opt/icu4c/include -I/usr/local/opt/gettext/include

clang++ called with: -E conftest.cpp
superenv added:    -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/opt/X11/include -isystem/opt/X11/include/freetype2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers -I/usr/local/opt/icu4c/include -I/usr/local/opt/gettext/include
superenv executed: clang++ -E conftest.cpp -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/opt/X11/include -isystem/opt/X11/include/freetype2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers -I/usr/local/opt/icu4c/include -I/usr/local/opt/gettext/include

clang++ called with: -E conftest.cpp
superenv added:    -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/opt/X11/include -isystem/opt/X11/include/freetype2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers -I/usr/local/opt/icu4c/include -I/usr/local/opt/gettext/include
superenv executed: clang++ -E conftest.cpp -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/opt/X11/include -isystem/opt/X11/include/freetype2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers -I/usr/local/opt/icu4c/include -I/usr/local/opt/gettext/include

clang++ called with: -c -g -O2 conftest.cpp
superenv added:    -pipe -Os -march=core2 -std=c++11 -stdlib=libc++ -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/opt/X11/include -isystem/opt/X11/include/freetype2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers -I/usr/local/opt/icu4c/include -I/usr/local/opt/gettext/include
superenv executed: clang++ -pipe -Os -march=core2 -std=c++11 -stdlib=libc++ -c -g -O2 conftest.cpp -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/opt/X11/include -isystem/opt/X11/include/freetype2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers -I/usr/local/opt/icu4c/include -I/usr/local/opt/gettext/include

clang++ called with: -E conftest.cpp
superenv added:    -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/opt/X11/include -isystem/opt/X11/include/freetype2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers -I/usr/local/opt/icu4c/include -I/usr/local/opt/gettext/include
superenv executed: clang++ -E conftest.cpp -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/opt/X11/include -isystem/opt/X11/include/freetype2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers -I/usr/local/opt/icu4c/include -I/usr/local/opt/gettext/include

clang++ called with: -E conftest.cpp
superenv added:    -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/opt/X11/include -isystem/opt/X11/include/freetype2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers -I/usr/local/opt/icu4c/include -I/usr/local/opt/gettext/include
superenv executed: clang++ -E conftest.cpp -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/opt/X11/include -isystem/opt/X11/include/freetype2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers -I/usr/local/opt/icu4c/include -I/usr/local/opt/gettext/include

clang++ called with: -o conftest -g -O2 -L/usr/local/opt/icu4c/lib conftest.cpp
superenv added:    -pipe -Os -march=core2 -std=c++11 -stdlib=libc++ -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/opt/X11/include -isystem/opt/X11/include/freetype2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers -I/usr/local/opt/icu4c/include -I/usr/local/opt/gettext/include -L/usr/local/opt/gettext/lib -L/usr/local/opt/libffi/lib -L/usr/local/lib -L/opt/X11/lib -L/System/Library/Frameworks/OpenGL.framework/Versions/Current/Libraries -Wl,-headerpad_max_install_names
superenv executed: clang++ -pipe -Os -march=core2 -std=c++11 -stdlib=libc++ -o conftest -g -O2 -L/usr/local/opt/icu4c/lib conftest.cpp -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/opt/X11/include -isystem/opt/X11/include/freetype2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers -I/usr/local/opt/icu4c/include -I/usr/local/opt/gettext/include -L/usr/local/opt/icu4c/lib -L/usr/local/opt/gettext/lib -L/usr/local/opt/libffi/lib -L/usr/local/lib -L/opt/X11/lib -L/System/Library/Frameworks/OpenGL.framework/Versions/Current/Libraries -Wl,-headerpad_max_install_names

clang++ called with: -c -g -O2 conftest.cpp
superenv added:    -pipe -Os -march=core2 -std=c++11 -stdlib=libc++ -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/opt/X11/include -isystem/opt/X11/include/freetype2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers -I/usr/local/opt/icu4c/include -I/usr/local/opt/gettext/include
superenv executed: clang++ -pipe -Os -march=core2 -std=c++11 -stdlib=libc++ -c -g -O2 conftest.cpp -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/opt/X11/include -isystem/opt/X11/include/freetype2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers -I/usr/local/opt/icu4c/include -I/usr/local/opt/gettext/include

clang++ called with: -c -g -O2 conftest.cpp
superenv added:    -pipe -Os -march=core2 -std=c++11 -stdlib=libc++ -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/opt/X11/include -isystem/opt/X11/include/freetype2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers -I/usr/local/opt/icu4c/include -I/usr/local/opt/gettext/include
superenv executed: clang++ -pipe -Os -march=core2 -std=c++11 -stdlib=libc++ -c -g -O2 conftest.cpp -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/opt/X11/include -isystem/opt/X11/include/freetype2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers -I/usr/local/opt/icu4c/include -I/usr/local/opt/gettext/include

clang++ called with: -c -g -O2 conftest.cpp
superenv added:    -pipe -Os -march=core2 -std=c++11 -stdlib=libc++ -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/opt/X11/include -isystem/opt/X11/include/freetype2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers -I/usr/local/opt/icu4c/include -I/usr/local/opt/gettext/include
superenv executed: clang++ -pipe -Os -march=core2 -std=c++11 -stdlib=libc++ -c -g -O2 conftest.cpp -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/opt/X11/include -isystem/opt/X11/include/freetype2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers -I/usr/local/opt/icu4c/include -I/usr/local/opt/gettext/include

clang++ called with: -c -g -O2 conftest.cpp
superenv added:    -pipe -Os -march=core2 -std=c++11 -stdlib=libc++ -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/opt/X11/include -isystem/opt/X11/include/freetype2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers -I/usr/local/opt/icu4c/include -I/usr/local/opt/gettext/include
superenv executed: clang++ -pipe -Os -march=core2 -std=c++11 -stdlib=libc++ -c -g -O2 conftest.cpp -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/opt/X11/include -isystem/opt/X11/include/freetype2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers -I/usr/local/opt/icu4c/include -I/usr/local/opt/gettext/include

clang++ called with: -c -g -O2 conftest.cpp
superenv added:    -pipe -Os -march=core2 -std=c++11 -stdlib=libc++ -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/opt/X11/include -isystem/opt/X11/include/freetype2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers -I/usr/local/opt/icu4c/include -I/usr/local/opt/gettext/include
superenv executed: clang++ -pipe -Os -march=core2 -std=c++11 -stdlib=libc++ -c -g -O2 conftest.cpp -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/opt/X11/include -isystem/opt/X11/include/freetype2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers -I/usr/local/opt/icu4c/include -I/usr/local/opt/gettext/include

clang++ called with: -c -g -O2 conftest.cpp
superenv added:    -pipe -Os -march=core2 -std=c++11 -stdlib=libc++ -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/opt/X11/include -isystem/opt/X11/include/freetype2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers -I/usr/local/opt/icu4c/include -I/usr/local/opt/gettext/include
superenv executed: clang++ -pipe -Os -march=core2 -std=c++11 -stdlib=libc++ -c -g -O2 conftest.cpp -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/opt/X11/include -isystem/opt/X11/include/freetype2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers -I/usr/local/opt/icu4c/include -I/usr/local/opt/gettext/include

clang++ called with: -c -g -O2 conftest.cpp
superenv added:    -pipe -Os -march=core2 -std=c++11 -stdlib=libc++ -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/opt/X11/include -isystem/opt/X11/include/freetype2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers -I/usr/local/opt/icu4c/include -I/usr/local/opt/gettext/include
superenv executed: clang++ -pipe -Os -march=core2 -std=c++11 -stdlib=libc++ -c -g -O2 conftest.cpp -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/opt/X11/include -isystem/opt/X11/include/freetype2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers -I/usr/local/opt/icu4c/include -I/usr/local/opt/gettext/include

clang++ called with: -c -g -O2 conftest.cpp
superenv added:    -pipe -Os -march=core2 -std=c++11 -stdlib=libc++ -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/opt/X11/include -isystem/opt/X11/include/freetype2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers -I/usr/local/opt/icu4c/include -I/usr/local/opt/gettext/include
superenv executed: clang++ -pipe -Os -march=core2 -std=c++11 -stdlib=libc++ -c -g -O2 conftest.cpp -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/opt/X11/include -isystem/opt/X11/include/freetype2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers -I/usr/local/opt/icu4c/include -I/usr/local/opt/gettext/include

clang++ called with: -c -g -O2 conftest.cpp
superenv added:    -pipe -Os -march=core2 -std=c++11 -stdlib=libc++ -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/opt/X11/include -isystem/opt/X11/include/freetype2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers -I/usr/local/opt/icu4c/include -I/usr/local/opt/gettext/include
superenv executed: clang++ -pipe -Os -march=core2 -std=c++11 -stdlib=libc++ -c -g -O2 conftest.cpp -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/opt/X11/include -isystem/opt/X11/include/freetype2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers -I/usr/local/opt/icu4c/include -I/usr/local/opt/gettext/include

clang++ called with: -c -g -O2 conftest.cpp
superenv added:    -pipe -Os -march=core2 -std=c++11 -stdlib=libc++ -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/opt/X11/include -isystem/opt/X11/include/freetype2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers -I/usr/local/opt/icu4c/include -I/usr/local/opt/gettext/include
superenv executed: clang++ -pipe -Os -march=core2 -std=c++11 -stdlib=libc++ -c -g -O2 conftest.cpp -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/opt/X11/include -isystem/opt/X11/include/freetype2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers -I/usr/local/opt/icu4c/include -I/usr/local/opt/gettext/include

clang++ called with: -E conftest.cpp
superenv added:    -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/opt/X11/include -isystem/opt/X11/include/freetype2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers -I/usr/local/opt/icu4c/include -I/usr/local/opt/gettext/include
superenv executed: clang++ -E conftest.cpp -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/opt/X11/include -isystem/opt/X11/include/freetype2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers -I/usr/local/opt/icu4c/include -I/usr/local/opt/gettext/include

clang++ called with: -c -g -O2 conftest.cpp
superenv added:    -pipe -Os -march=core2 -std=c++11 -stdlib=libc++ -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/opt/X11/include -isystem/opt/X11/include/freetype2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers -I/usr/local/opt/icu4c/include -I/usr/local/opt/gettext/include
superenv executed: clang++ -pipe -Os -march=core2 -std=c++11 -stdlib=libc++ -c -g -O2 conftest.cpp -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/opt/X11/include -isystem/opt/X11/include/freetype2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers -I/usr/local/opt/icu4c/include -I/usr/local/opt/gettext/include

clang++ called with: -E conftest.cpp
superenv added:    -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/opt/X11/include -isystem/opt/X11/include/freetype2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers -I/usr/local/opt/icu4c/include -I/usr/local/opt/gettext/include
superenv executed: clang++ -E conftest.cpp -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/opt/X11/include -isystem/opt/X11/include/freetype2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers -I/usr/local/opt/icu4c/include -I/usr/local/opt/gettext/include

clang++ called with: -c -g -O2 conftest.cpp
superenv added:    -pipe -Os -march=core2 -std=c++11 -stdlib=libc++ -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/opt/X11/include -isystem/opt/X11/include/freetype2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers -I/usr/local/opt/icu4c/include -I/usr/local/opt/gettext/include
superenv executed: clang++ -pipe -Os -march=core2 -std=c++11 -stdlib=libc++ -c -g -O2 conftest.cpp -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/opt/X11/include -isystem/opt/X11/include/freetype2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers -I/usr/local/opt/icu4c/include -I/usr/local/opt/gettext/include

clang++ called with: -E conftest.cpp
superenv added:    -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/opt/X11/include -isystem/opt/X11/include/freetype2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers -I/usr/local/opt/icu4c/include -I/usr/local/opt/gettext/include
superenv executed: clang++ -E conftest.cpp -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/opt/X11/include -isystem/opt/X11/include/freetype2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers -I/usr/local/opt/icu4c/include -I/usr/local/opt/gettext/include

clang++ called with: -o conftest -g -O2 -L/usr/local/opt/icu4c/lib conftest.cpp -framework OpenCL
superenv added:    -pipe -Os -march=core2 -std=c++11 -stdlib=libc++ -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/opt/X11/include -isystem/opt/X11/include/freetype2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers -I/usr/local/opt/icu4c/include -I/usr/local/opt/gettext/include -L/usr/local/opt/gettext/lib -L/usr/local/opt/libffi/lib -L/usr/local/lib -L/opt/X11/lib -L/System/Library/Frameworks/OpenGL.framework/Versions/Current/Libraries -Wl,-headerpad_max_install_names
superenv executed: clang++ -pipe -Os -march=core2 -std=c++11 -stdlib=libc++ -o conftest -g -O2 -L/usr/local/opt/icu4c/lib conftest.cpp -framework OpenCL -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/opt/X11/include -isystem/opt/X11/include/freetype2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers -I/usr/local/opt/icu4c/include -I/usr/local/opt/gettext/include -L/usr/local/opt/icu4c/lib -L/usr/local/opt/gettext/lib -L/usr/local/opt/libffi/lib -L/usr/local/lib -L/opt/X11/lib -L/System/Library/Frameworks/OpenGL.framework/Versions/Current/Libraries -Wl,-headerpad_max_install_names

clang called with: --version
superenv added:    -pipe -Os -march=core2 -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/opt/X11/include -isystem/opt/X11/include/freetype2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers -I/usr/local/opt/icu4c/include -I/usr/local/opt/gettext/include -L/usr/local/opt/icu4c/lib -L/usr/local/opt/gettext/lib -L/usr/local/opt/libffi/lib -L/usr/local/lib -L/opt/X11/lib -L/System/Library/Frameworks/OpenGL.framework/Versions/Current/Libraries -Wl,-headerpad_max_install_names
superenv executed: clang -pipe -Os -march=core2 --version -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/opt/X11/include -isystem/opt/X11/include/freetype2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers -I/usr/local/opt/icu4c/include -I/usr/local/opt/gettext/include -L/usr/local/opt/icu4c/lib -L/usr/local/opt/gettext/lib -L/usr/local/opt/libffi/lib -L/usr/local/lib -L/opt/X11/lib -L/System/Library/Frameworks/OpenGL.framework/Versions/Current/Libraries -Wl,-headerpad_max_install_names

clang called with: -v
superenv executed: clang -v

clang called with: -V
superenv added:    -pipe -Os -march=core2 -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/opt/X11/include -isystem/opt/X11/include/freetype2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers -I/usr/local/opt/icu4c/include -I/usr/local/opt/gettext/include -L/usr/local/opt/icu4c/lib -L/usr/local/opt/gettext/lib -L/usr/local/opt/libffi/lib -L/usr/local/lib -L/opt/X11/lib -L/System/Library/Frameworks/OpenGL.framework/Versions/Current/Libraries -Wl,-headerpad_max_install_names
superenv executed: clang -pipe -Os -march=core2 -V -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/opt/X11/include -isystem/opt/X11/include/freetype2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers -I/usr/local/opt/icu4c/include -I/usr/local/opt/gettext/include -L/usr/local/opt/icu4c/lib -L/usr/local/opt/gettext/lib -L/usr/local/opt/libffi/lib -L/usr/local/lib -L/opt/X11/lib -L/System/Library/Frameworks/OpenGL.framework/Versions/Current/Libraries -Wl,-headerpad_max_install_names

clang called with: -qversion
superenv added:    -pipe -Os -march=core2 -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/opt/X11/include -isystem/opt/X11/include/freetype2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers -I/usr/local/opt/icu4c/include -I/usr/local/opt/gettext/include -L/usr/local/opt/icu4c/lib -L/usr/local/opt/gettext/lib -L/usr/local/opt/libffi/lib -L/usr/local/lib -L/opt/X11/lib -L/System/Library/Frameworks/OpenGL.framework/Versions/Current/Libraries -Wl,-headerpad_max_install_names
superenv executed: clang -pipe -Os -march=core2 -qversion -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/opt/X11/include -isystem/opt/X11/include/freetype2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers -I/usr/local/opt/icu4c/include -I/usr/local/opt/gettext/include -L/usr/local/opt/icu4c/lib -L/usr/local/opt/gettext/lib -L/usr/local/opt/libffi/lib -L/usr/local/lib -L/opt/X11/lib -L/System/Library/Frameworks/OpenGL.framework/Versions/Current/Libraries -Wl,-headerpad_max_install_names

clang called with: -c -I/usr/local/opt/icu4c/include conftest.c
superenv added:    -pipe -Os -march=core2 -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/opt/X11/include -isystem/opt/X11/include/freetype2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers -I/usr/local/opt/gettext/include
superenv executed: clang -pipe -Os -march=core2 -c -I/usr/local/opt/icu4c/include conftest.c -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/opt/X11/include -isystem/opt/X11/include/freetype2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers -I/usr/local/opt/icu4c/include -I/usr/local/opt/gettext/include

clang called with: -c -g conftest.c
superenv added:    -pipe -Os -march=core2 -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/opt/X11/include -isystem/opt/X11/include/freetype2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers -I/usr/local/opt/icu4c/include -I/usr/local/opt/gettext/include
superenv executed: clang -pipe -Os -march=core2 -c -g conftest.c -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/opt/X11/include -isystem/opt/X11/include/freetype2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers -I/usr/local/opt/icu4c/include -I/usr/local/opt/gettext/include

clang called with: -c -I/usr/local/opt/icu4c/include conftest.c
superenv added:    -pipe -Os -march=core2 -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/opt/X11/include -isystem/opt/X11/include/freetype2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers -I/usr/local/opt/gettext/include
superenv executed: clang -pipe -Os -march=core2 -c -I/usr/local/opt/icu4c/include conftest.c -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/opt/X11/include -isystem/opt/X11/include/freetype2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers -I/usr/local/opt/icu4c/include -I/usr/local/opt/gettext/include

clang called with: -c conftest.c -o conftest2.o
superenv added:    -pipe -Os -march=core2 -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/opt/X11/include -isystem/opt/X11/include/freetype2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers -I/usr/local/opt/icu4c/include -I/usr/local/opt/gettext/include
superenv executed: clang -pipe -Os -march=core2 -c conftest.c -o conftest2.o -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/opt/X11/include -isystem/opt/X11/include/freetype2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers -I/usr/local/opt/icu4c/include -I/usr/local/opt/gettext/include

clang called with: -c conftest.c -o conftest2.o
superenv added:    -pipe -Os -march=core2 -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/opt/X11/include -isystem/opt/X11/include/freetype2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers -I/usr/local/opt/icu4c/include -I/usr/local/opt/gettext/include
superenv executed: clang -pipe -Os -march=core2 -c conftest.c -o conftest2.o -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/opt/X11/include -isystem/opt/X11/include/freetype2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers -I/usr/local/opt/icu4c/include -I/usr/local/opt/gettext/include

clang called with: -print-prog-name=ld
superenv added:    -pipe -Os -march=core2 -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/opt/X11/include -isystem/opt/X11/include/freetype2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers -I/usr/local/opt/icu4c/include -I/usr/local/opt/gettext/include -L/usr/local/opt/icu4c/lib -L/usr/local/opt/gettext/lib -L/usr/local/opt/libffi/lib -L/usr/local/lib -L/opt/X11/lib -L/System/Library/Frameworks/OpenGL.framework/Versions/Current/Libraries -Wl,-headerpad_max_install_names
superenv executed: clang -pipe -Os -march=core2 -print-prog-name=ld -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/opt/X11/include -isystem/opt/X11/include/freetype2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers -I/usr/local/opt/icu4c/include -I/usr/local/opt/gettext/include -L/usr/local/opt/icu4c/lib -L/usr/local/opt/gettext/lib -L/usr/local/opt/libffi/lib -L/usr/local/lib -L/opt/X11/lib -L/System/Library/Frameworks/OpenGL.framework/Versions/Current/Libraries -Wl,-headerpad_max_install_names

clang++ called with: -c -g -O2 conftest.cpp
superenv added:    -pipe -Os -march=core2 -std=c++11 -stdlib=libc++ -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/opt/X11/include -isystem/opt/X11/include/freetype2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers -I/usr/local/opt/icu4c/include -I/usr/local/opt/gettext/include
superenv executed: clang++ -pipe -Os -march=core2 -std=c++11 -stdlib=libc++ -c -g -O2 conftest.cpp -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/opt/X11/include -isystem/opt/X11/include/freetype2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers -I/usr/local/opt/icu4c/include -I/usr/local/opt/gettext/include

clang++ called with: -c -g -O2 conftest.cpp
superenv added:    -pipe -Os -march=core2 -std=c++11 -stdlib=libc++ -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/opt/X11/include -isystem/opt/X11/include/freetype2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers -I/usr/local/opt/icu4c/include -I/usr/local/opt/gettext/include
superenv executed: clang++ -pipe -Os -march=core2 -std=c++11 -stdlib=libc++ -c -g -O2 conftest.cpp -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/opt/X11/include -isystem/opt/X11/include/freetype2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers -I/usr/local/opt/icu4c/include -I/usr/local/opt/gettext/include

clang++ called with: -c -g -O2 conftest.cpp
superenv added:    -pipe -Os -march=core2 -std=c++11 -stdlib=libc++ -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/opt/X11/include -isystem/opt/X11/include/freetype2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers -I/usr/local/opt/icu4c/include -I/usr/local/opt/gettext/include
superenv executed: clang++ -pipe -Os -march=core2 -std=c++11 -stdlib=libc++ -c -g -O2 conftest.cpp -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/opt/X11/include -isystem/opt/X11/include/freetype2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers -I/usr/local/opt/icu4c/include -I/usr/local/opt/gettext/include

clang++ called with: -c -g -O2 conftest.cpp
superenv added:    -pipe -Os -march=core2 -std=c++11 -stdlib=libc++ -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/opt/X11/include -isystem/opt/X11/include/freetype2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers -I/usr/local/opt/icu4c/include -I/usr/local/opt/gettext/include
superenv executed: clang++ -pipe -Os -march=core2 -std=c++11 -stdlib=libc++ -c -g -O2 conftest.cpp -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/opt/X11/include -isystem/opt/X11/include/freetype2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers -I/usr/local/opt/icu4c/include -I/usr/local/opt/gettext/include

clang++ called with: -o conftest -g -O2 -L/usr/local/opt/icu4c/lib conftest.cpp conftstm.o
superenv added:    -pipe -Os -march=core2 -std=c++11 -stdlib=libc++ -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/opt/X11/include -isystem/opt/X11/include/freetype2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers -I/usr/local/opt/icu4c/include -I/usr/local/opt/gettext/include -L/usr/local/opt/gettext/lib -L/usr/local/opt/libffi/lib -L/usr/local/lib -L/opt/X11/lib -L/System/Library/Frameworks/OpenGL.framework/Versions/Current/Libraries -Wl,-headerpad_max_install_names
superenv executed: clang++ -pipe -Os -march=core2 -std=c++11 -stdlib=libc++ -o conftest -g -O2 -L/usr/local/opt/icu4c/lib conftest.cpp conftstm.o -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/opt/X11/include -isystem/opt/X11/include/freetype2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers -I/usr/local/opt/icu4c/include -I/usr/local/opt/gettext/include -L/usr/local/opt/icu4c/lib -L/usr/local/opt/gettext/lib -L/usr/local/opt/libffi/lib -L/usr/local/lib -L/opt/X11/lib -L/System/Library/Frameworks/OpenGL.framework/Versions/Current/Libraries -Wl,-headerpad_max_install_names

clang called with: -I/usr/local/opt/icu4c/include -L/usr/local/opt/icu4c/lib -o libconftest.dylib -dynamiclib -Wl,-single_module conftest.c
superenv added:    -pipe -Os -march=core2 -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/opt/X11/include -isystem/opt/X11/include/freetype2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers -I/usr/local/opt/gettext/include -L/usr/local/opt/gettext/lib -L/usr/local/opt/libffi/lib -L/usr/local/lib -L/opt/X11/lib -L/System/Library/Frameworks/OpenGL.framework/Versions/Current/Libraries -Wl,-headerpad_max_install_names
superenv executed: clang -pipe -Os -march=core2 -I/usr/local/opt/icu4c/include -L/usr/local/opt/icu4c/lib -o libconftest.dylib -dynamiclib -Wl,-single_module conftest.c -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/opt/X11/include -isystem/opt/X11/include/freetype2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers -I/usr/local/opt/icu4c/include -I/usr/local/opt/gettext/include -L/usr/local/opt/icu4c/lib -L/usr/local/opt/gettext/lib -L/usr/local/opt/libffi/lib -L/usr/local/lib -L/opt/X11/lib -L/System/Library/Frameworks/OpenGL.framework/Versions/Current/Libraries -Wl,-headerpad_max_install_names

clang++ called with: -o conftest -g -O2 -L/usr/local/opt/icu4c/lib -Wl,-exported_symbols_list,conftest.sym conftest.cpp
superenv added:    -pipe -Os -march=core2 -std=c++11 -stdlib=libc++ -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/opt/X11/include -isystem/opt/X11/include/freetype2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers -I/usr/local/opt/icu4c/include -I/usr/local/opt/gettext/include -L/usr/local/opt/gettext/lib -L/usr/local/opt/libffi/lib -L/usr/local/lib -L/opt/X11/lib -L/System/Library/Frameworks/OpenGL.framework/Versions/Current/Libraries -Wl,-headerpad_max_install_names
superenv executed: clang++ -pipe -Os -march=core2 -std=c++11 -stdlib=libc++ -o conftest -g -O2 -L/usr/local/opt/icu4c/lib -Wl,-exported_symbols_list,conftest.sym conftest.cpp -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/opt/X11/include -isystem/opt/X11/include/freetype2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers -I/usr/local/opt/icu4c/include -I/usr/local/opt/gettext/include -L/usr/local/opt/icu4c/lib -L/usr/local/opt/gettext/lib -L/usr/local/opt/libffi/lib -L/usr/local/lib -L/opt/X11/lib -L/System/Library/Frameworks/OpenGL.framework/Versions/Current/Libraries -Wl,-headerpad_max_install_names

clang called with: -I/usr/local/opt/icu4c/include -c -o conftest.o conftest.c
superenv added:    -pipe -Os -march=core2 -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/opt/X11/include -isystem/opt/X11/include/freetype2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers -I/usr/local/opt/gettext/include
superenv executed: clang -pipe -Os -march=core2 -I/usr/local/opt/icu4c/include -c -o conftest.o conftest.c -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/opt/X11/include -isystem/opt/X11/include/freetype2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers -I/usr/local/opt/icu4c/include -I/usr/local/opt/gettext/include

clang called with: -I/usr/local/opt/icu4c/include -L/usr/local/opt/icu4c/lib -o conftest conftest.c -Wl,-force_load,./libconftest.a
superenv added:    -pipe -Os -march=core2 -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/opt/X11/include -isystem/opt/X11/include/freetype2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers -I/usr/local/opt/gettext/include -L/usr/local/opt/gettext/lib -L/usr/local/opt/libffi/lib -L/usr/local/lib -L/opt/X11/lib -L/System/Library/Frameworks/OpenGL.framework/Versions/Current/Libraries -Wl,-headerpad_max_install_names
superenv executed: clang -pipe -Os -march=core2 -I/usr/local/opt/icu4c/include -L/usr/local/opt/icu4c/lib -o conftest conftest.c -Wl,-force_load,./libconftest.a -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/opt/X11/include -isystem/opt/X11/include/freetype2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers -I/usr/local/opt/icu4c/include -I/usr/local/opt/gettext/include -L/usr/local/opt/icu4c/lib -L/usr/local/opt/gettext/lib -L/usr/local/opt/libffi/lib -L/usr/local/lib -L/opt/X11/lib -L/System/Library/Frameworks/OpenGL.framework/Versions/Current/Libraries -Wl,-headerpad_max_install_names

clang++ called with: -c -g -O2 conftest.cpp
superenv added:    -pipe -Os -march=core2 -std=c++11 -stdlib=libc++ -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/opt/X11/include -isystem/opt/X11/include/freetype2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers -I/usr/local/opt/icu4c/include -I/usr/local/opt/gettext/include
superenv executed: clang++ -pipe -Os -march=core2 -std=c++11 -stdlib=libc++ -c -g -O2 conftest.cpp -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/opt/X11/include -isystem/opt/X11/include/freetype2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers -I/usr/local/opt/icu4c/include -I/usr/local/opt/gettext/include

clang called with: -c -I/usr/local/opt/icu4c/include conftest.c
superenv added:    -pipe -Os -march=core2 -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/opt/X11/include -isystem/opt/X11/include/freetype2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers -I/usr/local/opt/gettext/include
superenv executed: clang -pipe -Os -march=core2 -c -I/usr/local/opt/icu4c/include conftest.c -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/opt/X11/include -isystem/opt/X11/include/freetype2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers -I/usr/local/opt/icu4c/include -I/usr/local/opt/gettext/include

clang called with: -o conftest -I/usr/local/opt/icu4c/include -L/usr/local/opt/icu4c/lib conftest.c
superenv added:    -pipe -Os -march=core2 -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/opt/X11/include -isystem/opt/X11/include/freetype2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers -I/usr/local/opt/gettext/include -L/usr/local/opt/gettext/lib -L/usr/local/opt/libffi/lib -L/usr/local/lib -L/opt/X11/lib -L/System/Library/Frameworks/OpenGL.framework/Versions/Current/Libraries -Wl,-headerpad_max_install_names
superenv executed: clang -pipe -Os -march=core2 -o conftest -I/usr/local/opt/icu4c/include -L/usr/local/opt/icu4c/lib conftest.c -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/opt/X11/include -isystem/opt/X11/include/freetype2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers -I/usr/local/opt/icu4c/include -I/usr/local/opt/gettext/include -L/usr/local/opt/icu4c/lib -L/usr/local/opt/gettext/lib -L/usr/local/opt/libffi/lib -L/usr/local/lib -L/opt/X11/lib -L/System/Library/Frameworks/OpenGL.framework/Versions/Current/Libraries -Wl,-headerpad_max_install_names

clang called with: -c -I/usr/local/opt/icu4c/include -fno-rtti -fno-exceptions conftest.c
superenv added:    -pipe -Os -march=core2 -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/opt/X11/include -isystem/opt/X11/include/freetype2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers -I/usr/local/opt/gettext/include
superenv executed: clang -pipe -Os -march=core2 -c -I/usr/local/opt/icu4c/include -fno-rtti -fno-exceptions conftest.c -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/opt/X11/include -isystem/opt/X11/include/freetype2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers -I/usr/local/opt/icu4c/include -I/usr/local/opt/gettext/include

clang called with: -c -I/usr/local/opt/icu4c/include -fno-common -DPIC -DPIC conftest.c
superenv added:    -pipe -Os -march=core2 -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/opt/X11/include -isystem/opt/X11/include/freetype2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers -I/usr/local/opt/gettext/include
superenv executed: clang -pipe -Os -march=core2 -c -I/usr/local/opt/icu4c/include -fno-common -DPIC -DPIC conftest.c -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/opt/X11/include -isystem/opt/X11/include/freetype2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers -I/usr/local/opt/icu4c/include -I/usr/local/opt/gettext/include

clang called with: -o conftest -I/usr/local/opt/icu4c/include -L/usr/local/opt/icu4c/lib -static conftest.c
superenv added:    -pipe -Os -march=core2 -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/opt/X11/include -isystem/opt/X11/include/freetype2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers -I/usr/local/opt/gettext/include -L/usr/local/opt/gettext/lib -L/usr/local/opt/libffi/lib -L/usr/local/lib -L/opt/X11/lib -L/System/Library/Frameworks/OpenGL.framework/Versions/Current/Libraries -Wl,-headerpad_max_install_names
superenv executed: clang -pipe -Os -march=core2 -o conftest -I/usr/local/opt/icu4c/include -L/usr/local/opt/icu4c/lib -static conftest.c -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/opt/X11/include -isystem/opt/X11/include/freetype2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers -I/usr/local/opt/icu4c/include -I/usr/local/opt/gettext/include -L/usr/local/opt/icu4c/lib -L/usr/local/opt/gettext/lib -L/usr/local/opt/libffi/lib -L/usr/local/lib -L/opt/X11/lib -L/System/Library/Frameworks/OpenGL.framework/Versions/Current/Libraries -Wl,-headerpad_max_install_names

clang called with: -c -I/usr/local/opt/icu4c/include -o out/conftest2.o conftest.c
superenv added:    -pipe -Os -march=core2 -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/opt/X11/include -isystem/opt/X11/include/freetype2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers -I/usr/local/opt/gettext/include
superenv executed: clang -pipe -Os -march=core2 -c -I/usr/local/opt/icu4c/include -o out/conftest2.o conftest.c -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/opt/X11/include -isystem/opt/X11/include/freetype2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers -I/usr/local/opt/icu4c/include -I/usr/local/opt/gettext/include

clang called with: -print-search-dirs
superenv added:    -pipe -Os -march=core2 -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/opt/X11/include -isystem/opt/X11/include/freetype2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers -I/usr/local/opt/icu4c/include -I/usr/local/opt/gettext/include -L/usr/local/opt/icu4c/lib -L/usr/local/opt/gettext/lib -L/usr/local/opt/libffi/lib -L/usr/local/lib -L/opt/X11/lib -L/System/Library/Frameworks/OpenGL.framework/Versions/Current/Libraries -Wl,-headerpad_max_install_names
superenv executed: clang -pipe -Os -march=core2 -print-search-dirs -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/opt/X11/include -isystem/opt/X11/include/freetype2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers -I/usr/local/opt/icu4c/include -I/usr/local/opt/gettext/include -L/usr/local/opt/icu4c/lib -L/usr/local/opt/gettext/lib -L/usr/local/opt/libffi/lib -L/usr/local/lib -L/opt/X11/lib -L/System/Library/Frameworks/OpenGL.framework/Versions/Current/Libraries -Wl,-headerpad_max_install_names

clang called with: -I/usr/local/opt/icu4c/include -L/usr/local/opt/icu4c/lib -print-multi-os-directory
superenv added:    -pipe -Os -march=core2 -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/opt/X11/include -isystem/opt/X11/include/freetype2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers -I/usr/local/opt/gettext/include -L/usr/local/opt/gettext/lib -L/usr/local/opt/libffi/lib -L/usr/local/lib -L/opt/X11/lib -L/System/Library/Frameworks/OpenGL.framework/Versions/Current/Libraries -Wl,-headerpad_max_install_names
superenv executed: clang -pipe -Os -march=core2 -I/usr/local/opt/icu4c/include -L/usr/local/opt/icu4c/lib -print-multi-os-directory -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/opt/X11/include -isystem/opt/X11/include/freetype2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers -I/usr/local/opt/icu4c/include -I/usr/local/opt/gettext/include -L/usr/local/opt/icu4c/lib -L/usr/local/opt/gettext/lib -L/usr/local/opt/libffi/lib -L/usr/local/lib -L/opt/X11/lib -L/System/Library/Frameworks/OpenGL.framework/Versions/Current/Libraries -Wl,-headerpad_max_install_names

clang++ called with: -E conftest.cpp
superenv added:    -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/opt/X11/include -isystem/opt/X11/include/freetype2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers -I/usr/local/opt/icu4c/include -I/usr/local/opt/gettext/include
superenv executed: clang++ -E conftest.cpp -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/opt/X11/include -isystem/opt/X11/include/freetype2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers -I/usr/local/opt/icu4c/include -I/usr/local/opt/gettext/include

clang++ called with: -E conftest.cpp
superenv added:    -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/opt/X11/include -isystem/opt/X11/include/freetype2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers -I/usr/local/opt/icu4c/include -I/usr/local/opt/gettext/include
superenv executed: clang++ -E conftest.cpp -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/opt/X11/include -isystem/opt/X11/include/freetype2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers -I/usr/local/opt/icu4c/include -I/usr/local/opt/gettext/include

clang++ called with: -c -g -O2 conftest.cpp
superenv added:    -pipe -Os -march=core2 -std=c++11 -stdlib=libc++ -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/opt/X11/include -isystem/opt/X11/include/freetype2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers -I/usr/local/opt/icu4c/include -I/usr/local/opt/gettext/include
superenv executed: clang++ -pipe -Os -march=core2 -std=c++11 -stdlib=libc++ -c -g -O2 conftest.cpp -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/opt/X11/include -isystem/opt/X11/include/freetype2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers -I/usr/local/opt/icu4c/include -I/usr/local/opt/gettext/include

clang++ called with: -o conftest -g -O2 -L/usr/local/opt/icu4c/lib conftest.cpp
superenv added:    -pipe -Os -march=core2 -std=c++11 -stdlib=libc++ -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/opt/X11/include -isystem/opt/X11/include/freetype2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers -I/usr/local/opt/icu4c/include -I/usr/local/opt/gettext/include -L/usr/local/opt/gettext/lib -L/usr/local/opt/libffi/lib -L/usr/local/lib -L/opt/X11/lib -L/System/Library/Frameworks/OpenGL.framework/Versions/Current/Libraries -Wl,-headerpad_max_install_names
superenv executed: clang++ -pipe -Os -march=core2 -std=c++11 -stdlib=libc++ -o conftest -g -O2 -L/usr/local/opt/icu4c/lib conftest.cpp -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/opt/X11/include -isystem/opt/X11/include/freetype2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers -I/usr/local/opt/icu4c/include -I/usr/local/opt/gettext/include -L/usr/local/opt/icu4c/lib -L/usr/local/opt/gettext/lib -L/usr/local/opt/libffi/lib -L/usr/local/lib -L/opt/X11/lib -L/System/Library/Frameworks/OpenGL.framework/Versions/Current/Libraries -Wl,-headerpad_max_install_names

clang++ called with: -print-prog-name=ld
superenv added:    -pipe -Os -march=core2 -std=c++11 -stdlib=libc++ -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/opt/X11/include -isystem/opt/X11/include/freetype2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers -I/usr/local/opt/icu4c/include -I/usr/local/opt/gettext/include -L/usr/local/opt/icu4c/lib -L/usr/local/opt/gettext/lib -L/usr/local/opt/libffi/lib -L/usr/local/lib -L/opt/X11/lib -L/System/Library/Frameworks/OpenGL.framework/Versions/Current/Libraries -Wl,-headerpad_max_install_names
superenv executed: clang++ -pipe -Os -march=core2 -std=c++11 -stdlib=libc++ -print-prog-name=ld -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/opt/X11/include -isystem/opt/X11/include/freetype2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers -I/usr/local/opt/icu4c/include -I/usr/local/opt/gettext/include -L/usr/local/opt/icu4c/lib -L/usr/local/opt/gettext/lib -L/usr/local/opt/libffi/lib -L/usr/local/lib -L/opt/X11/lib -L/System/Library/Frameworks/OpenGL.framework/Versions/Current/Libraries -Wl,-headerpad_max_install_names

clang++ called with: -c -g -O2 conftest.cpp
superenv added:    -pipe -Os -march=core2 -std=c++11 -stdlib=libc++ -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/opt/X11/include -isystem/opt/X11/include/freetype2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers -I/usr/local/opt/icu4c/include -I/usr/local/opt/gettext/include
superenv executed: clang++ -pipe -Os -march=core2 -std=c++11 -stdlib=libc++ -c -g -O2 conftest.cpp -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/opt/X11/include -isystem/opt/X11/include/freetype2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers -I/usr/local/opt/icu4c/include -I/usr/local/opt/gettext/include

clang++ called with: -c -g -O2 -fno-common -DPIC -DPIC conftest.cpp
superenv added:    -pipe -Os -march=core2 -std=c++11 -stdlib=libc++ -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/opt/X11/include -isystem/opt/X11/include/freetype2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers -I/usr/local/opt/icu4c/include -I/usr/local/opt/gettext/include
superenv executed: clang++ -pipe -Os -march=core2 -std=c++11 -stdlib=libc++ -c -g -O2 -fno-common -DPIC -DPIC conftest.cpp -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/opt/X11/include -isystem/opt/X11/include/freetype2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers -I/usr/local/opt/icu4c/include -I/usr/local/opt/gettext/include

clang++ called with: -o conftest -g -O2 -L/usr/local/opt/icu4c/lib -static conftest.cpp
superenv added:    -pipe -Os -march=core2 -std=c++11 -stdlib=libc++ -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/opt/X11/include -isystem/opt/X11/include/freetype2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers -I/usr/local/opt/icu4c/include -I/usr/local/opt/gettext/include -L/usr/local/opt/gettext/lib -L/usr/local/opt/libffi/lib -L/usr/local/lib -L/opt/X11/lib -L/System/Library/Frameworks/OpenGL.framework/Versions/Current/Libraries -Wl,-headerpad_max_install_names
superenv executed: clang++ -pipe -Os -march=core2 -std=c++11 -stdlib=libc++ -o conftest -g -O2 -L/usr/local/opt/icu4c/lib -static conftest.cpp -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/opt/X11/include -isystem/opt/X11/include/freetype2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers -I/usr/local/opt/icu4c/include -I/usr/local/opt/gettext/include -L/usr/local/opt/icu4c/lib -L/usr/local/opt/gettext/lib -L/usr/local/opt/libffi/lib -L/usr/local/lib -L/opt/X11/lib -L/System/Library/Frameworks/OpenGL.framework/Versions/Current/Libraries -Wl,-headerpad_max_install_names

clang++ called with: -c -g -O2 -o out/conftest2.o conftest.cpp
superenv added:    -pipe -Os -march=core2 -std=c++11 -stdlib=libc++ -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/opt/X11/include -isystem/opt/X11/include/freetype2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers -I/usr/local/opt/icu4c/include -I/usr/local/opt/gettext/include
superenv executed: clang++ -pipe -Os -march=core2 -std=c++11 -stdlib=libc++ -c -g -O2 -o out/conftest2.o conftest.cpp -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/opt/X11/include -isystem/opt/X11/include/freetype2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers -I/usr/local/opt/icu4c/include -I/usr/local/opt/gettext/include

clang++ called with: -c -g -O2 conftest.cpp
superenv added:    -pipe -Os -march=core2 -std=c++11 -stdlib=libc++ -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/opt/X11/include -isystem/opt/X11/include/freetype2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers -I/usr/local/opt/icu4c/include -I/usr/local/opt/gettext/include
superenv executed: clang++ -pipe -Os -march=core2 -std=c++11 -stdlib=libc++ -c -g -O2 conftest.cpp -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/opt/X11/include -isystem/opt/X11/include/freetype2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers -I/usr/local/opt/icu4c/include -I/usr/local/opt/gettext/include

clang++ called with: -c -g -O2 conftest.cpp
superenv added:    -pipe -Os -march=core2 -std=c++11 -stdlib=libc++ -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/opt/X11/include -isystem/opt/X11/include/freetype2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers -I/usr/local/opt/icu4c/include -I/usr/local/opt/gettext/include
superenv executed: clang++ -pipe -Os -march=core2 -std=c++11 -stdlib=libc++ -c -g -O2 conftest.cpp -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/opt/X11/include -isystem/opt/X11/include/freetype2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers -I/usr/local/opt/icu4c/include -I/usr/local/opt/gettext/include

clang++ called with: -c -g -O2 conftest.cpp
superenv added:    -pipe -Os -march=core2 -std=c++11 -stdlib=libc++ -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/opt/X11/include -isystem/opt/X11/include/freetype2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers -I/usr/local/opt/icu4c/include -I/usr/local/opt/gettext/include
superenv executed: clang++ -pipe -Os -march=core2 -std=c++11 -stdlib=libc++ -c -g -O2 conftest.cpp -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/opt/X11/include -isystem/opt/X11/include/freetype2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers -I/usr/local/opt/icu4c/include -I/usr/local/opt/gettext/include

clang++ called with: -c -g -O2 conftest.cpp
superenv added:    -pipe -Os -march=core2 -std=c++11 -stdlib=libc++ -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/opt/X11/include -isystem/opt/X11/include/freetype2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers -I/usr/local/opt/icu4c/include -I/usr/local/opt/gettext/include
superenv executed: clang++ -pipe -Os -march=core2 -std=c++11 -stdlib=libc++ -c -g -O2 conftest.cpp -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/opt/X11/include -isystem/opt/X11/include/freetype2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers -I/usr/local/opt/icu4c/include -I/usr/local/opt/gettext/include

clang++ called with: -c -g -O2 -std=c++11 conftest.cpp
superenv added:    -pipe -Os -march=core2 -stdlib=libc++ -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/opt/X11/include -isystem/opt/X11/include/freetype2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers -I/usr/local/opt/icu4c/include -I/usr/local/opt/gettext/include
superenv executed: clang++ -pipe -Os -march=core2 -std=c++11 -stdlib=libc++ -c -g -O2 -std=c++11 conftest.cpp -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/opt/X11/include -isystem/opt/X11/include/freetype2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers -I/usr/local/opt/icu4c/include -I/usr/local/opt/gettext/include

clang++ called with: -o conftest -g -O2 -std=c++11 -L/usr/local/opt/icu4c/lib conftest.cpp
superenv added:    -pipe -Os -march=core2 -stdlib=libc++ -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/opt/X11/include -isystem/opt/X11/include/freetype2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers -I/usr/local/opt/icu4c/include -I/usr/local/opt/gettext/include -L/usr/local/opt/gettext/lib -L/usr/local/opt/libffi/lib -L/usr/local/lib -L/opt/X11/lib -L/System/Library/Frameworks/OpenGL.framework/Versions/Current/Libraries -Wl,-headerpad_max_install_names
superenv executed: clang++ -pipe -Os -march=core2 -std=c++11 -stdlib=libc++ -o conftest -g -O2 -std=c++11 -L/usr/local/opt/icu4c/lib conftest.cpp -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/opt/X11/include -isystem/opt/X11/include/freetype2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers -I/usr/local/opt/icu4c/include -I/usr/local/opt/gettext/include -L/usr/local/opt/icu4c/lib -L/usr/local/opt/gettext/lib -L/usr/local/opt/libffi/lib -L/usr/local/lib -L/opt/X11/lib -L/System/Library/Frameworks/OpenGL.framework/Versions/Current/Libraries -Wl,-headerpad_max_install_names

clang++ called with: -o conftest -g -O2 -L/usr/local/opt/icu4c/lib conftest.cpp
superenv added:    -pipe -Os -march=core2 -std=c++11 -stdlib=libc++ -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/opt/X11/include -isystem/opt/X11/include/freetype2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers -I/usr/local/opt/icu4c/include -I/usr/local/opt/gettext/include -L/usr/local/opt/gettext/lib -L/usr/local/opt/libffi/lib -L/usr/local/lib -L/opt/X11/lib -L/System/Library/Frameworks/OpenGL.framework/Versions/Current/Libraries -Wl,-headerpad_max_install_names
superenv executed: clang++ -pipe -Os -march=core2 -std=c++11 -stdlib=libc++ -o conftest -g -O2 -L/usr/local/opt/icu4c/lib conftest.cpp -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/opt/X11/include -isystem/opt/X11/include/freetype2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers -I/usr/local/opt/icu4c/include -I/usr/local/opt/gettext/include -L/usr/local/opt/icu4c/lib -L/usr/local/opt/gettext/lib -L/usr/local/opt/libffi/lib -L/usr/local/lib -L/opt/X11/lib -L/System/Library/Frameworks/OpenGL.framework/Versions/Current/Libraries -Wl,-headerpad_max_install_names

clang++ called with: -c -g -O2 conftest.cpp
superenv added:    -pipe -Os -march=core2 -std=c++11 -stdlib=libc++ -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/opt/X11/include -isystem/opt/X11/include/freetype2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers -I/usr/local/opt/icu4c/include -I/usr/local/opt/gettext/include
superenv executed: clang++ -pipe -Os -march=core2 -std=c++11 -stdlib=libc++ -c -g -O2 conftest.cpp -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/opt/X11/include -isystem/opt/X11/include/freetype2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers -I/usr/local/opt/icu4c/include -I/usr/local/opt/gettext/include

clang++ called with: -c -g -O2 conftest.cpp
superenv added:    -pipe -Os -march=core2 -std=c++11 -stdlib=libc++ -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/opt/X11/include -isystem/opt/X11/include/freetype2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers -I/usr/local/opt/icu4c/include -I/usr/local/opt/gettext/include
superenv executed: clang++ -pipe -Os -march=core2 -std=c++11 -stdlib=libc++ -c -g -O2 conftest.cpp -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/opt/X11/include -isystem/opt/X11/include/freetype2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers -I/usr/local/opt/icu4c/include -I/usr/local/opt/gettext/include

clang++ called with: -c -g -O2 conftest.cpp
superenv added:    -pipe -Os -march=core2 -std=c++11 -stdlib=libc++ -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/opt/X11/include -isystem/opt/X11/include/freetype2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers -I/usr/local/opt/icu4c/include -I/usr/local/opt/gettext/include
superenv executed: clang++ -pipe -Os -march=core2 -std=c++11 -stdlib=libc++ -c -g -O2 conftest.cpp -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/opt/X11/include -isystem/opt/X11/include/freetype2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers -I/usr/local/opt/icu4c/include -I/usr/local/opt/gettext/include

clang++ called with: -E conftest.cpp
superenv added:    -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/opt/X11/include -isystem/opt/X11/include/freetype2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers -I/usr/local/opt/icu4c/include -I/usr/local/opt/gettext/include
superenv executed: clang++ -E conftest.cpp -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/opt/X11/include -isystem/opt/X11/include/freetype2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers -I/usr/local/opt/icu4c/include -I/usr/local/opt/gettext/include

clang++ called with: -c -g -O2 conftest.cpp
superenv added:    -pipe -Os -march=core2 -std=c++11 -stdlib=libc++ -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/opt/X11/include -isystem/opt/X11/include/freetype2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers -I/usr/local/opt/icu4c/include -I/usr/local/opt/gettext/include
superenv executed: clang++ -pipe -Os -march=core2 -std=c++11 -stdlib=libc++ -c -g -O2 conftest.cpp -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/opt/X11/include -isystem/opt/X11/include/freetype2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers -I/usr/local/opt/icu4c/include -I/usr/local/opt/gettext/include

clang++ called with: -E conftest.cpp
superenv added:    -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/opt/X11/include -isystem/opt/X11/include/freetype2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers -I/usr/local/opt/icu4c/include -I/usr/local/opt/gettext/include
superenv executed: clang++ -E conftest.cpp -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/opt/X11/include -isystem/opt/X11/include/freetype2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers -I/usr/local/opt/icu4c/include -I/usr/local/opt/gettext/include

clang++ called with: -c -g -O2 conftest.cpp
superenv added:    -pipe -Os -march=core2 -std=c++11 -stdlib=libc++ -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/opt/X11/include -isystem/opt/X11/include/freetype2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers -I/usr/local/opt/icu4c/include -I/usr/local/opt/gettext/include
superenv executed: clang++ -pipe -Os -march=core2 -std=c++11 -stdlib=libc++ -c -g -O2 conftest.cpp -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/opt/X11/include -isystem/opt/X11/include/freetype2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers -I/usr/local/opt/icu4c/include -I/usr/local/opt/gettext/include

clang++ called with: -E conftest.cpp
superenv added:    -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/opt/X11/include -isystem/opt/X11/include/freetype2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers -I/usr/local/opt/icu4c/include -I/usr/local/opt/gettext/include
superenv executed: clang++ -E conftest.cpp -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/opt/X11/include -isystem/opt/X11/include/freetype2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers -I/usr/local/opt/icu4c/include -I/usr/local/opt/gettext/include

clang++ called with: -c -g -O2 conftest.cpp
superenv added:    -pipe -Os -march=core2 -std=c++11 -stdlib=libc++ -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/opt/X11/include -isystem/opt/X11/include/freetype2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers -I/usr/local/opt/icu4c/include -I/usr/local/opt/gettext/include
superenv executed: clang++ -pipe -Os -march=core2 -std=c++11 -stdlib=libc++ -c -g -O2 conftest.cpp -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/opt/X11/include -isystem/opt/X11/include/freetype2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers -I/usr/local/opt/icu4c/include -I/usr/local/opt/gettext/include

clang++ called with: -E conftest.cpp
superenv added:    -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/opt/X11/include -isystem/opt/X11/include/freetype2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers -I/usr/local/opt/icu4c/include -I/usr/local/opt/gettext/include
superenv executed: clang++ -E conftest.cpp -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/opt/X11/include -isystem/opt/X11/include/freetype2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers -I/usr/local/opt/icu4c/include -I/usr/local/opt/gettext/include

clang++ called with: -c -g -O2 conftest.cpp
superenv added:    -pipe -Os -march=core2 -std=c++11 -stdlib=libc++ -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/opt/X11/include -isystem/opt/X11/include/freetype2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers -I/usr/local/opt/icu4c/include -I/usr/local/opt/gettext/include
superenv executed: clang++ -pipe -Os -march=core2 -std=c++11 -stdlib=libc++ -c -g -O2 conftest.cpp -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/opt/X11/include -isystem/opt/X11/include/freetype2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers -I/usr/local/opt/icu4c/include -I/usr/local/opt/gettext/include

clang++ called with: -c -g -O2 conftest.cpp
superenv added:    -pipe -Os -march=core2 -std=c++11 -stdlib=libc++ -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/opt/X11/include -isystem/opt/X11/include/freetype2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers -I/usr/local/opt/icu4c/include -I/usr/local/opt/gettext/include
superenv executed: clang++ -pipe -Os -march=core2 -std=c++11 -stdlib=libc++ -c -g -O2 conftest.cpp -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/opt/X11/include -isystem/opt/X11/include/freetype2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers -I/usr/local/opt/icu4c/include -I/usr/local/opt/gettext/include

clang++ called with: -c -g -O2 conftest.cpp
superenv added:    -pipe -Os -march=core2 -std=c++11 -stdlib=libc++ -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/opt/X11/include -isystem/opt/X11/include/freetype2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers -I/usr/local/opt/icu4c/include -I/usr/local/opt/gettext/include
superenv executed: clang++ -pipe -Os -march=core2 -std=c++11 -stdlib=libc++ -c -g -O2 conftest.cpp -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/opt/X11/include -isystem/opt/X11/include/freetype2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers -I/usr/local/opt/icu4c/include -I/usr/local/opt/gettext/include

clang++ called with: -o conftest -g -O2 -L/usr/local/opt/icu4c/lib conftest.cpp
superenv added:    -pipe -Os -march=core2 -std=c++11 -stdlib=libc++ -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/opt/X11/include -isystem/opt/X11/include/freetype2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers -I/usr/local/opt/icu4c/include -I/usr/local/opt/gettext/include -L/usr/local/opt/gettext/lib -L/usr/local/opt/libffi/lib -L/usr/local/lib -L/opt/X11/lib -L/System/Library/Frameworks/OpenGL.framework/Versions/Current/Libraries -Wl,-headerpad_max_install_names
superenv executed: clang++ -pipe -Os -march=core2 -std=c++11 -stdlib=libc++ -o conftest -g -O2 -L/usr/local/opt/icu4c/lib conftest.cpp -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/opt/X11/include -isystem/opt/X11/include/freetype2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers -I/usr/local/opt/icu4c/include -I/usr/local/opt/gettext/include -L/usr/local/opt/icu4c/lib -L/usr/local/opt/gettext/lib -L/usr/local/opt/libffi/lib -L/usr/local/lib -L/opt/X11/lib -L/System/Library/Frameworks/OpenGL.framework/Versions/Current/Libraries -Wl,-headerpad_max_install_names

clang++ called with: -c -g -O2 conftest.cpp
superenv added:    -pipe -Os -march=core2 -std=c++11 -stdlib=libc++ -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/opt/X11/include -isystem/opt/X11/include/freetype2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers -I/usr/local/opt/icu4c/include -I/usr/local/opt/gettext/include
superenv executed: clang++ -pipe -Os -march=core2 -std=c++11 -stdlib=libc++ -c -g -O2 conftest.cpp -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/opt/X11/include -isystem/opt/X11/include/freetype2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers -I/usr/local/opt/icu4c/include -I/usr/local/opt/gettext/include

clang++ called with: -c -g -O2 conftest.cpp
superenv added:    -pipe -Os -march=core2 -std=c++11 -stdlib=libc++ -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/opt/X11/include -isystem/opt/X11/include/freetype2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers -I/usr/local/opt/icu4c/include -I/usr/local/opt/gettext/include
superenv executed: clang++ -pipe -Os -march=core2 -std=c++11 -stdlib=libc++ -c -g -O2 conftest.cpp -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/opt/X11/include -isystem/opt/X11/include/freetype2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers -I/usr/local/opt/icu4c/include -I/usr/local/opt/gettext/include

clang++ called with: -c -g -O2 conftest.cpp
superenv added:    -pipe -Os -march=core2 -std=c++11 -stdlib=libc++ -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/opt/X11/include -isystem/opt/X11/include/freetype2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers -I/usr/local/opt/icu4c/include -I/usr/local/opt/gettext/include
superenv executed: clang++ -pipe -Os -march=core2 -std=c++11 -stdlib=libc++ -c -g -O2 conftest.cpp -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/opt/X11/include -isystem/opt/X11/include/freetype2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers -I/usr/local/opt/icu4c/include -I/usr/local/opt/gettext/include

clang++ called with: -c -g -O2 conftest.cpp
superenv added:    -pipe -Os -march=core2 -std=c++11 -stdlib=libc++ -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/opt/X11/include -isystem/opt/X11/include/freetype2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers -I/usr/local/opt/icu4c/include -I/usr/local/opt/gettext/include
superenv executed: clang++ -pipe -Os -march=core2 -std=c++11 -stdlib=libc++ -c -g -O2 conftest.cpp -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/opt/X11/include -isystem/opt/X11/include/freetype2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers -I/usr/local/opt/icu4c/include -I/usr/local/opt/gettext/include

clang++ called with: -c -g -O2 conftest.cpp
superenv added:    -pipe -Os -march=core2 -std=c++11 -stdlib=libc++ -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/opt/X11/include -isystem/opt/X11/include/freetype2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers -I/usr/local/opt/icu4c/include -I/usr/local/opt/gettext/include
superenv executed: clang++ -pipe -Os -march=core2 -std=c++11 -stdlib=libc++ -c -g -O2 conftest.cpp -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/opt/X11/include -isystem/opt/X11/include/freetype2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers -I/usr/local/opt/icu4c/include -I/usr/local/opt/gettext/include

clang++ called with: -c -g -O2 conftest.cpp
superenv added:    -pipe -Os -march=core2 -std=c++11 -stdlib=libc++ -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/opt/X11/include -isystem/opt/X11/include/freetype2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers -I/usr/local/opt/icu4c/include -I/usr/local/opt/gettext/include
superenv executed: clang++ -pipe -Os -march=core2 -std=c++11 -stdlib=libc++ -c -g -O2 conftest.cpp -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/opt/X11/include -isystem/opt/X11/include/freetype2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers -I/usr/local/opt/icu4c/include -I/usr/local/opt/gettext/include

clang++ called with: -c -g -O2 conftest.cpp
superenv added:    -pipe -Os -march=core2 -std=c++11 -stdlib=libc++ -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/opt/X11/include -isystem/opt/X11/include/freetype2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers -I/usr/local/opt/icu4c/include -I/usr/local/opt/gettext/include
superenv executed: clang++ -pipe -Os -march=core2 -std=c++11 -stdlib=libc++ -c -g -O2 conftest.cpp -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/opt/X11/include -isystem/opt/X11/include/freetype2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers -I/usr/local/opt/icu4c/include -I/usr/local/opt/gettext/include

clang++ called with: -c -g -O2 conftest.cpp
superenv added:    -pipe -Os -march=core2 -std=c++11 -stdlib=libc++ -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/opt/X11/include -isystem/opt/X11/include/freetype2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers -I/usr/local/opt/icu4c/include -I/usr/local/opt/gettext/include
superenv executed: clang++ -pipe -Os -march=core2 -std=c++11 -stdlib=libc++ -c -g -O2 conftest.cpp -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/opt/X11/include -isystem/opt/X11/include/freetype2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers -I/usr/local/opt/icu4c/include -I/usr/local/opt/gettext/include

clang++ called with: -o conftest -g -O2 -I/usr/local/include/leptonica -L/usr/local/opt/icu4c/lib conftest.cpp -llept
superenv added:    -pipe -Os -march=core2 -std=c++11 -stdlib=libc++ -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/opt/X11/include -isystem/opt/X11/include/freetype2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers -I/usr/local/opt/icu4c/include -I/usr/local/opt/gettext/include -L/usr/local/opt/gettext/lib -L/usr/local/opt/libffi/lib -L/usr/local/lib -L/opt/X11/lib -L/System/Library/Frameworks/OpenGL.framework/Versions/Current/Libraries -Wl,-headerpad_max_install_names
superenv executed: clang++ -pipe -Os -march=core2 -std=c++11 -stdlib=libc++ -o conftest -g -O2 -I/usr/local/include/leptonica -L/usr/local/opt/icu4c/lib conftest.cpp -llept -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/opt/X11/include -isystem/opt/X11/include/freetype2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers -I/usr/local/opt/icu4c/include -I/usr/local/opt/gettext/include -L/usr/local/opt/icu4c/lib -L/usr/local/opt/gettext/lib -L/usr/local/opt/libffi/lib -L/usr/local/lib -L/opt/X11/lib -L/System/Library/Frameworks/OpenGL.framework/Versions/Current/Libraries -Wl,-headerpad_max_install_names

clang++ called with: -E -I/usr/local/include/leptonica conftest.cpp
superenv added:    -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/opt/X11/include -isystem/opt/X11/include/freetype2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers -I/usr/local/opt/icu4c/include -I/usr/local/opt/gettext/include
superenv executed: clang++ -E -I/usr/local/include/leptonica conftest.cpp -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/opt/X11/include -isystem/opt/X11/include/freetype2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers -I/usr/local/opt/icu4c/include -I/usr/local/opt/gettext/include

clang++ called with: -c -g -O2 -I/usr/local/include/leptonica conftest.cpp
superenv added:    -pipe -Os -march=core2 -std=c++11 -stdlib=libc++ -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/opt/X11/include -isystem/opt/X11/include/freetype2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers -I/usr/local/opt/icu4c/include -I/usr/local/opt/gettext/include
superenv executed: clang++ -pipe -Os -march=core2 -std=c++11 -stdlib=libc++ -c -g -O2 -I/usr/local/include/leptonica conftest.cpp -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/opt/X11/include -isystem/opt/X11/include/freetype2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers -I/usr/local/opt/icu4c/include -I/usr/local/opt/gettext/include

clang++ called with: -E -I/usr/local/include/leptonica conftest.cpp
superenv added:    -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/opt/X11/include -isystem/opt/X11/include/freetype2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers -I/usr/local/opt/icu4c/include -I/usr/local/opt/gettext/include
superenv executed: clang++ -E -I/usr/local/include/leptonica conftest.cpp -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/opt/X11/include -isystem/opt/X11/include/freetype2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers -I/usr/local/opt/icu4c/include -I/usr/local/opt/gettext/include

