ld called with: --version
superenv added:    -L/usr/local/lib -L/System/Library/Frameworks/OpenGL.framework/Versions/Current/Libraries -headerpad_max_install_names
superenv executed: ld -L/usr/local/lib -L/System/Library/Frameworks/OpenGL.framework/Versions/Current/Libraries -headerpad_max_install_names --version

clang called with: -fdebug-prefix-map=a=b -c trivial.c
superenv added:    -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers
superenv executed: clang -fdebug-prefix-map=a=b -c trivial.c -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers

clang called with: -gno-record-gcc-switches -c trivial.c
superenv added:    -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers
superenv executed: clang -gno-record-gcc-switches -c trivial.c -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers

clang called with: --help
superenv added:    -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers -L/usr/local/lib -L/System/Library/Frameworks/OpenGL.framework/Versions/Current/Libraries -Wl,-headerpad_max_install_names
superenv executed: clang --help -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers -L/usr/local/lib -L/System/Library/Frameworks/OpenGL.framework/Versions/Current/Libraries -Wl,-headerpad_max_install_names

clang called with: -fdebug-prefix-map=a=b -c trivial.c
superenv added:    -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers
superenv executed: clang -fdebug-prefix-map=a=b -c trivial.c -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers

clang called with: -gno-record-gcc-switches -c trivial.c
superenv added:    -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers
superenv executed: clang -gno-record-gcc-switches -c trivial.c -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers

clang called with: -fdebug-prefix-map=a=b -c trivial.c
superenv added:    -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers
superenv executed: clang -fdebug-prefix-map=a=b -c trivial.c -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers

clang called with: -gno-record-gcc-switches -c trivial.c
superenv added:    -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers
superenv executed: clang -gno-record-gcc-switches -c trivial.c -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers

clang called with: -E -dM -m64 -I /tmp/go-build803923973/runtime/cgo/_obj/ -g -O2 -Wall -Werror -I . /tmp/cgo-gcc-input-034318090.c
superenv added:    -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers
superenv executed: clang -E -dM -m64 -I /tmp/go-build803923973/runtime/cgo/_obj/ -g -O2 -Wall -Werror -I . /tmp/cgo-gcc-input-034318090.c -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers

clang called with: -fdebug-prefix-map=a=b -c trivial.c
superenv added:    -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers
superenv executed: clang -fdebug-prefix-map=a=b -c trivial.c -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers

clang called with: -gno-record-gcc-switches -c trivial.c
superenv added:    -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers
superenv executed: clang -gno-record-gcc-switches -c trivial.c -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers

clang called with: -I /private/tmp/go-20170217-86759-1l6igmj/go/src/runtime/cgo -fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build803923973=/tmp/go-build -gno-record-gcc-switches -fno-common -I /tmp/go-build803923973/runtime/cgo/_obj/ -g -O2 -Wall -Werror -o /tmp/go-build803923973/runtime/cgo/_obj/_cgo_export.o -c /tmp/go-build803923973/runtime/cgo/_obj/_cgo_export.c
superenv added:    -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers
superenv executed: clang -I /private/tmp/go-20170217-86759-1l6igmj/go/src/runtime/cgo -fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build803923973=/tmp/go-build -gno-record-gcc-switches -fno-common -I /tmp/go-build803923973/runtime/cgo/_obj/ -g -O2 -Wall -Werror -o /tmp/go-build803923973/runtime/cgo/_obj/_cgo_export.o -c /tmp/go-build803923973/runtime/cgo/_obj/_cgo_export.c -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers

clang called with: -I /private/tmp/go-20170217-86759-1l6igmj/go/src/runtime/cgo -fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build803923973=/tmp/go-build -gno-record-gcc-switches -fno-common -I /tmp/go-build803923973/runtime/cgo/_obj/ -g -O2 -Wall -Werror -o /tmp/go-build803923973/runtime/cgo/_obj/cgo.cgo2.o -c /tmp/go-build803923973/runtime/cgo/_obj/cgo.cgo2.c
superenv added:    -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers
superenv executed: clang -I /private/tmp/go-20170217-86759-1l6igmj/go/src/runtime/cgo -fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build803923973=/tmp/go-build -gno-record-gcc-switches -fno-common -I /tmp/go-build803923973/runtime/cgo/_obj/ -g -O2 -Wall -Werror -o /tmp/go-build803923973/runtime/cgo/_obj/cgo.cgo2.o -c /tmp/go-build803923973/runtime/cgo/_obj/cgo.cgo2.c -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers

clang called with: -I /private/tmp/go-20170217-86759-1l6igmj/go/src/runtime/cgo -fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build803923973=/tmp/go-build -gno-record-gcc-switches -fno-common -I /tmp/go-build803923973/runtime/cgo/_obj/ -g -O2 -Wall -Werror -o /tmp/go-build803923973/runtime/cgo/_obj/gcc_context.o -c /private/tmp/go-20170217-86759-1l6igmj/go/src/runtime/cgo/gcc_context.c
superenv added:    -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers
superenv executed: clang -I /private/tmp/go-20170217-86759-1l6igmj/go/src/runtime/cgo -fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build803923973=/tmp/go-build -gno-record-gcc-switches -fno-common -I /tmp/go-build803923973/runtime/cgo/_obj/ -g -O2 -Wall -Werror -o /tmp/go-build803923973/runtime/cgo/_obj/gcc_context.o -c /private/tmp/go-20170217-86759-1l6igmj/go/src/runtime/cgo/gcc_context.c -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers

clang called with: -I /private/tmp/go-20170217-86759-1l6igmj/go/src/runtime/cgo -fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build803923973=/tmp/go-build -gno-record-gcc-switches -fno-common -I /tmp/go-build803923973/runtime/cgo/_obj/ -g -O2 -Wall -Werror -o /tmp/go-build803923973/runtime/cgo/_obj/gcc_darwin_amd64.o -c /private/tmp/go-20170217-86759-1l6igmj/go/src/runtime/cgo/gcc_darwin_amd64.c
superenv added:    -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers
superenv executed: clang -I /private/tmp/go-20170217-86759-1l6igmj/go/src/runtime/cgo -fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build803923973=/tmp/go-build -gno-record-gcc-switches -fno-common -I /tmp/go-build803923973/runtime/cgo/_obj/ -g -O2 -Wall -Werror -o /tmp/go-build803923973/runtime/cgo/_obj/gcc_darwin_amd64.o -c /private/tmp/go-20170217-86759-1l6igmj/go/src/runtime/cgo/gcc_darwin_amd64.c -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers

clang called with: -I /private/tmp/go-20170217-86759-1l6igmj/go/src/runtime/cgo -fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build803923973=/tmp/go-build -gno-record-gcc-switches -fno-common -I /tmp/go-build803923973/runtime/cgo/_obj/ -g -O2 -Wall -Werror -o /tmp/go-build803923973/runtime/cgo/_obj/gcc_libinit.o -c /private/tmp/go-20170217-86759-1l6igmj/go/src/runtime/cgo/gcc_libinit.c
superenv added:    -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers
superenv executed: clang -I /private/tmp/go-20170217-86759-1l6igmj/go/src/runtime/cgo -fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build803923973=/tmp/go-build -gno-record-gcc-switches -fno-common -I /tmp/go-build803923973/runtime/cgo/_obj/ -g -O2 -Wall -Werror -o /tmp/go-build803923973/runtime/cgo/_obj/gcc_libinit.o -c /private/tmp/go-20170217-86759-1l6igmj/go/src/runtime/cgo/gcc_libinit.c -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers

clang called with: -I /private/tmp/go-20170217-86759-1l6igmj/go/src/runtime/cgo -fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build803923973=/tmp/go-build -gno-record-gcc-switches -fno-common -I /tmp/go-build803923973/runtime/cgo/_obj/ -g -O2 -Wall -Werror -o /tmp/go-build803923973/runtime/cgo/_obj/gcc_setenv.o -c /private/tmp/go-20170217-86759-1l6igmj/go/src/runtime/cgo/gcc_setenv.c
superenv added:    -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers
superenv executed: clang -I /private/tmp/go-20170217-86759-1l6igmj/go/src/runtime/cgo -fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build803923973=/tmp/go-build -gno-record-gcc-switches -fno-common -I /tmp/go-build803923973/runtime/cgo/_obj/ -g -O2 -Wall -Werror -o /tmp/go-build803923973/runtime/cgo/_obj/gcc_setenv.o -c /private/tmp/go-20170217-86759-1l6igmj/go/src/runtime/cgo/gcc_setenv.c -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers

clang called with: -I /private/tmp/go-20170217-86759-1l6igmj/go/src/runtime/cgo -fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build803923973=/tmp/go-build -gno-record-gcc-switches -fno-common -I /tmp/go-build803923973/runtime/cgo/_obj/ -g -O2 -Wall -Werror -o /tmp/go-build803923973/runtime/cgo/_obj/gcc_util.o -c /private/tmp/go-20170217-86759-1l6igmj/go/src/runtime/cgo/gcc_util.c
superenv added:    -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers
superenv executed: clang -I /private/tmp/go-20170217-86759-1l6igmj/go/src/runtime/cgo -fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build803923973=/tmp/go-build -gno-record-gcc-switches -fno-common -I /tmp/go-build803923973/runtime/cgo/_obj/ -g -O2 -Wall -Werror -o /tmp/go-build803923973/runtime/cgo/_obj/gcc_util.o -c /private/tmp/go-20170217-86759-1l6igmj/go/src/runtime/cgo/gcc_util.c -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers

clang called with: -I /private/tmp/go-20170217-86759-1l6igmj/go/src/runtime/cgo -fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build803923973=/tmp/go-build -gno-record-gcc-switches -fno-common -I /tmp/go-build803923973/runtime/cgo/_obj/ -g -O2 -Wall -Werror -o /tmp/go-build803923973/runtime/cgo/_obj/gcc_amd64.o -c /private/tmp/go-20170217-86759-1l6igmj/go/src/runtime/cgo/gcc_amd64.S
superenv added:    -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers
superenv executed: clang -I /private/tmp/go-20170217-86759-1l6igmj/go/src/runtime/cgo -fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build803923973=/tmp/go-build -gno-record-gcc-switches -fno-common -I /tmp/go-build803923973/runtime/cgo/_obj/ -g -O2 -Wall -Werror -o /tmp/go-build803923973/runtime/cgo/_obj/gcc_amd64.o -c /private/tmp/go-20170217-86759-1l6igmj/go/src/runtime/cgo/gcc_amd64.S -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers

clang called with: -I /private/tmp/go-20170217-86759-1l6igmj/go/src/runtime/cgo -fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build803923973=/tmp/go-build -gno-record-gcc-switches -fno-common -I /tmp/go-build803923973/runtime/cgo/_obj/ -g -O2 -Wall -Werror -o /tmp/go-build803923973/runtime/cgo/_obj/_cgo_main.o -c /tmp/go-build803923973/runtime/cgo/_obj/_cgo_main.c
superenv added:    -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers
superenv executed: clang -I /private/tmp/go-20170217-86759-1l6igmj/go/src/runtime/cgo -fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build803923973=/tmp/go-build -gno-record-gcc-switches -fno-common -I /tmp/go-build803923973/runtime/cgo/_obj/ -g -O2 -Wall -Werror -o /tmp/go-build803923973/runtime/cgo/_obj/_cgo_main.o -c /tmp/go-build803923973/runtime/cgo/_obj/_cgo_main.c -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers

clang called with: -I /private/tmp/go-20170217-86759-1l6igmj/go/src/runtime/cgo -fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build803923973=/tmp/go-build -gno-record-gcc-switches -fno-common -o /tmp/go-build803923973/runtime/cgo/_obj/_cgo_.o /tmp/go-build803923973/runtime/cgo/_obj/_cgo_main.o /tmp/go-build803923973/runtime/cgo/_obj/_cgo_export.o /tmp/go-build803923973/runtime/cgo/_obj/cgo.cgo2.o /tmp/go-build803923973/runtime/cgo/_obj/gcc_context.o /tmp/go-build803923973/runtime/cgo/_obj/gcc_darwin_amd64.o /tmp/go-build803923973/runtime/cgo/_obj/gcc_libinit.o /tmp/go-build803923973/runtime/cgo/_obj/gcc_setenv.o /tmp/go-build803923973/runtime/cgo/_obj/gcc_util.o /tmp/go-build803923973/runtime/cgo/_obj/gcc_amd64.o -g -O2 -lpthread
superenv added:    -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers -L/usr/local/lib -L/System/Library/Frameworks/OpenGL.framework/Versions/Current/Libraries -Wl,-headerpad_max_install_names
superenv executed: clang -I /private/tmp/go-20170217-86759-1l6igmj/go/src/runtime/cgo -fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build803923973=/tmp/go-build -gno-record-gcc-switches -fno-common -o /tmp/go-build803923973/runtime/cgo/_obj/_cgo_.o /tmp/go-build803923973/runtime/cgo/_obj/_cgo_main.o /tmp/go-build803923973/runtime/cgo/_obj/_cgo_export.o /tmp/go-build803923973/runtime/cgo/_obj/cgo.cgo2.o /tmp/go-build803923973/runtime/cgo/_obj/gcc_context.o /tmp/go-build803923973/runtime/cgo/_obj/gcc_darwin_amd64.o /tmp/go-build803923973/runtime/cgo/_obj/gcc_libinit.o /tmp/go-build803923973/runtime/cgo/_obj/gcc_setenv.o /tmp/go-build803923973/runtime/cgo/_obj/gcc_util.o /tmp/go-build803923973/runtime/cgo/_obj/gcc_amd64.o -g -O2 -lpthread -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers -L/usr/local/lib -L/System/Library/Frameworks/OpenGL.framework/Versions/Current/Libraries -Wl,-headerpad_max_install_names

clang called with: -no-pie -c trivial.c
superenv added:    -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers
superenv executed: clang -no-pie -c trivial.c -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers

clang called with: -I /private/tmp/go-20170217-86759-1l6igmj/go/src/runtime/cgo -fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build803923973=/tmp/go-build -gno-record-gcc-switches -fno-common -o /tmp/go-build803923973/runtime/cgo/_obj/_all.o /tmp/go-build803923973/runtime/cgo/_obj/_cgo_export.o /tmp/go-build803923973/runtime/cgo/_obj/cgo.cgo2.o /tmp/go-build803923973/runtime/cgo/_obj/gcc_context.o /tmp/go-build803923973/runtime/cgo/_obj/gcc_darwin_amd64.o /tmp/go-build803923973/runtime/cgo/_obj/gcc_libinit.o /tmp/go-build803923973/runtime/cgo/_obj/gcc_setenv.o /tmp/go-build803923973/runtime/cgo/_obj/gcc_util.o /tmp/go-build803923973/runtime/cgo/_obj/gcc_amd64.o -g -O2 -Wl,-r -nostdlib
superenv added:    -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers -L/usr/local/lib -L/System/Library/Frameworks/OpenGL.framework/Versions/Current/Libraries -Wl,-headerpad_max_install_names
superenv executed: clang -I /private/tmp/go-20170217-86759-1l6igmj/go/src/runtime/cgo -fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build803923973=/tmp/go-build -gno-record-gcc-switches -fno-common -o /tmp/go-build803923973/runtime/cgo/_obj/_all.o /tmp/go-build803923973/runtime/cgo/_obj/_cgo_export.o /tmp/go-build803923973/runtime/cgo/_obj/cgo.cgo2.o /tmp/go-build803923973/runtime/cgo/_obj/gcc_context.o /tmp/go-build803923973/runtime/cgo/_obj/gcc_darwin_amd64.o /tmp/go-build803923973/runtime/cgo/_obj/gcc_libinit.o /tmp/go-build803923973/runtime/cgo/_obj/gcc_setenv.o /tmp/go-build803923973/runtime/cgo/_obj/gcc_util.o /tmp/go-build803923973/runtime/cgo/_obj/gcc_amd64.o -g -O2 -Wl,-r -nostdlib -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers -L/usr/local/lib -L/System/Library/Frameworks/OpenGL.framework/Versions/Current/Libraries -Wl,-headerpad_max_install_names

clang called with: -E -dM -m64 -I /tmp/go-build803923973/net/_obj/ -g -O2 -I . /tmp/cgo-gcc-input-513247399.c
superenv added:    -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers
superenv executed: clang -E -dM -m64 -I /tmp/go-build803923973/net/_obj/ -g -O2 -I . /tmp/cgo-gcc-input-513247399.c -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers

clang called with: -w -Wno-error -o/tmp/go-build803923973/net/_obj//_cgo_.o -gdwarf-2 -c -ferror-limit=0 -Wno-unknown-warning-option -Wno-unneeded-internal-declaration -Wno-unused-function -Qunused-arguments -fno-builtin -I /tmp/go-build803923973/net/_obj/ -g -m64 -I . /tmp/cgo-gcc-input-404411866.c
superenv added:    -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers
superenv executed: clang -w -Wno-error -o/tmp/go-build803923973/net/_obj//_cgo_.o -gdwarf-2 -c -ferror-limit=0 -Wno-unknown-warning-option -Wno-unneeded-internal-declaration -Wno-unused-function -Qunused-arguments -fno-builtin -I /tmp/go-build803923973/net/_obj/ -g -m64 -I . /tmp/cgo-gcc-input-404411866.c -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers

clang called with: -w -Wno-error -o/tmp/go-build803923973/net/_obj//_cgo_.o -gdwarf-2 -c -ferror-limit=0 -Wno-unknown-warning-option -Wno-unneeded-internal-declaration -Wno-unused-function -Qunused-arguments -fno-builtin -I /tmp/go-build803923973/net/_obj/ -g -O2 -m64 -I . /tmp/cgo-gcc-input-364423025.c
superenv added:    -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers
superenv executed: clang -w -Wno-error -o/tmp/go-build803923973/net/_obj//_cgo_.o -gdwarf-2 -c -ferror-limit=0 -Wno-unknown-warning-option -Wno-unneeded-internal-declaration -Wno-unused-function -Qunused-arguments -fno-builtin -I /tmp/go-build803923973/net/_obj/ -g -O2 -m64 -I . /tmp/cgo-gcc-input-364423025.c -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers

clang called with: -E -dM -m64 -I /tmp/go-build803923973/net/_obj/ -g -O2 -I . /tmp/cgo-gcc-input-967976988.c
superenv added:    -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers
superenv executed: clang -E -dM -m64 -I /tmp/go-build803923973/net/_obj/ -g -O2 -I . /tmp/cgo-gcc-input-967976988.c -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers

clang called with: -w -Wno-error -o/tmp/go-build803923973/net/_obj//_cgo_.o -gdwarf-2 -c -ferror-limit=0 -Wno-unknown-warning-option -Wno-unneeded-internal-declaration -Wno-unused-function -Qunused-arguments -fno-builtin -I /tmp/go-build803923973/net/_obj/ -g -m64 -I . /tmp/cgo-gcc-input-957500107.c
superenv added:    -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers
superenv executed: clang -w -Wno-error -o/tmp/go-build803923973/net/_obj//_cgo_.o -gdwarf-2 -c -ferror-limit=0 -Wno-unknown-warning-option -Wno-unneeded-internal-declaration -Wno-unused-function -Qunused-arguments -fno-builtin -I /tmp/go-build803923973/net/_obj/ -g -m64 -I . /tmp/cgo-gcc-input-957500107.c -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers

clang called with: -w -Wno-error -o/tmp/go-build803923973/net/_obj//_cgo_.o -gdwarf-2 -c -ferror-limit=0 -Wno-unknown-warning-option -Wno-unneeded-internal-declaration -Wno-unused-function -Qunused-arguments -fno-builtin -I /tmp/go-build803923973/net/_obj/ -g -O2 -m64 -I . /tmp/cgo-gcc-input-033908654.c
superenv added:    -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers
superenv executed: clang -w -Wno-error -o/tmp/go-build803923973/net/_obj//_cgo_.o -gdwarf-2 -c -ferror-limit=0 -Wno-unknown-warning-option -Wno-unneeded-internal-declaration -Wno-unused-function -Qunused-arguments -fno-builtin -I /tmp/go-build803923973/net/_obj/ -g -O2 -m64 -I . /tmp/cgo-gcc-input-033908654.c -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers

clang called with: -E -dM -m64 -I /tmp/go-build803923973/net/_obj/ -g -O2 -I . /tmp/cgo-gcc-input-650966837.c
superenv added:    -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers
superenv executed: clang -E -dM -m64 -I /tmp/go-build803923973/net/_obj/ -g -O2 -I . /tmp/cgo-gcc-input-650966837.c -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers

clang called with: -w -Wno-error -o/tmp/go-build803923973/net/_obj//_cgo_.o -gdwarf-2 -c -ferror-limit=0 -Wno-unknown-warning-option -Wno-unneeded-internal-declaration -Wno-unused-function -Qunused-arguments -fno-builtin -I /tmp/go-build803923973/net/_obj/ -g -O2 -m64 -I . /tmp/cgo-gcc-input-727958800.c
superenv added:    -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers
superenv executed: clang -w -Wno-error -o/tmp/go-build803923973/net/_obj//_cgo_.o -gdwarf-2 -c -ferror-limit=0 -Wno-unknown-warning-option -Wno-unneeded-internal-declaration -Wno-unused-function -Qunused-arguments -fno-builtin -I /tmp/go-build803923973/net/_obj/ -g -O2 -m64 -I . /tmp/cgo-gcc-input-727958800.c -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers

clang called with: -E -dM -m64 -I /tmp/go-build803923973/net/_obj/ -g -O2 -I . /tmp/cgo-gcc-input-080526639.c
superenv added:    -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers
superenv executed: clang -E -dM -m64 -I /tmp/go-build803923973/net/_obj/ -g -O2 -I . /tmp/cgo-gcc-input-080526639.c -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers

clang called with: -w -Wno-error -o/tmp/go-build803923973/net/_obj//_cgo_.o -gdwarf-2 -c -ferror-limit=0 -Wno-unknown-warning-option -Wno-unneeded-internal-declaration -Wno-unused-function -Qunused-arguments -fno-builtin -I /tmp/go-build803923973/net/_obj/ -g -m64 -I . /tmp/cgo-gcc-input-486846658.c
superenv added:    -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers
superenv executed: clang -w -Wno-error -o/tmp/go-build803923973/net/_obj//_cgo_.o -gdwarf-2 -c -ferror-limit=0 -Wno-unknown-warning-option -Wno-unneeded-internal-declaration -Wno-unused-function -Qunused-arguments -fno-builtin -I /tmp/go-build803923973/net/_obj/ -g -m64 -I . /tmp/cgo-gcc-input-486846658.c -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers

clang called with: -w -Wno-error -o/tmp/go-build803923973/net/_obj//_cgo_.o -gdwarf-2 -c -ferror-limit=0 -Wno-unknown-warning-option -Wno-unneeded-internal-declaration -Wno-unused-function -Qunused-arguments -fno-builtin -I /tmp/go-build803923973/net/_obj/ -g -O2 -m64 -I . /tmp/cgo-gcc-input-521404217.c
superenv added:    -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers
superenv executed: clang -w -Wno-error -o/tmp/go-build803923973/net/_obj//_cgo_.o -gdwarf-2 -c -ferror-limit=0 -Wno-unknown-warning-option -Wno-unneeded-internal-declaration -Wno-unused-function -Qunused-arguments -fno-builtin -I /tmp/go-build803923973/net/_obj/ -g -O2 -m64 -I . /tmp/cgo-gcc-input-521404217.c -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers

clang called with: -I /private/tmp/go-20170217-86759-1l6igmj/go/src/net -fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build803923973=/tmp/go-build -gno-record-gcc-switches -fno-common -I /tmp/go-build803923973/net/_obj/ -g -O2 -o /tmp/go-build803923973/net/_obj/_cgo_export.o -c /tmp/go-build803923973/net/_obj/_cgo_export.c
superenv added:    -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers
superenv executed: clang -I /private/tmp/go-20170217-86759-1l6igmj/go/src/net -fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build803923973=/tmp/go-build -gno-record-gcc-switches -fno-common -I /tmp/go-build803923973/net/_obj/ -g -O2 -o /tmp/go-build803923973/net/_obj/_cgo_export.o -c /tmp/go-build803923973/net/_obj/_cgo_export.c -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers

clang called with: -I /private/tmp/go-20170217-86759-1l6igmj/go/src/net -fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build803923973=/tmp/go-build -gno-record-gcc-switches -fno-common -I /tmp/go-build803923973/net/_obj/ -g -O2 -o /tmp/go-build803923973/net/_obj/cgo_bsd.cgo2.o -c /tmp/go-build803923973/net/_obj/cgo_bsd.cgo2.c
superenv added:    -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers
superenv executed: clang -I /private/tmp/go-20170217-86759-1l6igmj/go/src/net -fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build803923973=/tmp/go-build -gno-record-gcc-switches -fno-common -I /tmp/go-build803923973/net/_obj/ -g -O2 -o /tmp/go-build803923973/net/_obj/cgo_bsd.cgo2.o -c /tmp/go-build803923973/net/_obj/cgo_bsd.cgo2.c -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers

clang called with: -I /private/tmp/go-20170217-86759-1l6igmj/go/src/net -fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build803923973=/tmp/go-build -gno-record-gcc-switches -fno-common -I /tmp/go-build803923973/net/_obj/ -g -O2 -o /tmp/go-build803923973/net/_obj/cgo_resnew.cgo2.o -c /tmp/go-build803923973/net/_obj/cgo_resnew.cgo2.c
superenv added:    -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers
superenv executed: clang -I /private/tmp/go-20170217-86759-1l6igmj/go/src/net -fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build803923973=/tmp/go-build -gno-record-gcc-switches -fno-common -I /tmp/go-build803923973/net/_obj/ -g -O2 -o /tmp/go-build803923973/net/_obj/cgo_resnew.cgo2.o -c /tmp/go-build803923973/net/_obj/cgo_resnew.cgo2.c -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers

clang called with: -I /private/tmp/go-20170217-86759-1l6igmj/go/src/net -fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build803923973=/tmp/go-build -gno-record-gcc-switches -fno-common -I /tmp/go-build803923973/net/_obj/ -g -O2 -o /tmp/go-build803923973/net/_obj/cgo_sockold.cgo2.o -c /tmp/go-build803923973/net/_obj/cgo_sockold.cgo2.c
superenv added:    -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers
superenv executed: clang -I /private/tmp/go-20170217-86759-1l6igmj/go/src/net -fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build803923973=/tmp/go-build -gno-record-gcc-switches -fno-common -I /tmp/go-build803923973/net/_obj/ -g -O2 -o /tmp/go-build803923973/net/_obj/cgo_sockold.cgo2.o -c /tmp/go-build803923973/net/_obj/cgo_sockold.cgo2.c -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers

clang called with: -I /private/tmp/go-20170217-86759-1l6igmj/go/src/net -fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build803923973=/tmp/go-build -gno-record-gcc-switches -fno-common -I /tmp/go-build803923973/net/_obj/ -g -O2 -o /tmp/go-build803923973/net/_obj/cgo_unix.cgo2.o -c /tmp/go-build803923973/net/_obj/cgo_unix.cgo2.c
superenv added:    -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers
superenv executed: clang -I /private/tmp/go-20170217-86759-1l6igmj/go/src/net -fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build803923973=/tmp/go-build -gno-record-gcc-switches -fno-common -I /tmp/go-build803923973/net/_obj/ -g -O2 -o /tmp/go-build803923973/net/_obj/cgo_unix.cgo2.o -c /tmp/go-build803923973/net/_obj/cgo_unix.cgo2.c -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers

clang called with: -I /private/tmp/go-20170217-86759-1l6igmj/go/src/net -fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build803923973=/tmp/go-build -gno-record-gcc-switches -fno-common -I /tmp/go-build803923973/net/_obj/ -g -O2 -o /tmp/go-build803923973/net/_obj/_cgo_main.o -c /tmp/go-build803923973/net/_obj/_cgo_main.c
superenv added:    -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers
superenv executed: clang -I /private/tmp/go-20170217-86759-1l6igmj/go/src/net -fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build803923973=/tmp/go-build -gno-record-gcc-switches -fno-common -I /tmp/go-build803923973/net/_obj/ -g -O2 -o /tmp/go-build803923973/net/_obj/_cgo_main.o -c /tmp/go-build803923973/net/_obj/_cgo_main.c -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers

clang called with: -I /private/tmp/go-20170217-86759-1l6igmj/go/src/net -fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build803923973=/tmp/go-build -gno-record-gcc-switches -fno-common -o /tmp/go-build803923973/net/_obj/_cgo_.o /tmp/go-build803923973/net/_obj/_cgo_main.o /tmp/go-build803923973/net/_obj/_cgo_export.o /tmp/go-build803923973/net/_obj/cgo_bsd.cgo2.o /tmp/go-build803923973/net/_obj/cgo_resnew.cgo2.o /tmp/go-build803923973/net/_obj/cgo_sockold.cgo2.o /tmp/go-build803923973/net/_obj/cgo_unix.cgo2.o -g -O2
superenv added:    -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers -L/usr/local/lib -L/System/Library/Frameworks/OpenGL.framework/Versions/Current/Libraries -Wl,-headerpad_max_install_names
superenv executed: clang -I /private/tmp/go-20170217-86759-1l6igmj/go/src/net -fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build803923973=/tmp/go-build -gno-record-gcc-switches -fno-common -o /tmp/go-build803923973/net/_obj/_cgo_.o /tmp/go-build803923973/net/_obj/_cgo_main.o /tmp/go-build803923973/net/_obj/_cgo_export.o /tmp/go-build803923973/net/_obj/cgo_bsd.cgo2.o /tmp/go-build803923973/net/_obj/cgo_resnew.cgo2.o /tmp/go-build803923973/net/_obj/cgo_sockold.cgo2.o /tmp/go-build803923973/net/_obj/cgo_unix.cgo2.o -g -O2 -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers -L/usr/local/lib -L/System/Library/Frameworks/OpenGL.framework/Versions/Current/Libraries -Wl,-headerpad_max_install_names

clang called with: -I /private/tmp/go-20170217-86759-1l6igmj/go/src/net -fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build803923973=/tmp/go-build -gno-record-gcc-switches -fno-common -o /tmp/go-build803923973/net/_obj/_all.o /tmp/go-build803923973/net/_obj/_cgo_export.o /tmp/go-build803923973/net/_obj/cgo_bsd.cgo2.o /tmp/go-build803923973/net/_obj/cgo_resnew.cgo2.o /tmp/go-build803923973/net/_obj/cgo_sockold.cgo2.o /tmp/go-build803923973/net/_obj/cgo_unix.cgo2.o -g -O2 -Wl,-r -nostdlib
superenv added:    -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers -L/usr/local/lib -L/System/Library/Frameworks/OpenGL.framework/Versions/Current/Libraries -Wl,-headerpad_max_install_names
superenv executed: clang -I /private/tmp/go-20170217-86759-1l6igmj/go/src/net -fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build803923973=/tmp/go-build -gno-record-gcc-switches -fno-common -o /tmp/go-build803923973/net/_obj/_all.o /tmp/go-build803923973/net/_obj/_cgo_export.o /tmp/go-build803923973/net/_obj/cgo_bsd.cgo2.o /tmp/go-build803923973/net/_obj/cgo_resnew.cgo2.o /tmp/go-build803923973/net/_obj/cgo_sockold.cgo2.o /tmp/go-build803923973/net/_obj/cgo_unix.cgo2.o -g -O2 -Wl,-r -nostdlib -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers -L/usr/local/lib -L/System/Library/Frameworks/OpenGL.framework/Versions/Current/Libraries -Wl,-headerpad_max_install_names

clang called with: -E -dM -m64 -I /tmp/go-build803923973/crypto/x509/_obj/ -g -O2 -mmacosx-version-min=10.6 -D__MAC_OS_X_VERSION_MAX_ALLOWED=1080 -I . /tmp/cgo-gcc-input-247634276.c
superenv added:    -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers
superenv executed: clang -E -dM -m64 -I /tmp/go-build803923973/crypto/x509/_obj/ -g -O2 -mmacosx-version-min=10.6 -D__MAC_OS_X_VERSION_MAX_ALLOWED=1080 -I . /tmp/cgo-gcc-input-247634276.c -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers

clang called with: -E -dM -m64 -I /tmp/go-build803923973/os/user/_obj/ -g -O2 -I . /tmp/cgo-gcc-input-903729375.c
superenv added:    -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers
superenv executed: clang -E -dM -m64 -I /tmp/go-build803923973/os/user/_obj/ -g -O2 -I . /tmp/cgo-gcc-input-903729375.c -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers

clang called with: -w -Wno-error -o/tmp/go-build803923973/os/user/_obj//_cgo_.o -gdwarf-2 -c -ferror-limit=0 -Wno-unknown-warning-option -Wno-unneeded-internal-declaration -Wno-unused-function -Qunused-arguments -fno-builtin -I /tmp/go-build803923973/os/user/_obj/ -g -m64 -I . /tmp/cgo-gcc-input-216140466.c
superenv added:    -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers
superenv executed: clang -w -Wno-error -o/tmp/go-build803923973/os/user/_obj//_cgo_.o -gdwarf-2 -c -ferror-limit=0 -Wno-unknown-warning-option -Wno-unneeded-internal-declaration -Wno-unused-function -Qunused-arguments -fno-builtin -I /tmp/go-build803923973/os/user/_obj/ -g -m64 -I . /tmp/cgo-gcc-input-216140466.c -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers

clang called with: -w -Wno-error -o/tmp/go-build803923973/os/user/_obj//_cgo_.o -gdwarf-2 -c -ferror-limit=0 -Wno-unknown-warning-option -Wno-unneeded-internal-declaration -Wno-unused-function -Qunused-arguments -fno-builtin -I /tmp/go-build803923973/os/user/_obj/ -g -O2 -m64 -I . /tmp/cgo-gcc-input-201090665.c
superenv added:    -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers
superenv executed: clang -w -Wno-error -o/tmp/go-build803923973/os/user/_obj//_cgo_.o -gdwarf-2 -c -ferror-limit=0 -Wno-unknown-warning-option -Wno-unneeded-internal-declaration -Wno-unused-function -Qunused-arguments -fno-builtin -I /tmp/go-build803923973/os/user/_obj/ -g -O2 -m64 -I . /tmp/cgo-gcc-input-201090665.c -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers

clang called with: -E -dM -m64 -I /tmp/go-build803923973/os/user/_obj/ -g -O2 -I . /tmp/cgo-gcc-input-601284788.c
superenv added:    -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers
superenv executed: clang -E -dM -m64 -I /tmp/go-build803923973/os/user/_obj/ -g -O2 -I . /tmp/cgo-gcc-input-601284788.c -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers

clang called with: -w -Wno-error -o/tmp/go-build803923973/crypto/x509/_obj//_cgo_.o -gdwarf-2 -c -ferror-limit=0 -Wno-unknown-warning-option -Wno-unneeded-internal-declaration -Wno-unused-function -Qunused-arguments -fno-builtin -I /tmp/go-build803923973/crypto/x509/_obj/ -g -mmacosx-version-min=10.6 -D__MAC_OS_X_VERSION_MAX_ALLOWED=1080 -m64 -I . /tmp/cgo-gcc-input-150798707.c
superenv added:    -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers
superenv executed: clang -w -Wno-error -o/tmp/go-build803923973/crypto/x509/_obj//_cgo_.o -gdwarf-2 -c -ferror-limit=0 -Wno-unknown-warning-option -Wno-unneeded-internal-declaration -Wno-unused-function -Qunused-arguments -fno-builtin -I /tmp/go-build803923973/crypto/x509/_obj/ -g -mmacosx-version-min=10.6 -D__MAC_OS_X_VERSION_MAX_ALLOWED=1080 -m64 -I . /tmp/cgo-gcc-input-150798707.c -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers

clang called with: -w -Wno-error -o/tmp/go-build803923973/os/user/_obj//_cgo_.o -gdwarf-2 -c -ferror-limit=0 -Wno-unknown-warning-option -Wno-unneeded-internal-declaration -Wno-unused-function -Qunused-arguments -fno-builtin -I /tmp/go-build803923973/os/user/_obj/ -g -m64 -I . /tmp/cgo-gcc-input-850164867.c
superenv added:    -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers
superenv executed: clang -w -Wno-error -o/tmp/go-build803923973/os/user/_obj//_cgo_.o -gdwarf-2 -c -ferror-limit=0 -Wno-unknown-warning-option -Wno-unneeded-internal-declaration -Wno-unused-function -Qunused-arguments -fno-builtin -I /tmp/go-build803923973/os/user/_obj/ -g -m64 -I . /tmp/cgo-gcc-input-850164867.c -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers

clang called with: -w -Wno-error -o/tmp/go-build803923973/os/user/_obj//_cgo_.o -gdwarf-2 -c -ferror-limit=0 -Wno-unknown-warning-option -Wno-unneeded-internal-declaration -Wno-unused-function -Qunused-arguments -fno-builtin -I /tmp/go-build803923973/os/user/_obj/ -g -O2 -m64 -I . /tmp/cgo-gcc-input-188093958.c
superenv added:    -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers
superenv executed: clang -w -Wno-error -o/tmp/go-build803923973/os/user/_obj//_cgo_.o -gdwarf-2 -c -ferror-limit=0 -Wno-unknown-warning-option -Wno-unneeded-internal-declaration -Wno-unused-function -Qunused-arguments -fno-builtin -I /tmp/go-build803923973/os/user/_obj/ -g -O2 -m64 -I . /tmp/cgo-gcc-input-188093958.c -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers

clang called with: -E -dM -m64 -I /tmp/go-build803923973/os/user/_obj/ -g -O2 -I . /tmp/cgo-gcc-input-921402797.c
superenv added:    -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers
superenv executed: clang -E -dM -m64 -I /tmp/go-build803923973/os/user/_obj/ -g -O2 -I . /tmp/cgo-gcc-input-921402797.c -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers

clang called with: -w -Wno-error -o/tmp/go-build803923973/crypto/x509/_obj//_cgo_.o -gdwarf-2 -c -ferror-limit=0 -Wno-unknown-warning-option -Wno-unneeded-internal-declaration -Wno-unused-function -Qunused-arguments -fno-builtin -I /tmp/go-build803923973/crypto/x509/_obj/ -g -O2 -mmacosx-version-min=10.6 -D__MAC_OS_X_VERSION_MAX_ALLOWED=1080 -m64 -I . /tmp/cgo-gcc-input-126994486.c
superenv added:    -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers
superenv executed: clang -w -Wno-error -o/tmp/go-build803923973/crypto/x509/_obj//_cgo_.o -gdwarf-2 -c -ferror-limit=0 -Wno-unknown-warning-option -Wno-unneeded-internal-declaration -Wno-unused-function -Qunused-arguments -fno-builtin -I /tmp/go-build803923973/crypto/x509/_obj/ -g -O2 -mmacosx-version-min=10.6 -D__MAC_OS_X_VERSION_MAX_ALLOWED=1080 -m64 -I . /tmp/cgo-gcc-input-126994486.c -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers

clang called with: -w -Wno-error -o/tmp/go-build803923973/os/user/_obj//_cgo_.o -gdwarf-2 -c -ferror-limit=0 -Wno-unknown-warning-option -Wno-unneeded-internal-declaration -Wno-unused-function -Qunused-arguments -fno-builtin -I /tmp/go-build803923973/os/user/_obj/ -g -m64 -I . /tmp/cgo-gcc-input-542917416.c
superenv added:    -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers
superenv executed: clang -w -Wno-error -o/tmp/go-build803923973/os/user/_obj//_cgo_.o -gdwarf-2 -c -ferror-limit=0 -Wno-unknown-warning-option -Wno-unneeded-internal-declaration -Wno-unused-function -Qunused-arguments -fno-builtin -I /tmp/go-build803923973/os/user/_obj/ -g -m64 -I . /tmp/cgo-gcc-input-542917416.c -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers

clang called with: -w -Wno-error -o/tmp/go-build803923973/os/user/_obj//_cgo_.o -gdwarf-2 -c -ferror-limit=0 -Wno-unknown-warning-option -Wno-unneeded-internal-declaration -Wno-unused-function -Qunused-arguments -fno-builtin -I /tmp/go-build803923973/os/user/_obj/ -g -O2 -m64 -I . /tmp/cgo-gcc-input-851987559.c
superenv added:    -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers
superenv executed: clang -w -Wno-error -o/tmp/go-build803923973/os/user/_obj//_cgo_.o -gdwarf-2 -c -ferror-limit=0 -Wno-unknown-warning-option -Wno-unneeded-internal-declaration -Wno-unused-function -Qunused-arguments -fno-builtin -I /tmp/go-build803923973/os/user/_obj/ -g -O2 -m64 -I . /tmp/cgo-gcc-input-851987559.c -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers

clang called with: -I /private/tmp/go-20170217-86759-1l6igmj/go/src/os/user -fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build803923973=/tmp/go-build -gno-record-gcc-switches -fno-common -I /tmp/go-build803923973/os/user/_obj/ -g -O2 -o /tmp/go-build803923973/os/user/_obj/_cgo_export.o -c /tmp/go-build803923973/os/user/_obj/_cgo_export.c
superenv added:    -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers
superenv executed: clang -I /private/tmp/go-20170217-86759-1l6igmj/go/src/os/user -fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build803923973=/tmp/go-build -gno-record-gcc-switches -fno-common -I /tmp/go-build803923973/os/user/_obj/ -g -O2 -o /tmp/go-build803923973/os/user/_obj/_cgo_export.o -c /tmp/go-build803923973/os/user/_obj/_cgo_export.c -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers

clang called with: -I /private/tmp/go-20170217-86759-1l6igmj/go/src/os/user -fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build803923973=/tmp/go-build -gno-record-gcc-switches -fno-common -I /tmp/go-build803923973/os/user/_obj/ -g -O2 -o /tmp/go-build803923973/os/user/_obj/getgrouplist_darwin.cgo2.o -c /tmp/go-build803923973/os/user/_obj/getgrouplist_darwin.cgo2.c
superenv added:    -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers
superenv executed: clang -I /private/tmp/go-20170217-86759-1l6igmj/go/src/os/user -fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build803923973=/tmp/go-build -gno-record-gcc-switches -fno-common -I /tmp/go-build803923973/os/user/_obj/ -g -O2 -o /tmp/go-build803923973/os/user/_obj/getgrouplist_darwin.cgo2.o -c /tmp/go-build803923973/os/user/_obj/getgrouplist_darwin.cgo2.c -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers

clang called with: -I /private/tmp/go-20170217-86759-1l6igmj/go/src/crypto/x509 -fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build803923973=/tmp/go-build -gno-record-gcc-switches -fno-common -I /tmp/go-build803923973/crypto/x509/_obj/ -g -O2 -mmacosx-version-min=10.6 -D__MAC_OS_X_VERSION_MAX_ALLOWED=1080 -o /tmp/go-build803923973/crypto/x509/_obj/_cgo_export.o -c /tmp/go-build803923973/crypto/x509/_obj/_cgo_export.c
superenv added:    -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers
superenv executed: clang -I /private/tmp/go-20170217-86759-1l6igmj/go/src/crypto/x509 -fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build803923973=/tmp/go-build -gno-record-gcc-switches -fno-common -I /tmp/go-build803923973/crypto/x509/_obj/ -g -O2 -mmacosx-version-min=10.6 -D__MAC_OS_X_VERSION_MAX_ALLOWED=1080 -o /tmp/go-build803923973/crypto/x509/_obj/_cgo_export.o -c /tmp/go-build803923973/crypto/x509/_obj/_cgo_export.c -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers

clang called with: -I /private/tmp/go-20170217-86759-1l6igmj/go/src/os/user -fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build803923973=/tmp/go-build -gno-record-gcc-switches -fno-common -I /tmp/go-build803923973/os/user/_obj/ -g -O2 -o /tmp/go-build803923973/os/user/_obj/listgroups_unix.cgo2.o -c /tmp/go-build803923973/os/user/_obj/listgroups_unix.cgo2.c
superenv added:    -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers
superenv executed: clang -I /private/tmp/go-20170217-86759-1l6igmj/go/src/os/user -fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build803923973=/tmp/go-build -gno-record-gcc-switches -fno-common -I /tmp/go-build803923973/os/user/_obj/ -g -O2 -o /tmp/go-build803923973/os/user/_obj/listgroups_unix.cgo2.o -c /tmp/go-build803923973/os/user/_obj/listgroups_unix.cgo2.c -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers

clang called with: -I /private/tmp/go-20170217-86759-1l6igmj/go/src/crypto/x509 -fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build803923973=/tmp/go-build -gno-record-gcc-switches -fno-common -I /tmp/go-build803923973/crypto/x509/_obj/ -g -O2 -mmacosx-version-min=10.6 -D__MAC_OS_X_VERSION_MAX_ALLOWED=1080 -o /tmp/go-build803923973/crypto/x509/_obj/root_cgo_darwin.cgo2.o -c /tmp/go-build803923973/crypto/x509/_obj/root_cgo_darwin.cgo2.c
superenv added:    -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers
superenv executed: clang -I /private/tmp/go-20170217-86759-1l6igmj/go/src/crypto/x509 -fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build803923973=/tmp/go-build -gno-record-gcc-switches -fno-common -I /tmp/go-build803923973/crypto/x509/_obj/ -g -O2 -mmacosx-version-min=10.6 -D__MAC_OS_X_VERSION_MAX_ALLOWED=1080 -o /tmp/go-build803923973/crypto/x509/_obj/root_cgo_darwin.cgo2.o -c /tmp/go-build803923973/crypto/x509/_obj/root_cgo_darwin.cgo2.c -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers

clang called with: -I /private/tmp/go-20170217-86759-1l6igmj/go/src/os/user -fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build803923973=/tmp/go-build -gno-record-gcc-switches -fno-common -I /tmp/go-build803923973/os/user/_obj/ -g -O2 -o /tmp/go-build803923973/os/user/_obj/lookup_unix.cgo2.o -c /tmp/go-build803923973/os/user/_obj/lookup_unix.cgo2.c
superenv added:    -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers
superenv executed: clang -I /private/tmp/go-20170217-86759-1l6igmj/go/src/os/user -fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build803923973=/tmp/go-build -gno-record-gcc-switches -fno-common -I /tmp/go-build803923973/os/user/_obj/ -g -O2 -o /tmp/go-build803923973/os/user/_obj/lookup_unix.cgo2.o -c /tmp/go-build803923973/os/user/_obj/lookup_unix.cgo2.c -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers

clang called with: -I /private/tmp/go-20170217-86759-1l6igmj/go/src/os/user -fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build803923973=/tmp/go-build -gno-record-gcc-switches -fno-common -I /tmp/go-build803923973/os/user/_obj/ -g -O2 -o /tmp/go-build803923973/os/user/_obj/_cgo_main.o -c /tmp/go-build803923973/os/user/_obj/_cgo_main.c
superenv added:    -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers
superenv executed: clang -I /private/tmp/go-20170217-86759-1l6igmj/go/src/os/user -fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build803923973=/tmp/go-build -gno-record-gcc-switches -fno-common -I /tmp/go-build803923973/os/user/_obj/ -g -O2 -o /tmp/go-build803923973/os/user/_obj/_cgo_main.o -c /tmp/go-build803923973/os/user/_obj/_cgo_main.c -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers

clang called with: -I /private/tmp/go-20170217-86759-1l6igmj/go/src/crypto/x509 -fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build803923973=/tmp/go-build -gno-record-gcc-switches -fno-common -I /tmp/go-build803923973/crypto/x509/_obj/ -g -O2 -mmacosx-version-min=10.6 -D__MAC_OS_X_VERSION_MAX_ALLOWED=1080 -o /tmp/go-build803923973/crypto/x509/_obj/_cgo_main.o -c /tmp/go-build803923973/crypto/x509/_obj/_cgo_main.c
superenv added:    -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers
superenv executed: clang -I /private/tmp/go-20170217-86759-1l6igmj/go/src/crypto/x509 -fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build803923973=/tmp/go-build -gno-record-gcc-switches -fno-common -I /tmp/go-build803923973/crypto/x509/_obj/ -g -O2 -mmacosx-version-min=10.6 -D__MAC_OS_X_VERSION_MAX_ALLOWED=1080 -o /tmp/go-build803923973/crypto/x509/_obj/_cgo_main.o -c /tmp/go-build803923973/crypto/x509/_obj/_cgo_main.c -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers

clang called with: -I /private/tmp/go-20170217-86759-1l6igmj/go/src/os/user -fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build803923973=/tmp/go-build -gno-record-gcc-switches -fno-common -o /tmp/go-build803923973/os/user/_obj/_cgo_.o /tmp/go-build803923973/os/user/_obj/_cgo_main.o /tmp/go-build803923973/os/user/_obj/_cgo_export.o /tmp/go-build803923973/os/user/_obj/getgrouplist_darwin.cgo2.o /tmp/go-build803923973/os/user/_obj/listgroups_unix.cgo2.o /tmp/go-build803923973/os/user/_obj/lookup_unix.cgo2.o -g -O2
superenv added:    -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers -L/usr/local/lib -L/System/Library/Frameworks/OpenGL.framework/Versions/Current/Libraries -Wl,-headerpad_max_install_names
superenv executed: clang -I /private/tmp/go-20170217-86759-1l6igmj/go/src/os/user -fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build803923973=/tmp/go-build -gno-record-gcc-switches -fno-common -o /tmp/go-build803923973/os/user/_obj/_cgo_.o /tmp/go-build803923973/os/user/_obj/_cgo_main.o /tmp/go-build803923973/os/user/_obj/_cgo_export.o /tmp/go-build803923973/os/user/_obj/getgrouplist_darwin.cgo2.o /tmp/go-build803923973/os/user/_obj/listgroups_unix.cgo2.o /tmp/go-build803923973/os/user/_obj/lookup_unix.cgo2.o -g -O2 -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers -L/usr/local/lib -L/System/Library/Frameworks/OpenGL.framework/Versions/Current/Libraries -Wl,-headerpad_max_install_names

clang called with: -I /private/tmp/go-20170217-86759-1l6igmj/go/src/crypto/x509 -fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build803923973=/tmp/go-build -gno-record-gcc-switches -fno-common -o /tmp/go-build803923973/crypto/x509/_obj/_cgo_.o /tmp/go-build803923973/crypto/x509/_obj/_cgo_main.o /tmp/go-build803923973/crypto/x509/_obj/_cgo_export.o /tmp/go-build803923973/crypto/x509/_obj/root_cgo_darwin.cgo2.o -g -O2 -framework CoreFoundation -framework Security
superenv added:    -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers -L/usr/local/lib -L/System/Library/Frameworks/OpenGL.framework/Versions/Current/Libraries -Wl,-headerpad_max_install_names
superenv executed: clang -I /private/tmp/go-20170217-86759-1l6igmj/go/src/crypto/x509 -fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build803923973=/tmp/go-build -gno-record-gcc-switches -fno-common -o /tmp/go-build803923973/crypto/x509/_obj/_cgo_.o /tmp/go-build803923973/crypto/x509/_obj/_cgo_main.o /tmp/go-build803923973/crypto/x509/_obj/_cgo_export.o /tmp/go-build803923973/crypto/x509/_obj/root_cgo_darwin.cgo2.o -g -O2 -framework CoreFoundation -framework Security -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers -L/usr/local/lib -L/System/Library/Frameworks/OpenGL.framework/Versions/Current/Libraries -Wl,-headerpad_max_install_names

clang called with: -I /private/tmp/go-20170217-86759-1l6igmj/go/src/os/user -fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build803923973=/tmp/go-build -gno-record-gcc-switches -fno-common -o /tmp/go-build803923973/os/user/_obj/_all.o /tmp/go-build803923973/os/user/_obj/_cgo_export.o /tmp/go-build803923973/os/user/_obj/getgrouplist_darwin.cgo2.o /tmp/go-build803923973/os/user/_obj/listgroups_unix.cgo2.o /tmp/go-build803923973/os/user/_obj/lookup_unix.cgo2.o -g -O2 -Wl,-r -nostdlib
superenv added:    -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers -L/usr/local/lib -L/System/Library/Frameworks/OpenGL.framework/Versions/Current/Libraries -Wl,-headerpad_max_install_names
superenv executed: clang -I /private/tmp/go-20170217-86759-1l6igmj/go/src/os/user -fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build803923973=/tmp/go-build -gno-record-gcc-switches -fno-common -o /tmp/go-build803923973/os/user/_obj/_all.o /tmp/go-build803923973/os/user/_obj/_cgo_export.o /tmp/go-build803923973/os/user/_obj/getgrouplist_darwin.cgo2.o /tmp/go-build803923973/os/user/_obj/listgroups_unix.cgo2.o /tmp/go-build803923973/os/user/_obj/lookup_unix.cgo2.o -g -O2 -Wl,-r -nostdlib -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers -L/usr/local/lib -L/System/Library/Frameworks/OpenGL.framework/Versions/Current/Libraries -Wl,-headerpad_max_install_names

clang called with: -I /private/tmp/go-20170217-86759-1l6igmj/go/src/crypto/x509 -fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build803923973=/tmp/go-build -gno-record-gcc-switches -fno-common -o /tmp/go-build803923973/crypto/x509/_obj/_all.o /tmp/go-build803923973/crypto/x509/_obj/_cgo_export.o /tmp/go-build803923973/crypto/x509/_obj/root_cgo_darwin.cgo2.o -g -O2 -Wl,-r -nostdlib
superenv added:    -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers -L/usr/local/lib -L/System/Library/Frameworks/OpenGL.framework/Versions/Current/Libraries -Wl,-headerpad_max_install_names
superenv executed: clang -I /private/tmp/go-20170217-86759-1l6igmj/go/src/crypto/x509 -fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build803923973=/tmp/go-build -gno-record-gcc-switches -fno-common -o /tmp/go-build803923973/crypto/x509/_obj/_all.o /tmp/go-build803923973/crypto/x509/_obj/_cgo_export.o /tmp/go-build803923973/crypto/x509/_obj/root_cgo_darwin.cgo2.o -g -O2 -Wl,-r -nostdlib -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers -L/usr/local/lib -L/System/Library/Frameworks/OpenGL.framework/Versions/Current/Libraries -Wl,-headerpad_max_install_names

clang called with: -E -dM -m64 -I /tmp/go-build803923973/plugin/_obj/ -g -O2 -I . /tmp/cgo-gcc-input-464052658.c
superenv added:    -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers
superenv executed: clang -E -dM -m64 -I /tmp/go-build803923973/plugin/_obj/ -g -O2 -I . /tmp/cgo-gcc-input-464052658.c -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers

clang called with: -w -Wno-error -o/tmp/go-build803923973/plugin/_obj//_cgo_.o -gdwarf-2 -c -ferror-limit=0 -Wno-unknown-warning-option -Wno-unneeded-internal-declaration -Wno-unused-function -Qunused-arguments -fno-builtin -I /tmp/go-build803923973/plugin/_obj/ -g -m64 -I . /tmp/cgo-gcc-input-166079849.c
superenv added:    -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers
superenv executed: clang -w -Wno-error -o/tmp/go-build803923973/plugin/_obj//_cgo_.o -gdwarf-2 -c -ferror-limit=0 -Wno-unknown-warning-option -Wno-unneeded-internal-declaration -Wno-unused-function -Qunused-arguments -fno-builtin -I /tmp/go-build803923973/plugin/_obj/ -g -m64 -I . /tmp/cgo-gcc-input-166079849.c -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers

clang called with: -w -Wno-error -o/tmp/go-build803923973/plugin/_obj//_cgo_.o -gdwarf-2 -c -ferror-limit=0 -Wno-unknown-warning-option -Wno-unneeded-internal-declaration -Wno-unused-function -Qunused-arguments -fno-builtin -I /tmp/go-build803923973/plugin/_obj/ -g -O2 -m64 -I . /tmp/cgo-gcc-input-547589044.c
superenv added:    -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers
superenv executed: clang -w -Wno-error -o/tmp/go-build803923973/plugin/_obj//_cgo_.o -gdwarf-2 -c -ferror-limit=0 -Wno-unknown-warning-option -Wno-unneeded-internal-declaration -Wno-unused-function -Qunused-arguments -fno-builtin -I /tmp/go-build803923973/plugin/_obj/ -g -O2 -m64 -I . /tmp/cgo-gcc-input-547589044.c -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers

clang called with: -I /private/tmp/go-20170217-86759-1l6igmj/go/src/plugin -fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build803923973=/tmp/go-build -gno-record-gcc-switches -fno-common -I /tmp/go-build803923973/plugin/_obj/ -g -O2 -o /tmp/go-build803923973/plugin/_obj/_cgo_export.o -c /tmp/go-build803923973/plugin/_obj/_cgo_export.c
superenv added:    -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers
superenv executed: clang -I /private/tmp/go-20170217-86759-1l6igmj/go/src/plugin -fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build803923973=/tmp/go-build -gno-record-gcc-switches -fno-common -I /tmp/go-build803923973/plugin/_obj/ -g -O2 -o /tmp/go-build803923973/plugin/_obj/_cgo_export.o -c /tmp/go-build803923973/plugin/_obj/_cgo_export.c -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers

clang called with: -I /private/tmp/go-20170217-86759-1l6igmj/go/src/plugin -fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build803923973=/tmp/go-build -gno-record-gcc-switches -fno-common -I /tmp/go-build803923973/plugin/_obj/ -g -O2 -o /tmp/go-build803923973/plugin/_obj/plugin_dlopen.cgo2.o -c /tmp/go-build803923973/plugin/_obj/plugin_dlopen.cgo2.c
superenv added:    -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers
superenv executed: clang -I /private/tmp/go-20170217-86759-1l6igmj/go/src/plugin -fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build803923973=/tmp/go-build -gno-record-gcc-switches -fno-common -I /tmp/go-build803923973/plugin/_obj/ -g -O2 -o /tmp/go-build803923973/plugin/_obj/plugin_dlopen.cgo2.o -c /tmp/go-build803923973/plugin/_obj/plugin_dlopen.cgo2.c -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers

clang called with: -I /private/tmp/go-20170217-86759-1l6igmj/go/src/plugin -fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build803923973=/tmp/go-build -gno-record-gcc-switches -fno-common -I /tmp/go-build803923973/plugin/_obj/ -g -O2 -o /tmp/go-build803923973/plugin/_obj/_cgo_main.o -c /tmp/go-build803923973/plugin/_obj/_cgo_main.c
superenv added:    -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers
superenv executed: clang -I /private/tmp/go-20170217-86759-1l6igmj/go/src/plugin -fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build803923973=/tmp/go-build -gno-record-gcc-switches -fno-common -I /tmp/go-build803923973/plugin/_obj/ -g -O2 -o /tmp/go-build803923973/plugin/_obj/_cgo_main.o -c /tmp/go-build803923973/plugin/_obj/_cgo_main.c -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers

clang called with: -I /private/tmp/go-20170217-86759-1l6igmj/go/src/plugin -fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build803923973=/tmp/go-build -gno-record-gcc-switches -fno-common -o /tmp/go-build803923973/plugin/_obj/_cgo_.o /tmp/go-build803923973/plugin/_obj/_cgo_main.o /tmp/go-build803923973/plugin/_obj/_cgo_export.o /tmp/go-build803923973/plugin/_obj/plugin_dlopen.cgo2.o -g -O2
superenv added:    -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers -L/usr/local/lib -L/System/Library/Frameworks/OpenGL.framework/Versions/Current/Libraries -Wl,-headerpad_max_install_names
superenv executed: clang -I /private/tmp/go-20170217-86759-1l6igmj/go/src/plugin -fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build803923973=/tmp/go-build -gno-record-gcc-switches -fno-common -o /tmp/go-build803923973/plugin/_obj/_cgo_.o /tmp/go-build803923973/plugin/_obj/_cgo_main.o /tmp/go-build803923973/plugin/_obj/_cgo_export.o /tmp/go-build803923973/plugin/_obj/plugin_dlopen.cgo2.o -g -O2 -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers -L/usr/local/lib -L/System/Library/Frameworks/OpenGL.framework/Versions/Current/Libraries -Wl,-headerpad_max_install_names

clang called with: -I /private/tmp/go-20170217-86759-1l6igmj/go/src/plugin -fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build803923973=/tmp/go-build -gno-record-gcc-switches -fno-common -o /tmp/go-build803923973/plugin/_obj/_all.o /tmp/go-build803923973/plugin/_obj/_cgo_export.o /tmp/go-build803923973/plugin/_obj/plugin_dlopen.cgo2.o -g -O2 -Wl,-r -nostdlib
superenv added:    -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers -L/usr/local/lib -L/System/Library/Frameworks/OpenGL.framework/Versions/Current/Libraries -Wl,-headerpad_max_install_names
superenv executed: clang -I /private/tmp/go-20170217-86759-1l6igmj/go/src/plugin -fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build803923973=/tmp/go-build -gno-record-gcc-switches -fno-common -o /tmp/go-build803923973/plugin/_obj/_all.o /tmp/go-build803923973/plugin/_obj/_cgo_export.o /tmp/go-build803923973/plugin/_obj/plugin_dlopen.cgo2.o -g -O2 -Wl,-r -nostdlib -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers -L/usr/local/lib -L/System/Library/Frameworks/OpenGL.framework/Versions/Current/Libraries -Wl,-headerpad_max_install_names

