2017-02-17 20:10:43 -0500

./make.bash
--no-clean

##### Building Go bootstrap tool.
cmd/dist

##### Building Go toolchain using /private/tmp/go-20170217-86759-1l6igmj/go/gobootstrap.
bootstrap/cmd/internal/dwarf
bootstrap/cmd/internal/sys
bootstrap/cmd/asm/internal/flags
bootstrap/cmd/internal/obj
bootstrap/cmd/internal/bio
bootstrap/cmd/compile/internal/syntax
bootstrap/cmd/internal/obj/arm
bootstrap/cmd/internal/obj/arm64
bootstrap/cmd/internal/obj/mips
bootstrap/cmd/internal/obj/ppc64
bootstrap/cmd/internal/obj/s390x
bootstrap/cmd/internal/obj/x86
bootstrap/cmd/asm/internal/lex
bootstrap/cmd/internal/gcprog
bootstrap/math/big
bootstrap/cmd/asm/internal/arch
bootstrap/cmd/compile/internal/ssa
bootstrap/cmd/asm/internal/asm
bootstrap/cmd/asm
bootstrap/debug/pe
bootstrap/cmd/link/internal/ld
bootstrap/cmd/link/internal/amd64
bootstrap/cmd/link/internal/arm
bootstrap/cmd/link/internal/arm64
bootstrap/cmd/link/internal/mips
bootstrap/cmd/link/internal/mips64
bootstrap/cmd/link/internal/ppc64
bootstrap/cmd/link/internal/s390x
bootstrap/cmd/link/internal/x86
bootstrap/cmd/link
bootstrap/cmd/compile/internal/gc
bootstrap/cmd/compile/internal/amd64
bootstrap/cmd/compile/internal/arm
bootstrap/cmd/compile/internal/arm64
bootstrap/cmd/compile/internal/mips
bootstrap/cmd/compile/internal/mips64
bootstrap/cmd/compile/internal/ppc64
bootstrap/cmd/compile/internal/s390x
bootstrap/cmd/compile/internal/x86
bootstrap/cmd/compile

##### Building go_bootstrap for host, darwin/amd64.
runtime/internal/sys
runtime/internal/atomic
runtime
internal/syscall/windows/sysdll
unicode
sync/atomic
internal/race
unicode/utf16
encoding
unicode/utf8
errors
math
sync
syscall
internal/singleflight
io
strings
hash
bytes
hash/adler32
bufio
path
strconv
internal/syscall/windows/registry
internal/syscall/windows
time
crypto
reflect
encoding/base64
crypto/sha1
os
os/signal
encoding/binary
fmt
sort
container/heap
regexp/syntax
path/filepath
debug/dwarf
go/token
text/template/parse
encoding/json
log
compress/flate
context
net/url
flag
io/ioutil
regexp
os/exec
go/scanner
go/ast
debug/macho
compress/zlib
debug/elf
text/template
go/parser
go/doc
go/build
cmd/go

##### Building packages and commands for darwin/amd64.
runtime/internal/sys
runtime/internal/atomic
runtime
errors
internal/race
sync/atomic
unicode
sync
io
unicode/utf8
math
bytes
bufio
syscall
strconv
reflect
time
os
strings
encoding/binary
fmt
cmd/internal/sys
sort
path/filepath
path
hash
cmd/internal/dwarf
flag
log
debug/dwarf
cmd/internal/obj
compress/flate
cmd/internal/goobj
hash/adler32
debug/gosym
debug/macho
compress/zlib
debug/pe
debug/elf
debug/plan9obj
cmd/vendor/golang.org/x/arch/arm/armasm
cmd/vendor/golang.org/x/arch/ppc64/ppc64asm
cmd/vendor/golang.org/x/arch/x86/x86asm
regexp/syntax
text/tabwriter
io/ioutil
archive/tar
regexp
hash/crc32
archive/zip
cmd/internal/objfile
compress/bzip2
cmd/addr2line
compress/gzip
compress/lzw
container/heap
container/list
container/ring
context
crypto
crypto/subtle
crypto/cipher
crypto/internal/cipherhw
crypto/aes
crypto/des
math/rand
math/big
crypto/sha512
crypto/hmac
crypto/md5
crypto/rc4
crypto/sha1
crypto/sha256
encoding/hex
encoding/base64
encoding/pem
vendor/golang_org/x/net/route
crypto/dsa
crypto/elliptic
encoding/asn1
crypto/rand
crypto/ecdsa
crypto/rsa
crypto/x509/pkix
internal/nettrace
internal/singleflight
go/token
os/exec
go/scanner
go/ast
vendor/golang_org/x/crypto/chacha20poly1305/internal/chacha20
vendor/golang_org/x/crypto/poly1305
vendor/golang_org/x/crypto/chacha20poly1305
vendor/golang_org/x/crypto/curve25519
database/sql/driver
go/parser
go/printer
database/sql
cmd/cgo
encoding
encoding/ascii85
encoding/base32
encoding/csv
encoding/gob
unicode/utf16
encoding/json
encoding/xml
runtime/cgo
vendor/golang_org/x/net/http2/hpack
vendor/golang_org/x/net/idna
vendor/golang_org/x/text/transform
vendor/golang_org/x/text/unicode/norm
vendor/golang_org/x/text/width
mime
mime/quotedprintable
net/http/internal
net/url
text/template/parse
text/template
go/doc
go/build
go/constant
go/format
go/types
net
text/scanner
go/internal/gccgoimporter
go/internal/gcimporter
go/importer
hash/crc64
hash/fnv
html
html/template
image/color
image
image/color/palette
image/internal/imageutil
image/draw
image/gif
image/jpeg
image/png
index/suffixarray
internal/pprof/profile
internal/syscall/windows
internal/syscall/windows/registry
internal/syscall/windows/sysdll
runtime/debug
runtime/trace
testing
crypto/x509
vendor/golang_org/x/net/lex/httplex
net/textproto
mime/multipart
internal/testenv
internal/trace
log/syslog
math/cmplx
runtime/pprof/internal/protopprof
runtime/pprof
net/internal/socktest
net/mail
os/signal
os/user
plugin
crypto/tls
runtime/race
testing/internal/testdeps
testing/iotest
net/http/httptrace
net/smtp
net/http
testing/quick
cmd/api
cmd/internal/obj/arm
cmd/internal/obj/arm64
cmd/internal/obj/mips
expvar
net/http/cgi
net/http/cookiejar
net/http/fcgi
net/http/httptest
net/http/httputil
net/http/pprof
net/rpc
cmd/internal/obj/ppc64
net/rpc/jsonrpc
cmd/internal/obj/s390x
cmd/internal/obj/x86
cmd/asm/internal/flags
cmd/asm/internal/lex
cmd/internal/bio
cmd/compile/internal/syntax
cmd/asm/internal/arch
cmd/asm/internal/asm
cmd/asm
cmd/compile/internal/ssa
cmd/internal/gcprog
cmd/compile/internal/test
cmd/internal/browser
cmd/cover
cmd/dist
cmd/doc
cmd/fix
cmd/go
cmd/gofmt
cmd/link/internal/ld
cmd/compile/internal/gc
cmd/link/internal/amd64
cmd/link/internal/arm
cmd/link/internal/arm64
cmd/link/internal/mips
cmd/link/internal/mips64
cmd/link/internal/ppc64
cmd/link/internal/s390x
cmd/link/internal/x86
cmd/link
cmd/nm
cmd/objdump
cmd/pack
cmd/pprof/internal/plugin
cmd/pprof/internal/report
cmd/pprof/internal/svg
cmd/pprof/internal/tempfile
cmd/pprof/internal/commands
cmd/pprof/internal/driver
cmd/pprof/internal/fetch
cmd/pprof/internal/symbolizer
cmd/pprof/internal/symbolz
cmd/pprof
cmd/compile/internal/amd64
cmd/compile/internal/arm
cmd/compile/internal/arm64
cmd/compile/internal/mips
cmd/compile/internal/mips64
cmd/compile/internal/ppc64
cmd/compile/internal/s390x
cmd/compile/internal/x86
cmd/trace
cmd/compile
cmd/vet/internal/cfg
cmd/vet/internal/whitelist
cmd/vet


---
Installed Go for darwin/amd64 in /private/tmp/go-20170217-86759-1l6igmj/go
Installed commands in /private/tmp/go-20170217-86759-1l6igmj/go/bin

The binaries expect /private/tmp/go-20170217-86759-1l6igmj/go to be copied or moved to /usr/local/Cellar/go/1.8/libexec
