clang called with: -fdebug-prefix-map=a=b -c trivial.c
superenv added:    -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers
superenv executed: clang -fdebug-prefix-map=a=b -c trivial.c -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers

clang called with: -gno-record-gcc-switches -c trivial.c
superenv added:    -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers
superenv executed: clang -gno-record-gcc-switches -c trivial.c -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers

clang called with: -E -dM -m64 -I /tmp/go-build118709682/runtime/cgo/_obj/ -g -O2 -Wall -Werror -I . /tmp/cgo-gcc-input-461199012.c
superenv added:    -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers
superenv executed: clang -E -dM -m64 -I /tmp/go-build118709682/runtime/cgo/_obj/ -g -O2 -Wall -Werror -I . /tmp/cgo-gcc-input-461199012.c -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers

clang called with: -fdebug-prefix-map=a=b -c trivial.c
superenv added:    -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers
superenv executed: clang -fdebug-prefix-map=a=b -c trivial.c -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers

clang called with: -gno-record-gcc-switches -c trivial.c
superenv added:    -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers
superenv executed: clang -gno-record-gcc-switches -c trivial.c -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers

clang called with: -I /usr/local/Cellar/go/1.8/libexec/src/runtime/cgo -fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build118709682=/tmp/go-build -gno-record-gcc-switches -fno-common -I /tmp/go-build118709682/runtime/cgo/_obj/ -g -O2 -Wall -Werror -o /tmp/go-build118709682/runtime/cgo/_obj/_cgo_export.o -c /tmp/go-build118709682/runtime/cgo/_obj/_cgo_export.c
superenv added:    -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers
superenv executed: clang -I /usr/local/Cellar/go/1.8/libexec/src/runtime/cgo -fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build118709682=/tmp/go-build -gno-record-gcc-switches -fno-common -I /tmp/go-build118709682/runtime/cgo/_obj/ -g -O2 -Wall -Werror -o /tmp/go-build118709682/runtime/cgo/_obj/_cgo_export.o -c /tmp/go-build118709682/runtime/cgo/_obj/_cgo_export.c -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers

clang called with: -I /usr/local/Cellar/go/1.8/libexec/src/runtime/cgo -fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build118709682=/tmp/go-build -gno-record-gcc-switches -fno-common -I /tmp/go-build118709682/runtime/cgo/_obj/ -g -O2 -Wall -Werror -o /tmp/go-build118709682/runtime/cgo/_obj/cgo.cgo2.o -c /tmp/go-build118709682/runtime/cgo/_obj/cgo.cgo2.c
superenv added:    -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers
superenv executed: clang -I /usr/local/Cellar/go/1.8/libexec/src/runtime/cgo -fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build118709682=/tmp/go-build -gno-record-gcc-switches -fno-common -I /tmp/go-build118709682/runtime/cgo/_obj/ -g -O2 -Wall -Werror -o /tmp/go-build118709682/runtime/cgo/_obj/cgo.cgo2.o -c /tmp/go-build118709682/runtime/cgo/_obj/cgo.cgo2.c -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers

clang called with: -I /usr/local/Cellar/go/1.8/libexec/src/runtime/cgo -fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build118709682=/tmp/go-build -gno-record-gcc-switches -fno-common -I /tmp/go-build118709682/runtime/cgo/_obj/ -g -O2 -Wall -Werror -o /tmp/go-build118709682/runtime/cgo/_obj/gcc_context.o -c /usr/local/Cellar/go/1.8/libexec/src/runtime/cgo/gcc_context.c
superenv added:    -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers
superenv executed: clang -I /usr/local/Cellar/go/1.8/libexec/src/runtime/cgo -fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build118709682=/tmp/go-build -gno-record-gcc-switches -fno-common -I /tmp/go-build118709682/runtime/cgo/_obj/ -g -O2 -Wall -Werror -o /tmp/go-build118709682/runtime/cgo/_obj/gcc_context.o -c /usr/local/Cellar/go/1.8/libexec/src/runtime/cgo/gcc_context.c -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers

clang called with: -I /usr/local/Cellar/go/1.8/libexec/src/runtime/cgo -fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build118709682=/tmp/go-build -gno-record-gcc-switches -fno-common -I /tmp/go-build118709682/runtime/cgo/_obj/ -g -O2 -Wall -Werror -o /tmp/go-build118709682/runtime/cgo/_obj/gcc_darwin_amd64.o -c /usr/local/Cellar/go/1.8/libexec/src/runtime/cgo/gcc_darwin_amd64.c
superenv added:    -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers
superenv executed: clang -I /usr/local/Cellar/go/1.8/libexec/src/runtime/cgo -fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build118709682=/tmp/go-build -gno-record-gcc-switches -fno-common -I /tmp/go-build118709682/runtime/cgo/_obj/ -g -O2 -Wall -Werror -o /tmp/go-build118709682/runtime/cgo/_obj/gcc_darwin_amd64.o -c /usr/local/Cellar/go/1.8/libexec/src/runtime/cgo/gcc_darwin_amd64.c -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers

clang called with: -I /usr/local/Cellar/go/1.8/libexec/src/runtime/cgo -fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build118709682=/tmp/go-build -gno-record-gcc-switches -fno-common -I /tmp/go-build118709682/runtime/cgo/_obj/ -g -O2 -Wall -Werror -o /tmp/go-build118709682/runtime/cgo/_obj/gcc_libinit.o -c /usr/local/Cellar/go/1.8/libexec/src/runtime/cgo/gcc_libinit.c
superenv added:    -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers
superenv executed: clang -I /usr/local/Cellar/go/1.8/libexec/src/runtime/cgo -fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build118709682=/tmp/go-build -gno-record-gcc-switches -fno-common -I /tmp/go-build118709682/runtime/cgo/_obj/ -g -O2 -Wall -Werror -o /tmp/go-build118709682/runtime/cgo/_obj/gcc_libinit.o -c /usr/local/Cellar/go/1.8/libexec/src/runtime/cgo/gcc_libinit.c -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers

clang called with: -I /usr/local/Cellar/go/1.8/libexec/src/runtime/cgo -fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build118709682=/tmp/go-build -gno-record-gcc-switches -fno-common -I /tmp/go-build118709682/runtime/cgo/_obj/ -g -O2 -Wall -Werror -o /tmp/go-build118709682/runtime/cgo/_obj/gcc_setenv.o -c /usr/local/Cellar/go/1.8/libexec/src/runtime/cgo/gcc_setenv.c
superenv added:    -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers
superenv executed: clang -I /usr/local/Cellar/go/1.8/libexec/src/runtime/cgo -fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build118709682=/tmp/go-build -gno-record-gcc-switches -fno-common -I /tmp/go-build118709682/runtime/cgo/_obj/ -g -O2 -Wall -Werror -o /tmp/go-build118709682/runtime/cgo/_obj/gcc_setenv.o -c /usr/local/Cellar/go/1.8/libexec/src/runtime/cgo/gcc_setenv.c -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers

clang called with: -I /usr/local/Cellar/go/1.8/libexec/src/runtime/cgo -fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build118709682=/tmp/go-build -gno-record-gcc-switches -fno-common -I /tmp/go-build118709682/runtime/cgo/_obj/ -g -O2 -Wall -Werror -o /tmp/go-build118709682/runtime/cgo/_obj/gcc_util.o -c /usr/local/Cellar/go/1.8/libexec/src/runtime/cgo/gcc_util.c
superenv added:    -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers
superenv executed: clang -I /usr/local/Cellar/go/1.8/libexec/src/runtime/cgo -fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build118709682=/tmp/go-build -gno-record-gcc-switches -fno-common -I /tmp/go-build118709682/runtime/cgo/_obj/ -g -O2 -Wall -Werror -o /tmp/go-build118709682/runtime/cgo/_obj/gcc_util.o -c /usr/local/Cellar/go/1.8/libexec/src/runtime/cgo/gcc_util.c -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers

clang called with: -I /usr/local/Cellar/go/1.8/libexec/src/runtime/cgo -fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build118709682=/tmp/go-build -gno-record-gcc-switches -fno-common -I /tmp/go-build118709682/runtime/cgo/_obj/ -g -O2 -Wall -Werror -o /tmp/go-build118709682/runtime/cgo/_obj/gcc_amd64.o -c /usr/local/Cellar/go/1.8/libexec/src/runtime/cgo/gcc_amd64.S
superenv added:    -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers
superenv executed: clang -I /usr/local/Cellar/go/1.8/libexec/src/runtime/cgo -fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build118709682=/tmp/go-build -gno-record-gcc-switches -fno-common -I /tmp/go-build118709682/runtime/cgo/_obj/ -g -O2 -Wall -Werror -o /tmp/go-build118709682/runtime/cgo/_obj/gcc_amd64.o -c /usr/local/Cellar/go/1.8/libexec/src/runtime/cgo/gcc_amd64.S -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers

clang called with: -I /usr/local/Cellar/go/1.8/libexec/src/runtime/cgo -fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build118709682=/tmp/go-build -gno-record-gcc-switches -fno-common -I /tmp/go-build118709682/runtime/cgo/_obj/ -g -O2 -Wall -Werror -o /tmp/go-build118709682/runtime/cgo/_obj/_cgo_main.o -c /tmp/go-build118709682/runtime/cgo/_obj/_cgo_main.c
superenv added:    -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers
superenv executed: clang -I /usr/local/Cellar/go/1.8/libexec/src/runtime/cgo -fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build118709682=/tmp/go-build -gno-record-gcc-switches -fno-common -I /tmp/go-build118709682/runtime/cgo/_obj/ -g -O2 -Wall -Werror -o /tmp/go-build118709682/runtime/cgo/_obj/_cgo_main.o -c /tmp/go-build118709682/runtime/cgo/_obj/_cgo_main.c -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers

clang called with: -I /usr/local/Cellar/go/1.8/libexec/src/runtime/cgo -fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build118709682=/tmp/go-build -gno-record-gcc-switches -fno-common -o /tmp/go-build118709682/runtime/cgo/_obj/_cgo_.o /tmp/go-build118709682/runtime/cgo/_obj/_cgo_main.o /tmp/go-build118709682/runtime/cgo/_obj/_cgo_export.o /tmp/go-build118709682/runtime/cgo/_obj/cgo.cgo2.o /tmp/go-build118709682/runtime/cgo/_obj/gcc_context.o /tmp/go-build118709682/runtime/cgo/_obj/gcc_darwin_amd64.o /tmp/go-build118709682/runtime/cgo/_obj/gcc_libinit.o /tmp/go-build118709682/runtime/cgo/_obj/gcc_setenv.o /tmp/go-build118709682/runtime/cgo/_obj/gcc_util.o /tmp/go-build118709682/runtime/cgo/_obj/gcc_amd64.o -g -O2 -lpthread
superenv added:    -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers -L/usr/local/lib -L/System/Library/Frameworks/OpenGL.framework/Versions/Current/Libraries -Wl,-headerpad_max_install_names
superenv executed: clang -I /usr/local/Cellar/go/1.8/libexec/src/runtime/cgo -fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build118709682=/tmp/go-build -gno-record-gcc-switches -fno-common -o /tmp/go-build118709682/runtime/cgo/_obj/_cgo_.o /tmp/go-build118709682/runtime/cgo/_obj/_cgo_main.o /tmp/go-build118709682/runtime/cgo/_obj/_cgo_export.o /tmp/go-build118709682/runtime/cgo/_obj/cgo.cgo2.o /tmp/go-build118709682/runtime/cgo/_obj/gcc_context.o /tmp/go-build118709682/runtime/cgo/_obj/gcc_darwin_amd64.o /tmp/go-build118709682/runtime/cgo/_obj/gcc_libinit.o /tmp/go-build118709682/runtime/cgo/_obj/gcc_setenv.o /tmp/go-build118709682/runtime/cgo/_obj/gcc_util.o /tmp/go-build118709682/runtime/cgo/_obj/gcc_amd64.o -g -O2 -lpthread -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers -L/usr/local/lib -L/System/Library/Frameworks/OpenGL.framework/Versions/Current/Libraries -Wl,-headerpad_max_install_names

clang called with: -no-pie -c trivial.c
superenv added:    -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers
superenv executed: clang -no-pie -c trivial.c -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers

clang called with: -I /usr/local/Cellar/go/1.8/libexec/src/runtime/cgo -fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build118709682=/tmp/go-build -gno-record-gcc-switches -fno-common -o /tmp/go-build118709682/runtime/cgo/_obj/_all.o /tmp/go-build118709682/runtime/cgo/_obj/_cgo_export.o /tmp/go-build118709682/runtime/cgo/_obj/cgo.cgo2.o /tmp/go-build118709682/runtime/cgo/_obj/gcc_context.o /tmp/go-build118709682/runtime/cgo/_obj/gcc_darwin_amd64.o /tmp/go-build118709682/runtime/cgo/_obj/gcc_libinit.o /tmp/go-build118709682/runtime/cgo/_obj/gcc_setenv.o /tmp/go-build118709682/runtime/cgo/_obj/gcc_util.o /tmp/go-build118709682/runtime/cgo/_obj/gcc_amd64.o -g -O2 -Wl,-r -nostdlib
superenv added:    -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers -L/usr/local/lib -L/System/Library/Frameworks/OpenGL.framework/Versions/Current/Libraries -Wl,-headerpad_max_install_names
superenv executed: clang -I /usr/local/Cellar/go/1.8/libexec/src/runtime/cgo -fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build118709682=/tmp/go-build -gno-record-gcc-switches -fno-common -o /tmp/go-build118709682/runtime/cgo/_obj/_all.o /tmp/go-build118709682/runtime/cgo/_obj/_cgo_export.o /tmp/go-build118709682/runtime/cgo/_obj/cgo.cgo2.o /tmp/go-build118709682/runtime/cgo/_obj/gcc_context.o /tmp/go-build118709682/runtime/cgo/_obj/gcc_darwin_amd64.o /tmp/go-build118709682/runtime/cgo/_obj/gcc_libinit.o /tmp/go-build118709682/runtime/cgo/_obj/gcc_setenv.o /tmp/go-build118709682/runtime/cgo/_obj/gcc_util.o /tmp/go-build118709682/runtime/cgo/_obj/gcc_amd64.o -g -O2 -Wl,-r -nostdlib -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers -L/usr/local/lib -L/System/Library/Frameworks/OpenGL.framework/Versions/Current/Libraries -Wl,-headerpad_max_install_names

clang called with: -E -dM -m64 -I /tmp/go-build118709682/runtime/race/_obj/ -g -O2 -I . /tmp/cgo-gcc-input-509007410.c
superenv added:    -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers
superenv executed: clang -E -dM -m64 -I /tmp/go-build118709682/runtime/race/_obj/ -g -O2 -I . /tmp/cgo-gcc-input-509007410.c -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers

clang called with: -I /usr/local/Cellar/go/1.8/libexec/src/runtime/race -fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build118709682=/tmp/go-build -gno-record-gcc-switches -fno-common -I /tmp/go-build118709682/runtime/race/_obj/ -g -O2 -o /tmp/go-build118709682/runtime/race/_obj/_cgo_export.o -c /tmp/go-build118709682/runtime/race/_obj/_cgo_export.c
superenv added:    -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers
superenv executed: clang -I /usr/local/Cellar/go/1.8/libexec/src/runtime/race -fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build118709682=/tmp/go-build -gno-record-gcc-switches -fno-common -I /tmp/go-build118709682/runtime/race/_obj/ -g -O2 -o /tmp/go-build118709682/runtime/race/_obj/_cgo_export.o -c /tmp/go-build118709682/runtime/race/_obj/_cgo_export.c -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers

clang called with: -I /usr/local/Cellar/go/1.8/libexec/src/runtime/race -fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build118709682=/tmp/go-build -gno-record-gcc-switches -fno-common -I /tmp/go-build118709682/runtime/race/_obj/ -g -O2 -o /tmp/go-build118709682/runtime/race/_obj/race.cgo2.o -c /tmp/go-build118709682/runtime/race/_obj/race.cgo2.c
superenv added:    -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers
superenv executed: clang -I /usr/local/Cellar/go/1.8/libexec/src/runtime/race -fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build118709682=/tmp/go-build -gno-record-gcc-switches -fno-common -I /tmp/go-build118709682/runtime/race/_obj/ -g -O2 -o /tmp/go-build118709682/runtime/race/_obj/race.cgo2.o -c /tmp/go-build118709682/runtime/race/_obj/race.cgo2.c -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers

clang called with: -I /usr/local/Cellar/go/1.8/libexec/src/runtime/race -fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build118709682=/tmp/go-build -gno-record-gcc-switches -fno-common -I /tmp/go-build118709682/runtime/race/_obj/ -g -O2 -o /tmp/go-build118709682/runtime/race/_obj/_cgo_main.o -c /tmp/go-build118709682/runtime/race/_obj/_cgo_main.c
superenv added:    -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers
superenv executed: clang -I /usr/local/Cellar/go/1.8/libexec/src/runtime/race -fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build118709682=/tmp/go-build -gno-record-gcc-switches -fno-common -I /tmp/go-build118709682/runtime/race/_obj/ -g -O2 -o /tmp/go-build118709682/runtime/race/_obj/_cgo_main.o -c /tmp/go-build118709682/runtime/race/_obj/_cgo_main.c -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers

clang called with: -I /usr/local/Cellar/go/1.8/libexec/src/runtime/race -fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build118709682=/tmp/go-build -gno-record-gcc-switches -fno-common -o /tmp/go-build118709682/runtime/race/_obj/_cgo_.o /tmp/go-build118709682/runtime/race/_obj/_cgo_main.o /tmp/go-build118709682/runtime/race/_obj/_cgo_export.o /tmp/go-build118709682/runtime/race/_obj/race.cgo2.o race_darwin_amd64.syso -g -O2
superenv added:    -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers -L/usr/local/lib -L/System/Library/Frameworks/OpenGL.framework/Versions/Current/Libraries -Wl,-headerpad_max_install_names
superenv executed: clang -I /usr/local/Cellar/go/1.8/libexec/src/runtime/race -fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build118709682=/tmp/go-build -gno-record-gcc-switches -fno-common -o /tmp/go-build118709682/runtime/race/_obj/_cgo_.o /tmp/go-build118709682/runtime/race/_obj/_cgo_main.o /tmp/go-build118709682/runtime/race/_obj/_cgo_export.o /tmp/go-build118709682/runtime/race/_obj/race.cgo2.o race_darwin_amd64.syso -g -O2 -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers -L/usr/local/lib -L/System/Library/Frameworks/OpenGL.framework/Versions/Current/Libraries -Wl,-headerpad_max_install_names

clang called with: -I /usr/local/Cellar/go/1.8/libexec/src/runtime/race -fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build118709682=/tmp/go-build -gno-record-gcc-switches -fno-common -o /tmp/go-build118709682/runtime/race/_obj/_all.o /tmp/go-build118709682/runtime/race/_obj/_cgo_export.o /tmp/go-build118709682/runtime/race/_obj/race.cgo2.o -g -O2 -Wl,-r -nostdlib
superenv added:    -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers -L/usr/local/lib -L/System/Library/Frameworks/OpenGL.framework/Versions/Current/Libraries -Wl,-headerpad_max_install_names
superenv executed: clang -I /usr/local/Cellar/go/1.8/libexec/src/runtime/race -fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build118709682=/tmp/go-build -gno-record-gcc-switches -fno-common -o /tmp/go-build118709682/runtime/race/_obj/_all.o /tmp/go-build118709682/runtime/race/_obj/_cgo_export.o /tmp/go-build118709682/runtime/race/_obj/race.cgo2.o -g -O2 -Wl,-r -nostdlib -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers -L/usr/local/lib -L/System/Library/Frameworks/OpenGL.framework/Versions/Current/Libraries -Wl,-headerpad_max_install_names

clang called with: -E -dM -m64 -I /tmp/go-build118709682/net/_obj/ -g -O2 -I . /tmp/cgo-gcc-input-232310393.c
superenv added:    -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers
superenv executed: clang -E -dM -m64 -I /tmp/go-build118709682/net/_obj/ -g -O2 -I . /tmp/cgo-gcc-input-232310393.c -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers

clang called with: -w -Wno-error -o/tmp/go-build118709682/net/_obj//_cgo_.o -gdwarf-2 -c -ferror-limit=0 -Wno-unknown-warning-option -Wno-unneeded-internal-declaration -Wno-unused-function -Qunused-arguments -fno-builtin -I /tmp/go-build118709682/net/_obj/ -g -m64 -I . /tmp/cgo-gcc-input-514752388.c
superenv added:    -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers
superenv executed: clang -w -Wno-error -o/tmp/go-build118709682/net/_obj//_cgo_.o -gdwarf-2 -c -ferror-limit=0 -Wno-unknown-warning-option -Wno-unneeded-internal-declaration -Wno-unused-function -Qunused-arguments -fno-builtin -I /tmp/go-build118709682/net/_obj/ -g -m64 -I . /tmp/cgo-gcc-input-514752388.c -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers

clang called with: -w -Wno-error -o/tmp/go-build118709682/net/_obj//_cgo_.o -gdwarf-2 -c -ferror-limit=0 -Wno-unknown-warning-option -Wno-unneeded-internal-declaration -Wno-unused-function -Qunused-arguments -fno-builtin -I /tmp/go-build118709682/net/_obj/ -g -O2 -m64 -I . /tmp/cgo-gcc-input-321758995.c
superenv added:    -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers
superenv executed: clang -w -Wno-error -o/tmp/go-build118709682/net/_obj//_cgo_.o -gdwarf-2 -c -ferror-limit=0 -Wno-unknown-warning-option -Wno-unneeded-internal-declaration -Wno-unused-function -Qunused-arguments -fno-builtin -I /tmp/go-build118709682/net/_obj/ -g -O2 -m64 -I . /tmp/cgo-gcc-input-321758995.c -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers

clang called with: -E -dM -m64 -I /tmp/go-build118709682/net/_obj/ -g -O2 -I . /tmp/cgo-gcc-input-281714518.c
superenv added:    -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers
superenv executed: clang -E -dM -m64 -I /tmp/go-build118709682/net/_obj/ -g -O2 -I . /tmp/cgo-gcc-input-281714518.c -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers

clang called with: -w -Wno-error -o/tmp/go-build118709682/net/_obj//_cgo_.o -gdwarf-2 -c -ferror-limit=0 -Wno-unknown-warning-option -Wno-unneeded-internal-declaration -Wno-unused-function -Qunused-arguments -fno-builtin -I /tmp/go-build118709682/net/_obj/ -g -m64 -I . /tmp/cgo-gcc-input-385636029.c
superenv added:    -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers
superenv executed: clang -w -Wno-error -o/tmp/go-build118709682/net/_obj//_cgo_.o -gdwarf-2 -c -ferror-limit=0 -Wno-unknown-warning-option -Wno-unneeded-internal-declaration -Wno-unused-function -Qunused-arguments -fno-builtin -I /tmp/go-build118709682/net/_obj/ -g -m64 -I . /tmp/cgo-gcc-input-385636029.c -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers

clang called with: -w -Wno-error -o/tmp/go-build118709682/net/_obj//_cgo_.o -gdwarf-2 -c -ferror-limit=0 -Wno-unknown-warning-option -Wno-unneeded-internal-declaration -Wno-unused-function -Qunused-arguments -fno-builtin -I /tmp/go-build118709682/net/_obj/ -g -O2 -m64 -I . /tmp/cgo-gcc-input-782819064.c
superenv added:    -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers
superenv executed: clang -w -Wno-error -o/tmp/go-build118709682/net/_obj//_cgo_.o -gdwarf-2 -c -ferror-limit=0 -Wno-unknown-warning-option -Wno-unneeded-internal-declaration -Wno-unused-function -Qunused-arguments -fno-builtin -I /tmp/go-build118709682/net/_obj/ -g -O2 -m64 -I . /tmp/cgo-gcc-input-782819064.c -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers

clang called with: -E -dM -m64 -I /tmp/go-build118709682/net/_obj/ -g -O2 -I . /tmp/cgo-gcc-input-392779767.c
superenv added:    -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers
superenv executed: clang -E -dM -m64 -I /tmp/go-build118709682/net/_obj/ -g -O2 -I . /tmp/cgo-gcc-input-392779767.c -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers

clang called with: -w -Wno-error -o/tmp/go-build118709682/net/_obj//_cgo_.o -gdwarf-2 -c -ferror-limit=0 -Wno-unknown-warning-option -Wno-unneeded-internal-declaration -Wno-unused-function -Qunused-arguments -fno-builtin -I /tmp/go-build118709682/net/_obj/ -g -O2 -m64 -I . /tmp/cgo-gcc-input-243838186.c
superenv added:    -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers
superenv executed: clang -w -Wno-error -o/tmp/go-build118709682/net/_obj//_cgo_.o -gdwarf-2 -c -ferror-limit=0 -Wno-unknown-warning-option -Wno-unneeded-internal-declaration -Wno-unused-function -Qunused-arguments -fno-builtin -I /tmp/go-build118709682/net/_obj/ -g -O2 -m64 -I . /tmp/cgo-gcc-input-243838186.c -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers

clang called with: -E -dM -m64 -I /tmp/go-build118709682/net/_obj/ -g -O2 -I . /tmp/cgo-gcc-input-109051713.c
superenv added:    -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers
superenv executed: clang -E -dM -m64 -I /tmp/go-build118709682/net/_obj/ -g -O2 -I . /tmp/cgo-gcc-input-109051713.c -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers

clang called with: -w -Wno-error -o/tmp/go-build118709682/net/_obj//_cgo_.o -gdwarf-2 -c -ferror-limit=0 -Wno-unknown-warning-option -Wno-unneeded-internal-declaration -Wno-unused-function -Qunused-arguments -fno-builtin -I /tmp/go-build118709682/net/_obj/ -g -m64 -I . /tmp/cgo-gcc-input-113654700.c
superenv added:    -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers
superenv executed: clang -w -Wno-error -o/tmp/go-build118709682/net/_obj//_cgo_.o -gdwarf-2 -c -ferror-limit=0 -Wno-unknown-warning-option -Wno-unneeded-internal-declaration -Wno-unused-function -Qunused-arguments -fno-builtin -I /tmp/go-build118709682/net/_obj/ -g -m64 -I . /tmp/cgo-gcc-input-113654700.c -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers

clang called with: -w -Wno-error -o/tmp/go-build118709682/net/_obj//_cgo_.o -gdwarf-2 -c -ferror-limit=0 -Wno-unknown-warning-option -Wno-unneeded-internal-declaration -Wno-unused-function -Qunused-arguments -fno-builtin -I /tmp/go-build118709682/net/_obj/ -g -O2 -m64 -I . /tmp/cgo-gcc-input-052968731.c
superenv added:    -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers
superenv executed: clang -w -Wno-error -o/tmp/go-build118709682/net/_obj//_cgo_.o -gdwarf-2 -c -ferror-limit=0 -Wno-unknown-warning-option -Wno-unneeded-internal-declaration -Wno-unused-function -Qunused-arguments -fno-builtin -I /tmp/go-build118709682/net/_obj/ -g -O2 -m64 -I . /tmp/cgo-gcc-input-052968731.c -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers

clang called with: -I /usr/local/Cellar/go/1.8/libexec/src/net -fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build118709682=/tmp/go-build -gno-record-gcc-switches -fno-common -I /tmp/go-build118709682/net/_obj/ -g -O2 -o /tmp/go-build118709682/net/_obj/_cgo_export.o -c /tmp/go-build118709682/net/_obj/_cgo_export.c
superenv added:    -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers
superenv executed: clang -I /usr/local/Cellar/go/1.8/libexec/src/net -fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build118709682=/tmp/go-build -gno-record-gcc-switches -fno-common -I /tmp/go-build118709682/net/_obj/ -g -O2 -o /tmp/go-build118709682/net/_obj/_cgo_export.o -c /tmp/go-build118709682/net/_obj/_cgo_export.c -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers

clang called with: -I /usr/local/Cellar/go/1.8/libexec/src/net -fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build118709682=/tmp/go-build -gno-record-gcc-switches -fno-common -I /tmp/go-build118709682/net/_obj/ -g -O2 -o /tmp/go-build118709682/net/_obj/cgo_bsd.cgo2.o -c /tmp/go-build118709682/net/_obj/cgo_bsd.cgo2.c
superenv added:    -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers
superenv executed: clang -I /usr/local/Cellar/go/1.8/libexec/src/net -fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build118709682=/tmp/go-build -gno-record-gcc-switches -fno-common -I /tmp/go-build118709682/net/_obj/ -g -O2 -o /tmp/go-build118709682/net/_obj/cgo_bsd.cgo2.o -c /tmp/go-build118709682/net/_obj/cgo_bsd.cgo2.c -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers

clang called with: -I /usr/local/Cellar/go/1.8/libexec/src/net -fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build118709682=/tmp/go-build -gno-record-gcc-switches -fno-common -I /tmp/go-build118709682/net/_obj/ -g -O2 -o /tmp/go-build118709682/net/_obj/cgo_resnew.cgo2.o -c /tmp/go-build118709682/net/_obj/cgo_resnew.cgo2.c
superenv added:    -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers
superenv executed: clang -I /usr/local/Cellar/go/1.8/libexec/src/net -fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build118709682=/tmp/go-build -gno-record-gcc-switches -fno-common -I /tmp/go-build118709682/net/_obj/ -g -O2 -o /tmp/go-build118709682/net/_obj/cgo_resnew.cgo2.o -c /tmp/go-build118709682/net/_obj/cgo_resnew.cgo2.c -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers

clang called with: -I /usr/local/Cellar/go/1.8/libexec/src/net -fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build118709682=/tmp/go-build -gno-record-gcc-switches -fno-common -I /tmp/go-build118709682/net/_obj/ -g -O2 -o /tmp/go-build118709682/net/_obj/cgo_sockold.cgo2.o -c /tmp/go-build118709682/net/_obj/cgo_sockold.cgo2.c
superenv added:    -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers
superenv executed: clang -I /usr/local/Cellar/go/1.8/libexec/src/net -fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build118709682=/tmp/go-build -gno-record-gcc-switches -fno-common -I /tmp/go-build118709682/net/_obj/ -g -O2 -o /tmp/go-build118709682/net/_obj/cgo_sockold.cgo2.o -c /tmp/go-build118709682/net/_obj/cgo_sockold.cgo2.c -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers

clang called with: -I /usr/local/Cellar/go/1.8/libexec/src/net -fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build118709682=/tmp/go-build -gno-record-gcc-switches -fno-common -I /tmp/go-build118709682/net/_obj/ -g -O2 -o /tmp/go-build118709682/net/_obj/cgo_unix.cgo2.o -c /tmp/go-build118709682/net/_obj/cgo_unix.cgo2.c
superenv added:    -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers
superenv executed: clang -I /usr/local/Cellar/go/1.8/libexec/src/net -fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build118709682=/tmp/go-build -gno-record-gcc-switches -fno-common -I /tmp/go-build118709682/net/_obj/ -g -O2 -o /tmp/go-build118709682/net/_obj/cgo_unix.cgo2.o -c /tmp/go-build118709682/net/_obj/cgo_unix.cgo2.c -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers

clang called with: -I /usr/local/Cellar/go/1.8/libexec/src/net -fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build118709682=/tmp/go-build -gno-record-gcc-switches -fno-common -I /tmp/go-build118709682/net/_obj/ -g -O2 -o /tmp/go-build118709682/net/_obj/_cgo_main.o -c /tmp/go-build118709682/net/_obj/_cgo_main.c
superenv added:    -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers
superenv executed: clang -I /usr/local/Cellar/go/1.8/libexec/src/net -fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build118709682=/tmp/go-build -gno-record-gcc-switches -fno-common -I /tmp/go-build118709682/net/_obj/ -g -O2 -o /tmp/go-build118709682/net/_obj/_cgo_main.o -c /tmp/go-build118709682/net/_obj/_cgo_main.c -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers

clang called with: -I /usr/local/Cellar/go/1.8/libexec/src/net -fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build118709682=/tmp/go-build -gno-record-gcc-switches -fno-common -o /tmp/go-build118709682/net/_obj/_cgo_.o /tmp/go-build118709682/net/_obj/_cgo_main.o /tmp/go-build118709682/net/_obj/_cgo_export.o /tmp/go-build118709682/net/_obj/cgo_bsd.cgo2.o /tmp/go-build118709682/net/_obj/cgo_resnew.cgo2.o /tmp/go-build118709682/net/_obj/cgo_sockold.cgo2.o /tmp/go-build118709682/net/_obj/cgo_unix.cgo2.o -g -O2
superenv added:    -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers -L/usr/local/lib -L/System/Library/Frameworks/OpenGL.framework/Versions/Current/Libraries -Wl,-headerpad_max_install_names
superenv executed: clang -I /usr/local/Cellar/go/1.8/libexec/src/net -fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build118709682=/tmp/go-build -gno-record-gcc-switches -fno-common -o /tmp/go-build118709682/net/_obj/_cgo_.o /tmp/go-build118709682/net/_obj/_cgo_main.o /tmp/go-build118709682/net/_obj/_cgo_export.o /tmp/go-build118709682/net/_obj/cgo_bsd.cgo2.o /tmp/go-build118709682/net/_obj/cgo_resnew.cgo2.o /tmp/go-build118709682/net/_obj/cgo_sockold.cgo2.o /tmp/go-build118709682/net/_obj/cgo_unix.cgo2.o -g -O2 -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers -L/usr/local/lib -L/System/Library/Frameworks/OpenGL.framework/Versions/Current/Libraries -Wl,-headerpad_max_install_names

clang called with: -I /usr/local/Cellar/go/1.8/libexec/src/net -fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build118709682=/tmp/go-build -gno-record-gcc-switches -fno-common -o /tmp/go-build118709682/net/_obj/_all.o /tmp/go-build118709682/net/_obj/_cgo_export.o /tmp/go-build118709682/net/_obj/cgo_bsd.cgo2.o /tmp/go-build118709682/net/_obj/cgo_resnew.cgo2.o /tmp/go-build118709682/net/_obj/cgo_sockold.cgo2.o /tmp/go-build118709682/net/_obj/cgo_unix.cgo2.o -g -O2 -Wl,-r -nostdlib
superenv added:    -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers -L/usr/local/lib -L/System/Library/Frameworks/OpenGL.framework/Versions/Current/Libraries -Wl,-headerpad_max_install_names
superenv executed: clang -I /usr/local/Cellar/go/1.8/libexec/src/net -fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build118709682=/tmp/go-build -gno-record-gcc-switches -fno-common -o /tmp/go-build118709682/net/_obj/_all.o /tmp/go-build118709682/net/_obj/_cgo_export.o /tmp/go-build118709682/net/_obj/cgo_bsd.cgo2.o /tmp/go-build118709682/net/_obj/cgo_resnew.cgo2.o /tmp/go-build118709682/net/_obj/cgo_sockold.cgo2.o /tmp/go-build118709682/net/_obj/cgo_unix.cgo2.o -g -O2 -Wl,-r -nostdlib -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers -L/usr/local/lib -L/System/Library/Frameworks/OpenGL.framework/Versions/Current/Libraries -Wl,-headerpad_max_install_names

clang called with: -E -dM -m64 -I /tmp/go-build118709682/crypto/x509/_obj/ -g -O2 -mmacosx-version-min=10.6 -D__MAC_OS_X_VERSION_MAX_ALLOWED=1080 -I . /tmp/cgo-gcc-input-276734761.c
superenv added:    -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers
superenv executed: clang -E -dM -m64 -I /tmp/go-build118709682/crypto/x509/_obj/ -g -O2 -mmacosx-version-min=10.6 -D__MAC_OS_X_VERSION_MAX_ALLOWED=1080 -I . /tmp/cgo-gcc-input-276734761.c -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers

clang called with: -w -Wno-error -o/tmp/go-build118709682/crypto/x509/_obj//_cgo_.o -gdwarf-2 -c -ferror-limit=0 -Wno-unknown-warning-option -Wno-unneeded-internal-declaration -Wno-unused-function -Qunused-arguments -fno-builtin -I /tmp/go-build118709682/crypto/x509/_obj/ -g -mmacosx-version-min=10.6 -D__MAC_OS_X_VERSION_MAX_ALLOWED=1080 -m64 -I . /tmp/cgo-gcc-input-202963572.c
superenv added:    -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers
superenv executed: clang -w -Wno-error -o/tmp/go-build118709682/crypto/x509/_obj//_cgo_.o -gdwarf-2 -c -ferror-limit=0 -Wno-unknown-warning-option -Wno-unneeded-internal-declaration -Wno-unused-function -Qunused-arguments -fno-builtin -I /tmp/go-build118709682/crypto/x509/_obj/ -g -mmacosx-version-min=10.6 -D__MAC_OS_X_VERSION_MAX_ALLOWED=1080 -m64 -I . /tmp/cgo-gcc-input-202963572.c -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers

clang called with: -w -Wno-error -o/tmp/go-build118709682/crypto/x509/_obj//_cgo_.o -gdwarf-2 -c -ferror-limit=0 -Wno-unknown-warning-option -Wno-unneeded-internal-declaration -Wno-unused-function -Qunused-arguments -fno-builtin -I /tmp/go-build118709682/crypto/x509/_obj/ -g -O2 -mmacosx-version-min=10.6 -D__MAC_OS_X_VERSION_MAX_ALLOWED=1080 -m64 -I . /tmp/cgo-gcc-input-329585987.c
superenv added:    -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers
superenv executed: clang -w -Wno-error -o/tmp/go-build118709682/crypto/x509/_obj//_cgo_.o -gdwarf-2 -c -ferror-limit=0 -Wno-unknown-warning-option -Wno-unneeded-internal-declaration -Wno-unused-function -Qunused-arguments -fno-builtin -I /tmp/go-build118709682/crypto/x509/_obj/ -g -O2 -mmacosx-version-min=10.6 -D__MAC_OS_X_VERSION_MAX_ALLOWED=1080 -m64 -I . /tmp/cgo-gcc-input-329585987.c -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers

clang called with: -I /usr/local/Cellar/go/1.8/libexec/src/crypto/x509 -fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build118709682=/tmp/go-build -gno-record-gcc-switches -fno-common -I /tmp/go-build118709682/crypto/x509/_obj/ -g -O2 -mmacosx-version-min=10.6 -D__MAC_OS_X_VERSION_MAX_ALLOWED=1080 -o /tmp/go-build118709682/crypto/x509/_obj/_cgo_export.o -c /tmp/go-build118709682/crypto/x509/_obj/_cgo_export.c
superenv added:    -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers
superenv executed: clang -I /usr/local/Cellar/go/1.8/libexec/src/crypto/x509 -fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build118709682=/tmp/go-build -gno-record-gcc-switches -fno-common -I /tmp/go-build118709682/crypto/x509/_obj/ -g -O2 -mmacosx-version-min=10.6 -D__MAC_OS_X_VERSION_MAX_ALLOWED=1080 -o /tmp/go-build118709682/crypto/x509/_obj/_cgo_export.o -c /tmp/go-build118709682/crypto/x509/_obj/_cgo_export.c -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers

clang called with: -I /usr/local/Cellar/go/1.8/libexec/src/crypto/x509 -fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build118709682=/tmp/go-build -gno-record-gcc-switches -fno-common -I /tmp/go-build118709682/crypto/x509/_obj/ -g -O2 -mmacosx-version-min=10.6 -D__MAC_OS_X_VERSION_MAX_ALLOWED=1080 -o /tmp/go-build118709682/crypto/x509/_obj/root_cgo_darwin.cgo2.o -c /tmp/go-build118709682/crypto/x509/_obj/root_cgo_darwin.cgo2.c
superenv added:    -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers
superenv executed: clang -I /usr/local/Cellar/go/1.8/libexec/src/crypto/x509 -fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build118709682=/tmp/go-build -gno-record-gcc-switches -fno-common -I /tmp/go-build118709682/crypto/x509/_obj/ -g -O2 -mmacosx-version-min=10.6 -D__MAC_OS_X_VERSION_MAX_ALLOWED=1080 -o /tmp/go-build118709682/crypto/x509/_obj/root_cgo_darwin.cgo2.o -c /tmp/go-build118709682/crypto/x509/_obj/root_cgo_darwin.cgo2.c -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers

clang called with: -I /usr/local/Cellar/go/1.8/libexec/src/crypto/x509 -fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build118709682=/tmp/go-build -gno-record-gcc-switches -fno-common -I /tmp/go-build118709682/crypto/x509/_obj/ -g -O2 -mmacosx-version-min=10.6 -D__MAC_OS_X_VERSION_MAX_ALLOWED=1080 -o /tmp/go-build118709682/crypto/x509/_obj/_cgo_main.o -c /tmp/go-build118709682/crypto/x509/_obj/_cgo_main.c
superenv added:    -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers
superenv executed: clang -I /usr/local/Cellar/go/1.8/libexec/src/crypto/x509 -fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build118709682=/tmp/go-build -gno-record-gcc-switches -fno-common -I /tmp/go-build118709682/crypto/x509/_obj/ -g -O2 -mmacosx-version-min=10.6 -D__MAC_OS_X_VERSION_MAX_ALLOWED=1080 -o /tmp/go-build118709682/crypto/x509/_obj/_cgo_main.o -c /tmp/go-build118709682/crypto/x509/_obj/_cgo_main.c -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers

clang called with: -I /usr/local/Cellar/go/1.8/libexec/src/crypto/x509 -fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build118709682=/tmp/go-build -gno-record-gcc-switches -fno-common -o /tmp/go-build118709682/crypto/x509/_obj/_cgo_.o /tmp/go-build118709682/crypto/x509/_obj/_cgo_main.o /tmp/go-build118709682/crypto/x509/_obj/_cgo_export.o /tmp/go-build118709682/crypto/x509/_obj/root_cgo_darwin.cgo2.o -g -O2 -framework CoreFoundation -framework Security
superenv added:    -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers -L/usr/local/lib -L/System/Library/Frameworks/OpenGL.framework/Versions/Current/Libraries -Wl,-headerpad_max_install_names
superenv executed: clang -I /usr/local/Cellar/go/1.8/libexec/src/crypto/x509 -fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build118709682=/tmp/go-build -gno-record-gcc-switches -fno-common -o /tmp/go-build118709682/crypto/x509/_obj/_cgo_.o /tmp/go-build118709682/crypto/x509/_obj/_cgo_main.o /tmp/go-build118709682/crypto/x509/_obj/_cgo_export.o /tmp/go-build118709682/crypto/x509/_obj/root_cgo_darwin.cgo2.o -g -O2 -framework CoreFoundation -framework Security -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers -L/usr/local/lib -L/System/Library/Frameworks/OpenGL.framework/Versions/Current/Libraries -Wl,-headerpad_max_install_names

clang called with: -I /usr/local/Cellar/go/1.8/libexec/src/crypto/x509 -fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build118709682=/tmp/go-build -gno-record-gcc-switches -fno-common -o /tmp/go-build118709682/crypto/x509/_obj/_all.o /tmp/go-build118709682/crypto/x509/_obj/_cgo_export.o /tmp/go-build118709682/crypto/x509/_obj/root_cgo_darwin.cgo2.o -g -O2 -Wl,-r -nostdlib
superenv added:    -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers -L/usr/local/lib -L/System/Library/Frameworks/OpenGL.framework/Versions/Current/Libraries -Wl,-headerpad_max_install_names
superenv executed: clang -I /usr/local/Cellar/go/1.8/libexec/src/crypto/x509 -fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build118709682=/tmp/go-build -gno-record-gcc-switches -fno-common -o /tmp/go-build118709682/crypto/x509/_obj/_all.o /tmp/go-build118709682/crypto/x509/_obj/_cgo_export.o /tmp/go-build118709682/crypto/x509/_obj/root_cgo_darwin.cgo2.o -g -O2 -Wl,-r -nostdlib -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers -L/usr/local/lib -L/System/Library/Frameworks/OpenGL.framework/Versions/Current/Libraries -Wl,-headerpad_max_install_names

clang called with: -E -dM -m64 -I /tmp/go-build118709682/os/user/_obj/ -g -O2 -I . /tmp/cgo-gcc-input-775500594.c
superenv added:    -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers
superenv executed: clang -E -dM -m64 -I /tmp/go-build118709682/os/user/_obj/ -g -O2 -I . /tmp/cgo-gcc-input-775500594.c -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers

clang called with: -E -dM -m64 -I /tmp/go-build118709682/plugin/_obj/ -g -O2 -I . /tmp/cgo-gcc-input-653883318.c
superenv added:    -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers
superenv executed: clang -E -dM -m64 -I /tmp/go-build118709682/plugin/_obj/ -g -O2 -I . /tmp/cgo-gcc-input-653883318.c -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers

clang called with: -w -Wno-error -o/tmp/go-build118709682/plugin/_obj//_cgo_.o -gdwarf-2 -c -ferror-limit=0 -Wno-unknown-warning-option -Wno-unneeded-internal-declaration -Wno-unused-function -Qunused-arguments -fno-builtin -I /tmp/go-build118709682/plugin/_obj/ -g -m64 -I . /tmp/cgo-gcc-input-135950237.c
superenv added:    -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers
superenv executed: clang -w -Wno-error -o/tmp/go-build118709682/plugin/_obj//_cgo_.o -gdwarf-2 -c -ferror-limit=0 -Wno-unknown-warning-option -Wno-unneeded-internal-declaration -Wno-unused-function -Qunused-arguments -fno-builtin -I /tmp/go-build118709682/plugin/_obj/ -g -m64 -I . /tmp/cgo-gcc-input-135950237.c -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers

clang called with: -w -Wno-error -o/tmp/go-build118709682/os/user/_obj//_cgo_.o -gdwarf-2 -c -ferror-limit=0 -Wno-unknown-warning-option -Wno-unneeded-internal-declaration -Wno-unused-function -Qunused-arguments -fno-builtin -I /tmp/go-build118709682/os/user/_obj/ -g -m64 -I . /tmp/cgo-gcc-input-604221161.c
superenv added:    -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers
superenv executed: clang -w -Wno-error -o/tmp/go-build118709682/os/user/_obj//_cgo_.o -gdwarf-2 -c -ferror-limit=0 -Wno-unknown-warning-option -Wno-unneeded-internal-declaration -Wno-unused-function -Qunused-arguments -fno-builtin -I /tmp/go-build118709682/os/user/_obj/ -g -m64 -I . /tmp/cgo-gcc-input-604221161.c -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers

clang called with: -w -Wno-error -o/tmp/go-build118709682/os/user/_obj//_cgo_.o -gdwarf-2 -c -ferror-limit=0 -Wno-unknown-warning-option -Wno-unneeded-internal-declaration -Wno-unused-function -Qunused-arguments -fno-builtin -I /tmp/go-build118709682/os/user/_obj/ -g -O2 -m64 -I . /tmp/cgo-gcc-input-174648628.c
superenv added:    -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers
superenv executed: clang -w -Wno-error -o/tmp/go-build118709682/os/user/_obj//_cgo_.o -gdwarf-2 -c -ferror-limit=0 -Wno-unknown-warning-option -Wno-unneeded-internal-declaration -Wno-unused-function -Qunused-arguments -fno-builtin -I /tmp/go-build118709682/os/user/_obj/ -g -O2 -m64 -I . /tmp/cgo-gcc-input-174648628.c -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers

clang called with: -w -Wno-error -o/tmp/go-build118709682/plugin/_obj//_cgo_.o -gdwarf-2 -c -ferror-limit=0 -Wno-unknown-warning-option -Wno-unneeded-internal-declaration -Wno-unused-function -Qunused-arguments -fno-builtin -I /tmp/go-build118709682/plugin/_obj/ -g -O2 -m64 -I . /tmp/cgo-gcc-input-553789528.c
superenv added:    -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers
superenv executed: clang -w -Wno-error -o/tmp/go-build118709682/plugin/_obj//_cgo_.o -gdwarf-2 -c -ferror-limit=0 -Wno-unknown-warning-option -Wno-unneeded-internal-declaration -Wno-unused-function -Qunused-arguments -fno-builtin -I /tmp/go-build118709682/plugin/_obj/ -g -O2 -m64 -I . /tmp/cgo-gcc-input-553789528.c -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers

clang called with: -I /usr/local/Cellar/go/1.8/libexec/src/plugin -fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build118709682=/tmp/go-build -gno-record-gcc-switches -fno-common -I /tmp/go-build118709682/plugin/_obj/ -g -O2 -o /tmp/go-build118709682/plugin/_obj/_cgo_export.o -c /tmp/go-build118709682/plugin/_obj/_cgo_export.c
superenv added:    -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers
superenv executed: clang -I /usr/local/Cellar/go/1.8/libexec/src/plugin -fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build118709682=/tmp/go-build -gno-record-gcc-switches -fno-common -I /tmp/go-build118709682/plugin/_obj/ -g -O2 -o /tmp/go-build118709682/plugin/_obj/_cgo_export.o -c /tmp/go-build118709682/plugin/_obj/_cgo_export.c -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers

clang called with: -E -dM -m64 -I /tmp/go-build118709682/os/user/_obj/ -g -O2 -I . /tmp/cgo-gcc-input-159996163.c
superenv added:    -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers
superenv executed: clang -E -dM -m64 -I /tmp/go-build118709682/os/user/_obj/ -g -O2 -I . /tmp/cgo-gcc-input-159996163.c -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers

clang called with: -w -Wno-error -o/tmp/go-build118709682/os/user/_obj//_cgo_.o -gdwarf-2 -c -ferror-limit=0 -Wno-unknown-warning-option -Wno-unneeded-internal-declaration -Wno-unused-function -Qunused-arguments -fno-builtin -I /tmp/go-build118709682/os/user/_obj/ -g -m64 -I . /tmp/cgo-gcc-input-798533254.c
superenv added:    -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers
superenv executed: clang -w -Wno-error -o/tmp/go-build118709682/os/user/_obj//_cgo_.o -gdwarf-2 -c -ferror-limit=0 -Wno-unknown-warning-option -Wno-unneeded-internal-declaration -Wno-unused-function -Qunused-arguments -fno-builtin -I /tmp/go-build118709682/os/user/_obj/ -g -m64 -I . /tmp/cgo-gcc-input-798533254.c -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers

clang called with: -I /usr/local/Cellar/go/1.8/libexec/src/plugin -fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build118709682=/tmp/go-build -gno-record-gcc-switches -fno-common -I /tmp/go-build118709682/plugin/_obj/ -g -O2 -o /tmp/go-build118709682/plugin/_obj/plugin_dlopen.cgo2.o -c /tmp/go-build118709682/plugin/_obj/plugin_dlopen.cgo2.c
superenv added:    -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers
superenv executed: clang -I /usr/local/Cellar/go/1.8/libexec/src/plugin -fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build118709682=/tmp/go-build -gno-record-gcc-switches -fno-common -I /tmp/go-build118709682/plugin/_obj/ -g -O2 -o /tmp/go-build118709682/plugin/_obj/plugin_dlopen.cgo2.o -c /tmp/go-build118709682/plugin/_obj/plugin_dlopen.cgo2.c -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers

clang called with: -w -Wno-error -o/tmp/go-build118709682/os/user/_obj//_cgo_.o -gdwarf-2 -c -ferror-limit=0 -Wno-unknown-warning-option -Wno-unneeded-internal-declaration -Wno-unused-function -Qunused-arguments -fno-builtin -I /tmp/go-build118709682/os/user/_obj/ -g -O2 -m64 -I . /tmp/cgo-gcc-input-704056877.c
superenv added:    -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers
superenv executed: clang -w -Wno-error -o/tmp/go-build118709682/os/user/_obj//_cgo_.o -gdwarf-2 -c -ferror-limit=0 -Wno-unknown-warning-option -Wno-unneeded-internal-declaration -Wno-unused-function -Qunused-arguments -fno-builtin -I /tmp/go-build118709682/os/user/_obj/ -g -O2 -m64 -I . /tmp/cgo-gcc-input-704056877.c -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers

clang called with: -I /usr/local/Cellar/go/1.8/libexec/src/plugin -fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build118709682=/tmp/go-build -gno-record-gcc-switches -fno-common -I /tmp/go-build118709682/plugin/_obj/ -g -O2 -o /tmp/go-build118709682/plugin/_obj/_cgo_main.o -c /tmp/go-build118709682/plugin/_obj/_cgo_main.c
superenv added:    -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers
superenv executed: clang -I /usr/local/Cellar/go/1.8/libexec/src/plugin -fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build118709682=/tmp/go-build -gno-record-gcc-switches -fno-common -I /tmp/go-build118709682/plugin/_obj/ -g -O2 -o /tmp/go-build118709682/plugin/_obj/_cgo_main.o -c /tmp/go-build118709682/plugin/_obj/_cgo_main.c -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers

clang called with: -I /usr/local/Cellar/go/1.8/libexec/src/plugin -fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build118709682=/tmp/go-build -gno-record-gcc-switches -fno-common -o /tmp/go-build118709682/plugin/_obj/_cgo_.o /tmp/go-build118709682/plugin/_obj/_cgo_main.o /tmp/go-build118709682/plugin/_obj/_cgo_export.o /tmp/go-build118709682/plugin/_obj/plugin_dlopen.cgo2.o -g -O2
superenv added:    -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers -L/usr/local/lib -L/System/Library/Frameworks/OpenGL.framework/Versions/Current/Libraries -Wl,-headerpad_max_install_names
superenv executed: clang -I /usr/local/Cellar/go/1.8/libexec/src/plugin -fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build118709682=/tmp/go-build -gno-record-gcc-switches -fno-common -o /tmp/go-build118709682/plugin/_obj/_cgo_.o /tmp/go-build118709682/plugin/_obj/_cgo_main.o /tmp/go-build118709682/plugin/_obj/_cgo_export.o /tmp/go-build118709682/plugin/_obj/plugin_dlopen.cgo2.o -g -O2 -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers -L/usr/local/lib -L/System/Library/Frameworks/OpenGL.framework/Versions/Current/Libraries -Wl,-headerpad_max_install_names

clang called with: -E -dM -m64 -I /tmp/go-build118709682/os/user/_obj/ -g -O2 -I . /tmp/cgo-gcc-input-805673384.c
superenv added:    -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers
superenv executed: clang -E -dM -m64 -I /tmp/go-build118709682/os/user/_obj/ -g -O2 -I . /tmp/cgo-gcc-input-805673384.c -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers

clang called with: -w -Wno-error -o/tmp/go-build118709682/os/user/_obj//_cgo_.o -gdwarf-2 -c -ferror-limit=0 -Wno-unknown-warning-option -Wno-unneeded-internal-declaration -Wno-unused-function -Qunused-arguments -fno-builtin -I /tmp/go-build118709682/os/user/_obj/ -g -m64 -I . /tmp/cgo-gcc-input-914903783.c
superenv added:    -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers
superenv executed: clang -w -Wno-error -o/tmp/go-build118709682/os/user/_obj//_cgo_.o -gdwarf-2 -c -ferror-limit=0 -Wno-unknown-warning-option -Wno-unneeded-internal-declaration -Wno-unused-function -Qunused-arguments -fno-builtin -I /tmp/go-build118709682/os/user/_obj/ -g -m64 -I . /tmp/cgo-gcc-input-914903783.c -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers

clang called with: -I /usr/local/Cellar/go/1.8/libexec/src/plugin -fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build118709682=/tmp/go-build -gno-record-gcc-switches -fno-common -o /tmp/go-build118709682/plugin/_obj/_all.o /tmp/go-build118709682/plugin/_obj/_cgo_export.o /tmp/go-build118709682/plugin/_obj/plugin_dlopen.cgo2.o -g -O2 -Wl,-r -nostdlib
superenv added:    -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers -L/usr/local/lib -L/System/Library/Frameworks/OpenGL.framework/Versions/Current/Libraries -Wl,-headerpad_max_install_names
superenv executed: clang -I /usr/local/Cellar/go/1.8/libexec/src/plugin -fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build118709682=/tmp/go-build -gno-record-gcc-switches -fno-common -o /tmp/go-build118709682/plugin/_obj/_all.o /tmp/go-build118709682/plugin/_obj/_cgo_export.o /tmp/go-build118709682/plugin/_obj/plugin_dlopen.cgo2.o -g -O2 -Wl,-r -nostdlib -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers -L/usr/local/lib -L/System/Library/Frameworks/OpenGL.framework/Versions/Current/Libraries -Wl,-headerpad_max_install_names

clang called with: -w -Wno-error -o/tmp/go-build118709682/os/user/_obj//_cgo_.o -gdwarf-2 -c -ferror-limit=0 -Wno-unknown-warning-option -Wno-unneeded-internal-declaration -Wno-unused-function -Qunused-arguments -fno-builtin -I /tmp/go-build118709682/os/user/_obj/ -g -O2 -m64 -I . /tmp/cgo-gcc-input-002792218.c
superenv added:    -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers
superenv executed: clang -w -Wno-error -o/tmp/go-build118709682/os/user/_obj//_cgo_.o -gdwarf-2 -c -ferror-limit=0 -Wno-unknown-warning-option -Wno-unneeded-internal-declaration -Wno-unused-function -Qunused-arguments -fno-builtin -I /tmp/go-build118709682/os/user/_obj/ -g -O2 -m64 -I . /tmp/cgo-gcc-input-002792218.c -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers

clang called with: -I /usr/local/Cellar/go/1.8/libexec/src/os/user -fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build118709682=/tmp/go-build -gno-record-gcc-switches -fno-common -I /tmp/go-build118709682/os/user/_obj/ -g -O2 -o /tmp/go-build118709682/os/user/_obj/_cgo_export.o -c /tmp/go-build118709682/os/user/_obj/_cgo_export.c
superenv added:    -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers
superenv executed: clang -I /usr/local/Cellar/go/1.8/libexec/src/os/user -fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build118709682=/tmp/go-build -gno-record-gcc-switches -fno-common -I /tmp/go-build118709682/os/user/_obj/ -g -O2 -o /tmp/go-build118709682/os/user/_obj/_cgo_export.o -c /tmp/go-build118709682/os/user/_obj/_cgo_export.c -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers

clang called with: -I /usr/local/Cellar/go/1.8/libexec/src/os/user -fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build118709682=/tmp/go-build -gno-record-gcc-switches -fno-common -I /tmp/go-build118709682/os/user/_obj/ -g -O2 -o /tmp/go-build118709682/os/user/_obj/getgrouplist_darwin.cgo2.o -c /tmp/go-build118709682/os/user/_obj/getgrouplist_darwin.cgo2.c
superenv added:    -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers
superenv executed: clang -I /usr/local/Cellar/go/1.8/libexec/src/os/user -fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build118709682=/tmp/go-build -gno-record-gcc-switches -fno-common -I /tmp/go-build118709682/os/user/_obj/ -g -O2 -o /tmp/go-build118709682/os/user/_obj/getgrouplist_darwin.cgo2.o -c /tmp/go-build118709682/os/user/_obj/getgrouplist_darwin.cgo2.c -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers

clang called with: -I /usr/local/Cellar/go/1.8/libexec/src/os/user -fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build118709682=/tmp/go-build -gno-record-gcc-switches -fno-common -I /tmp/go-build118709682/os/user/_obj/ -g -O2 -o /tmp/go-build118709682/os/user/_obj/listgroups_unix.cgo2.o -c /tmp/go-build118709682/os/user/_obj/listgroups_unix.cgo2.c
superenv added:    -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers
superenv executed: clang -I /usr/local/Cellar/go/1.8/libexec/src/os/user -fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build118709682=/tmp/go-build -gno-record-gcc-switches -fno-common -I /tmp/go-build118709682/os/user/_obj/ -g -O2 -o /tmp/go-build118709682/os/user/_obj/listgroups_unix.cgo2.o -c /tmp/go-build118709682/os/user/_obj/listgroups_unix.cgo2.c -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers

clang called with: -I /usr/local/Cellar/go/1.8/libexec/src/os/user -fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build118709682=/tmp/go-build -gno-record-gcc-switches -fno-common -I /tmp/go-build118709682/os/user/_obj/ -g -O2 -o /tmp/go-build118709682/os/user/_obj/lookup_unix.cgo2.o -c /tmp/go-build118709682/os/user/_obj/lookup_unix.cgo2.c
superenv added:    -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers
superenv executed: clang -I /usr/local/Cellar/go/1.8/libexec/src/os/user -fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build118709682=/tmp/go-build -gno-record-gcc-switches -fno-common -I /tmp/go-build118709682/os/user/_obj/ -g -O2 -o /tmp/go-build118709682/os/user/_obj/lookup_unix.cgo2.o -c /tmp/go-build118709682/os/user/_obj/lookup_unix.cgo2.c -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers

clang called with: -I /usr/local/Cellar/go/1.8/libexec/src/os/user -fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build118709682=/tmp/go-build -gno-record-gcc-switches -fno-common -I /tmp/go-build118709682/os/user/_obj/ -g -O2 -o /tmp/go-build118709682/os/user/_obj/_cgo_main.o -c /tmp/go-build118709682/os/user/_obj/_cgo_main.c
superenv added:    -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers
superenv executed: clang -I /usr/local/Cellar/go/1.8/libexec/src/os/user -fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build118709682=/tmp/go-build -gno-record-gcc-switches -fno-common -I /tmp/go-build118709682/os/user/_obj/ -g -O2 -o /tmp/go-build118709682/os/user/_obj/_cgo_main.o -c /tmp/go-build118709682/os/user/_obj/_cgo_main.c -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers

clang called with: -I /usr/local/Cellar/go/1.8/libexec/src/os/user -fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build118709682=/tmp/go-build -gno-record-gcc-switches -fno-common -o /tmp/go-build118709682/os/user/_obj/_cgo_.o /tmp/go-build118709682/os/user/_obj/_cgo_main.o /tmp/go-build118709682/os/user/_obj/_cgo_export.o /tmp/go-build118709682/os/user/_obj/getgrouplist_darwin.cgo2.o /tmp/go-build118709682/os/user/_obj/listgroups_unix.cgo2.o /tmp/go-build118709682/os/user/_obj/lookup_unix.cgo2.o -g -O2
superenv added:    -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers -L/usr/local/lib -L/System/Library/Frameworks/OpenGL.framework/Versions/Current/Libraries -Wl,-headerpad_max_install_names
superenv executed: clang -I /usr/local/Cellar/go/1.8/libexec/src/os/user -fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build118709682=/tmp/go-build -gno-record-gcc-switches -fno-common -o /tmp/go-build118709682/os/user/_obj/_cgo_.o /tmp/go-build118709682/os/user/_obj/_cgo_main.o /tmp/go-build118709682/os/user/_obj/_cgo_export.o /tmp/go-build118709682/os/user/_obj/getgrouplist_darwin.cgo2.o /tmp/go-build118709682/os/user/_obj/listgroups_unix.cgo2.o /tmp/go-build118709682/os/user/_obj/lookup_unix.cgo2.o -g -O2 -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers -L/usr/local/lib -L/System/Library/Frameworks/OpenGL.framework/Versions/Current/Libraries -Wl,-headerpad_max_install_names

clang called with: -I /usr/local/Cellar/go/1.8/libexec/src/os/user -fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build118709682=/tmp/go-build -gno-record-gcc-switches -fno-common -o /tmp/go-build118709682/os/user/_obj/_all.o /tmp/go-build118709682/os/user/_obj/_cgo_export.o /tmp/go-build118709682/os/user/_obj/getgrouplist_darwin.cgo2.o /tmp/go-build118709682/os/user/_obj/listgroups_unix.cgo2.o /tmp/go-build118709682/os/user/_obj/lookup_unix.cgo2.o -g -O2 -Wl,-r -nostdlib
superenv added:    -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers -L/usr/local/lib -L/System/Library/Frameworks/OpenGL.framework/Versions/Current/Libraries -Wl,-headerpad_max_install_names
superenv executed: clang -I /usr/local/Cellar/go/1.8/libexec/src/os/user -fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build118709682=/tmp/go-build -gno-record-gcc-switches -fno-common -o /tmp/go-build118709682/os/user/_obj/_all.o /tmp/go-build118709682/os/user/_obj/_cgo_export.o /tmp/go-build118709682/os/user/_obj/getgrouplist_darwin.cgo2.o /tmp/go-build118709682/os/user/_obj/listgroups_unix.cgo2.o /tmp/go-build118709682/os/user/_obj/lookup_unix.cgo2.o -g -O2 -Wl,-r -nostdlib -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers -L/usr/local/lib -L/System/Library/Frameworks/OpenGL.framework/Versions/Current/Libraries -Wl,-headerpad_max_install_names

