clang called with: -I. -I/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/include/python2.7 -I/usr/local/opt/openssl/include -I/usr/local/opt/libevent/include -g -O2 -flto -D_THREAD_SAFE -pthread -c daemon/remote.c -fno-common -DPIC -o .libs/remote.o
superenv removed:  -g -O2
superenv added:    -pipe -w -Os -march=core2 -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers
superenv executed: clang -pipe -w -Os -march=core2 -I. -I/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/include/python2.7 -I/usr/local/opt/openssl/include -I/usr/local/opt/libevent/include -flto -D_THREAD_SAFE -pthread -c daemon/remote.c -fno-common -DPIC -o .libs/remote.o -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers -I/usr/local/opt/openssl/include

clang called with: -I. -I/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/include/python2.7 -I/usr/local/opt/openssl/include -I/usr/local/opt/libevent/include -g -O2 -flto -D_THREAD_SAFE -pthread -c daemon/cachedump.c -fno-common -DPIC -o .libs/cachedump.o
superenv removed:  -g -O2
superenv added:    -pipe -w -Os -march=core2 -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers
superenv executed: clang -pipe -w -Os -march=core2 -I. -I/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/include/python2.7 -I/usr/local/opt/openssl/include -I/usr/local/opt/libevent/include -flto -D_THREAD_SAFE -pthread -c daemon/cachedump.c -fno-common -DPIC -o .libs/cachedump.o -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers -I/usr/local/opt/openssl/include

clang called with: -I. -I/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/include/python2.7 -I/usr/local/opt/openssl/include -I/usr/local/opt/libevent/include -g -O2 -flto -D_THREAD_SAFE -pthread -c daemon/cachedump.c -o cachedump.o
superenv removed:  -g -O2
superenv added:    -pipe -w -Os -march=core2 -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers
superenv executed: clang -pipe -w -Os -march=core2 -I. -I/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/include/python2.7 -I/usr/local/opt/openssl/include -I/usr/local/opt/libevent/include -flto -D_THREAD_SAFE -pthread -c daemon/cachedump.c -o cachedump.o -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers -I/usr/local/opt/openssl/include

clang called with: -I. -I/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/include/python2.7 -I/usr/local/opt/openssl/include -I/usr/local/opt/libevent/include -g -O2 -flto -D_THREAD_SAFE -pthread -c daemon/remote.c -o remote.o
superenv removed:  -g -O2
superenv added:    -pipe -w -Os -march=core2 -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers
superenv executed: clang -pipe -w -Os -march=core2 -I. -I/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/include/python2.7 -I/usr/local/opt/openssl/include -I/usr/local/opt/libevent/include -flto -D_THREAD_SAFE -pthread -c daemon/remote.c -o remote.o -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers -I/usr/local/opt/openssl/include

clang called with: -I. -I/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/include/python2.7 -I/usr/local/opt/openssl/include -I/usr/local/opt/libevent/include -g -O2 -flto -D_THREAD_SAFE -pthread -c daemon/unbound.c -fno-common -DPIC -o .libs/unbound.o
superenv removed:  -g -O2
superenv added:    -pipe -w -Os -march=core2 -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers
superenv executed: clang -pipe -w -Os -march=core2 -I. -I/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/include/python2.7 -I/usr/local/opt/openssl/include -I/usr/local/opt/libevent/include -flto -D_THREAD_SAFE -pthread -c daemon/unbound.c -fno-common -DPIC -o .libs/unbound.o -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers -I/usr/local/opt/openssl/include

clang called with: -I. -I/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/include/python2.7 -I/usr/local/opt/openssl/include -I/usr/local/opt/libevent/include -g -O2 -flto -D_THREAD_SAFE -pthread -c daemon/unbound.c -o unbound.o
superenv removed:  -g -O2
superenv added:    -pipe -w -Os -march=core2 -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers
superenv executed: clang -pipe -w -Os -march=core2 -I. -I/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/include/python2.7 -I/usr/local/opt/openssl/include -I/usr/local/opt/libevent/include -flto -D_THREAD_SAFE -pthread -c daemon/unbound.c -o unbound.o -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers -I/usr/local/opt/openssl/include

clang called with: -I. -I/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/include/python2.7 -I/usr/local/opt/openssl/include -I/usr/local/opt/libevent/include -g -O2 -flto -D_THREAD_SAFE -pthread -c libunbound/context.c -fno-common -DPIC -o .libs/context.o
superenv removed:  -g -O2
superenv added:    -pipe -w -Os -march=core2 -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers
superenv executed: clang -pipe -w -Os -march=core2 -I. -I/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/include/python2.7 -I/usr/local/opt/openssl/include -I/usr/local/opt/libevent/include -flto -D_THREAD_SAFE -pthread -c libunbound/context.c -fno-common -DPIC -o .libs/context.o -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers -I/usr/local/opt/openssl/include

clang called with: -I. -I/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/include/python2.7 -I/usr/local/opt/openssl/include -I/usr/local/opt/libevent/include -g -O2 -flto -D_THREAD_SAFE -pthread -c libunbound/context.c -o context.o
superenv removed:  -g -O2
superenv added:    -pipe -w -Os -march=core2 -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers
superenv executed: clang -pipe -w -Os -march=core2 -I. -I/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/include/python2.7 -I/usr/local/opt/openssl/include -I/usr/local/opt/libevent/include -flto -D_THREAD_SAFE -pthread -c libunbound/context.c -o context.o -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers -I/usr/local/opt/openssl/include

clang called with: -I. -I/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/include/python2.7 -I/usr/local/opt/openssl/include -I/usr/local/opt/libevent/include -g -O2 -flto -D_THREAD_SAFE -pthread -c libunbound/libunbound.c -fno-common -DPIC -o .libs/libunbound.o
superenv removed:  -g -O2
superenv added:    -pipe -w -Os -march=core2 -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers
superenv executed: clang -pipe -w -Os -march=core2 -I. -I/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/include/python2.7 -I/usr/local/opt/openssl/include -I/usr/local/opt/libevent/include -flto -D_THREAD_SAFE -pthread -c libunbound/libunbound.c -fno-common -DPIC -o .libs/libunbound.o -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers -I/usr/local/opt/openssl/include

clang called with: -I. -I/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/include/python2.7 -I/usr/local/opt/openssl/include -I/usr/local/opt/libevent/include -g -O2 -flto -D_THREAD_SAFE -pthread -c libunbound/libworker.c -fno-common -DPIC -o .libs/libworker.o
superenv removed:  -g -O2
superenv added:    -pipe -w -Os -march=core2 -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers
superenv executed: clang -pipe -w -Os -march=core2 -I. -I/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/include/python2.7 -I/usr/local/opt/openssl/include -I/usr/local/opt/libevent/include -flto -D_THREAD_SAFE -pthread -c libunbound/libworker.c -fno-common -DPIC -o .libs/libworker.o -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers -I/usr/local/opt/openssl/include

clang called with: -I. -I/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/include/python2.7 -I/usr/local/opt/openssl/include -I/usr/local/opt/libevent/include -g -O2 -flto -D_THREAD_SAFE -pthread -c libunbound/libunbound.c -o libunbound.o
superenv removed:  -g -O2
superenv added:    -pipe -w -Os -march=core2 -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers
superenv executed: clang -pipe -w -Os -march=core2 -I. -I/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/include/python2.7 -I/usr/local/opt/openssl/include -I/usr/local/opt/libevent/include -flto -D_THREAD_SAFE -pthread -c libunbound/libunbound.c -o libunbound.o -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers -I/usr/local/opt/openssl/include

clang called with: -I. -I/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/include/python2.7 -I/usr/local/opt/openssl/include -I/usr/local/opt/libevent/include -g -O2 -flto -D_THREAD_SAFE -pthread -c libunbound/libworker.c -o libworker.o
superenv removed:  -g -O2
superenv added:    -pipe -w -Os -march=core2 -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers
superenv executed: clang -pipe -w -Os -march=core2 -I. -I/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/include/python2.7 -I/usr/local/opt/openssl/include -I/usr/local/opt/libevent/include -flto -D_THREAD_SAFE -pthread -c libunbound/libworker.c -o libworker.o -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers -I/usr/local/opt/openssl/include

clang called with: -I. -I/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/include/python2.7 -I/usr/local/opt/openssl/include -I/usr/local/opt/libevent/include -g -O2 -flto -D_THREAD_SAFE -pthread -c util/ub_event_pluggable.c -fno-common -DPIC -o .libs/ub_event_pluggable.o
superenv removed:  -g -O2
superenv added:    -pipe -w -Os -march=core2 -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers
superenv executed: clang -pipe -w -Os -march=core2 -I. -I/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/include/python2.7 -I/usr/local/opt/openssl/include -I/usr/local/opt/libevent/include -flto -D_THREAD_SAFE -pthread -c util/ub_event_pluggable.c -fno-common -DPIC -o .libs/ub_event_pluggable.o -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers -I/usr/local/opt/openssl/include

clang called with: -I. -I/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/include/python2.7 -I/usr/local/opt/openssl/include -I/usr/local/opt/libevent/include -g -O2 -flto -D_THREAD_SAFE -pthread -c util/ub_event_pluggable.c -o ub_event_pluggable.o
superenv removed:  -g -O2
superenv added:    -pipe -w -Os -march=core2 -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers
superenv executed: clang -pipe -w -Os -march=core2 -I. -I/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/include/python2.7 -I/usr/local/opt/openssl/include -I/usr/local/opt/libevent/include -flto -D_THREAD_SAFE -pthread -c util/ub_event_pluggable.c -o ub_event_pluggable.o -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers -I/usr/local/opt/openssl/include

clang called with: -I. -I/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/include/python2.7 -I/usr/local/opt/openssl/include -I/usr/local/opt/libevent/include -g -O2 -flto -D_THREAD_SAFE -pthread -c smallapp/unbound-checkconf.c -fno-common -DPIC -o .libs/unbound-checkconf.o
superenv removed:  -g -O2
superenv added:    -pipe -w -Os -march=core2 -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers
superenv executed: clang -pipe -w -Os -march=core2 -I. -I/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/include/python2.7 -I/usr/local/opt/openssl/include -I/usr/local/opt/libevent/include -flto -D_THREAD_SAFE -pthread -c smallapp/unbound-checkconf.c -fno-common -DPIC -o .libs/unbound-checkconf.o -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers -I/usr/local/opt/openssl/include

clang called with: -I. -I/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/include/python2.7 -I/usr/local/opt/openssl/include -I/usr/local/opt/libevent/include -g -O2 -flto -D_THREAD_SAFE -pthread -c smallapp/unbound-host.c -fno-common -DPIC -o .libs/unbound-host.o
superenv removed:  -g -O2
superenv added:    -pipe -w -Os -march=core2 -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers
superenv executed: clang -pipe -w -Os -march=core2 -I. -I/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/include/python2.7 -I/usr/local/opt/openssl/include -I/usr/local/opt/libevent/include -flto -D_THREAD_SAFE -pthread -c smallapp/unbound-host.c -fno-common -DPIC -o .libs/unbound-host.o -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers -I/usr/local/opt/openssl/include

clang called with: -I. -I/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/include/python2.7 -I/usr/local/opt/openssl/include -I/usr/local/opt/libevent/include -g -O2 -flto -D_THREAD_SAFE -pthread -c smallapp/unbound-checkconf.c -o unbound-checkconf.o
superenv removed:  -g -O2
superenv added:    -pipe -w -Os -march=core2 -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers
superenv executed: clang -pipe -w -Os -march=core2 -I. -I/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/include/python2.7 -I/usr/local/opt/openssl/include -I/usr/local/opt/libevent/include -flto -D_THREAD_SAFE -pthread -c smallapp/unbound-checkconf.c -o unbound-checkconf.o -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers -I/usr/local/opt/openssl/include

clang called with: -I. -I/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/include/python2.7 -I/usr/local/opt/openssl/include -I/usr/local/opt/libevent/include -g -O2 -flto -D_THREAD_SAFE -pthread -c smallapp/unbound-host.c -o unbound-host.o
superenv removed:  -g -O2
superenv added:    -pipe -w -Os -march=core2 -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers
superenv executed: clang -pipe -w -Os -march=core2 -I. -I/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/include/python2.7 -I/usr/local/opt/openssl/include -I/usr/local/opt/libevent/include -flto -D_THREAD_SAFE -pthread -c smallapp/unbound-host.c -o unbound-host.o -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers -I/usr/local/opt/openssl/include

clang called with: -I. -I/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/include/python2.7 -I/usr/local/opt/openssl/include -I/usr/local/opt/libevent/include -g -O2 -flto -D_THREAD_SAFE -pthread -c smallapp/unbound-control.c -fno-common -DPIC -o .libs/unbound-control.o
superenv removed:  -g -O2
superenv added:    -pipe -w -Os -march=core2 -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers
superenv executed: clang -pipe -w -Os -march=core2 -I. -I/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/include/python2.7 -I/usr/local/opt/openssl/include -I/usr/local/opt/libevent/include -flto -D_THREAD_SAFE -pthread -c smallapp/unbound-control.c -fno-common -DPIC -o .libs/unbound-control.o -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers -I/usr/local/opt/openssl/include

clang called with: -I. -I/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/include/python2.7 -I/usr/local/opt/openssl/include -I/usr/local/opt/libevent/include -g -O2 -flto -D_THREAD_SAFE -pthread -c smallapp/unbound-anchor.c -fno-common -DPIC -o .libs/unbound-anchor.o
superenv removed:  -g -O2
superenv added:    -pipe -w -Os -march=core2 -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers
superenv executed: clang -pipe -w -Os -march=core2 -I. -I/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/include/python2.7 -I/usr/local/opt/openssl/include -I/usr/local/opt/libevent/include -flto -D_THREAD_SAFE -pthread -c smallapp/unbound-anchor.c -fno-common -DPIC -o .libs/unbound-anchor.o -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers -I/usr/local/opt/openssl/include

clang called with: -I. -I/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/include/python2.7 -I/usr/local/opt/openssl/include -I/usr/local/opt/libevent/include -g -O2 -flto -D_THREAD_SAFE -pthread -c smallapp/unbound-control.c -o unbound-control.o
superenv removed:  -g -O2
superenv added:    -pipe -w -Os -march=core2 -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers
superenv executed: clang -pipe -w -Os -march=core2 -I. -I/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/include/python2.7 -I/usr/local/opt/openssl/include -I/usr/local/opt/libevent/include -flto -D_THREAD_SAFE -pthread -c smallapp/unbound-control.c -o unbound-control.o -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers -I/usr/local/opt/openssl/include

clang called with: -I. -I/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/include/python2.7 -I/usr/local/opt/openssl/include -I/usr/local/opt/libevent/include -g -O2 -flto -D_THREAD_SAFE -pthread -c smallapp/unbound-anchor.c -o unbound-anchor.o
superenv removed:  -g -O2
superenv added:    -pipe -w -Os -march=core2 -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers
superenv executed: clang -pipe -w -Os -march=core2 -I. -I/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/include/python2.7 -I/usr/local/opt/openssl/include -I/usr/local/opt/libevent/include -flto -D_THREAD_SAFE -pthread -c smallapp/unbound-anchor.c -o unbound-anchor.o -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers -I/usr/local/opt/openssl/include

clang called with: -dynamiclib -o .libs/libunbound.2.dylib .libs/context.o .libs/libunbound.o .libs/libworker.o .libs/ub_event_pluggable.o .libs/dns.o .libs/infra.o .libs/rrset.o .libs/dname.o .libs/msgencode.o .libs/as112.o .libs/msgparse.o .libs/msgreply.o .libs/packed_rrset.o .libs/iterator.o .libs/iter_delegpt.o .libs/iter_donotq.o .libs/iter_fwd.o .libs/iter_hints.o .libs/iter_priv.o .libs/iter_resptype.o .libs/iter_scrub.o .libs/iter_utils.o .libs/localzone.o .libs/mesh.o .libs/modstack.o .libs/view.o .libs/outbound_list.o .libs/alloc.o .libs/config_file.o .libs/configlexer.o .libs/configparser.o .libs/fptr_wlist.o .libs/locks.o .libs/log.o .libs/mini_event.o .libs/module.o .libs/net_help.o .libs/random.o .libs/rbtree.o .libs/regional.o .libs/rtt.o .libs/dnstree.o .libs/lookup3.o .libs/lruhash.o .libs/slabhash.o .libs/timehist.o .libs/tube.o .libs/winsock_event.o .libs/autotrust.o .libs/val_anchor.o .libs/validator.o .libs/val_kcache.o .libs/val_kentry.o .libs/val_neg.o .libs/val_nsec3.o .libs/val_nsec.o .libs/val_secalgo.o .libs/val_sigcrypt.o .libs/val_utils.o .libs/dns64.o .libs/cachedb.o .libs/pythonmod.o .libs/pythonmod_utils.o .libs/netevent.o .libs/listen_dnsport.o .libs/outside_network.o .libs/keyraw.o .libs/sbuffer.o .libs/wire2str.o .libs/parse.o .libs/parseutil.o .libs/rrdef.o .libs/str2wire.o .libs/strptime.o .libs/reallocarray.o -L/usr/local/opt/python/Frameworks/Python.framework/Versions/2.7/lib/python2.7/config -lpython2.7 -ldl -framework CoreFoundation -L/usr/local/opt/openssl/lib -L/usr/local/opt/libevent/lib -lssl -levent -L/usr/local/opt/python/Frameworks/Python.framework/Versions/2.7/lib -L/usr/local/opt/python/Frameworks/Python.framework/Versions/2.7/lib/python2.7 -lcrypto -g -O2 -flto -framework CoreFoundation -install_name /usr/local/Cellar/unbound/1.6.0_1/lib/libunbound.2.dylib -compatibility_version 7 -current_version 7.3 -Wl,-single_module -Wl,-exported_symbols_list,.libs/libunbound-symbols.expsym
superenv removed:  -g -O2
superenv added:    -pipe -w -Os -march=core2 -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers -I/usr/local/opt/openssl/include -L/usr/local/lib -L/System/Library/Frameworks/OpenGL.framework/Versions/Current/Libraries -Wl,-headerpad_max_install_names
superenv executed: clang -pipe -w -Os -march=core2 -dynamiclib -o .libs/libunbound.2.dylib .libs/context.o .libs/libunbound.o .libs/libworker.o .libs/ub_event_pluggable.o .libs/dns.o .libs/infra.o .libs/rrset.o .libs/dname.o .libs/msgencode.o .libs/as112.o .libs/msgparse.o .libs/msgreply.o .libs/packed_rrset.o .libs/iterator.o .libs/iter_delegpt.o .libs/iter_donotq.o .libs/iter_fwd.o .libs/iter_hints.o .libs/iter_priv.o .libs/iter_resptype.o .libs/iter_scrub.o .libs/iter_utils.o .libs/localzone.o .libs/mesh.o .libs/modstack.o .libs/view.o .libs/outbound_list.o .libs/alloc.o .libs/config_file.o .libs/configlexer.o .libs/configparser.o .libs/fptr_wlist.o .libs/locks.o .libs/log.o .libs/mini_event.o .libs/module.o .libs/net_help.o .libs/random.o .libs/rbtree.o .libs/regional.o .libs/rtt.o .libs/dnstree.o .libs/lookup3.o .libs/lruhash.o .libs/slabhash.o .libs/timehist.o .libs/tube.o .libs/winsock_event.o .libs/autotrust.o .libs/val_anchor.o .libs/validator.o .libs/val_kcache.o .libs/val_kentry.o .libs/val_neg.o .libs/val_nsec3.o .libs/val_nsec.o .libs/val_secalgo.o .libs/val_sigcrypt.o .libs/val_utils.o .libs/dns64.o .libs/cachedb.o .libs/pythonmod.o .libs/pythonmod_utils.o .libs/netevent.o .libs/listen_dnsport.o .libs/outside_network.o .libs/keyraw.o .libs/sbuffer.o .libs/wire2str.o .libs/parse.o .libs/parseutil.o .libs/rrdef.o .libs/str2wire.o .libs/strptime.o .libs/reallocarray.o -L/usr/local/opt/python/Frameworks/Python.framework/Versions/2.7/lib/python2.7/config -lpython2.7 -ldl -framework CoreFoundation -L/usr/local/opt/openssl/lib -L/usr/local/opt/libevent/lib -lssl -levent -L/usr/local/opt/python/Frameworks/Python.framework/Versions/2.7/lib -L/usr/local/opt/python/Frameworks/Python.framework/Versions/2.7/lib/python2.7 -lcrypto -flto -framework CoreFoundation -install_name /usr/local/Cellar/unbound/1.6.0_1/lib/libunbound.2.dylib -compatibility_version 7 -current_version 7.3 -Wl,-single_module -Wl,-exported_symbols_list,.libs/libunbound-symbols.expsym -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers -I/usr/local/opt/openssl/include -L/usr/local/opt/openssl/lib -L/usr/local/lib -L/System/Library/Frameworks/OpenGL.framework/Versions/Current/Libraries -Wl,-headerpad_max_install_names

