clang called with: -E -
superenv added:    -isystem/usr/local/include -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers -I/usr/local/opt/openssl/include -I/usr/local/opt/icu4c/include -I/usr/local/opt/curl/include -I/usr/local/opt/gettext/include -I/usr/local/opt/libxml2/include -I/usr/local/opt/readline/include
superenv executed: clang -E - -isystem/usr/local/include -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers -I/usr/local/opt/openssl/include -I/usr/local/opt/icu4c/include -I/usr/local/opt/curl/include -I/usr/local/opt/gettext/include -I/usr/local/opt/libxml2/include -I/usr/local/opt/readline/include

clang called with: --version
superenv added:    -pipe -Os -march=core2 -isystem/usr/local/include -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers -I/usr/local/opt/openssl/include -I/usr/local/opt/icu4c/include -I/usr/local/opt/curl/include -I/usr/local/opt/gettext/include -I/usr/local/opt/libxml2/include -I/usr/local/opt/readline/include -L/usr/local/opt/openssl/lib -L/usr/local/opt/icu4c/lib -L/usr/local/opt/curl/lib -L/usr/local/opt/gettext/lib -L/usr/local/opt/libffi/lib -L/usr/local/opt/libxml2/lib -L/usr/local/opt/readline/lib -L/usr/local/lib -L/System/Library/Frameworks/OpenGL.framework/Versions/Current/Libraries -Wl,-headerpad_max_install_names
superenv executed: clang -pipe -Os -march=core2 --version -isystem/usr/local/include -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers -I/usr/local/opt/openssl/include -I/usr/local/opt/icu4c/include -I/usr/local/opt/curl/include -I/usr/local/opt/gettext/include -I/usr/local/opt/libxml2/include -I/usr/local/opt/readline/include -L/usr/local/opt/openssl/lib -L/usr/local/opt/icu4c/lib -L/usr/local/opt/curl/lib -L/usr/local/opt/gettext/lib -L/usr/local/opt/libffi/lib -L/usr/local/opt/libxml2/lib -L/usr/local/opt/readline/lib -L/usr/local/lib -L/System/Library/Frameworks/OpenGL.framework/Versions/Current/Libraries -Wl,-headerpad_max_install_names

clang called with: -v
superenv executed: clang -v

clang called with: -V
superenv added:    -pipe -Os -march=core2 -isystem/usr/local/include -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers -I/usr/local/opt/openssl/include -I/usr/local/opt/icu4c/include -I/usr/local/opt/curl/include -I/usr/local/opt/gettext/include -I/usr/local/opt/libxml2/include -I/usr/local/opt/readline/include -L/usr/local/opt/openssl/lib -L/usr/local/opt/icu4c/lib -L/usr/local/opt/curl/lib -L/usr/local/opt/gettext/lib -L/usr/local/opt/libffi/lib -L/usr/local/opt/libxml2/lib -L/usr/local/opt/readline/lib -L/usr/local/lib -L/System/Library/Frameworks/OpenGL.framework/Versions/Current/Libraries -Wl,-headerpad_max_install_names
superenv executed: clang -pipe -Os -march=core2 -V -isystem/usr/local/include -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers -I/usr/local/opt/openssl/include -I/usr/local/opt/icu4c/include -I/usr/local/opt/curl/include -I/usr/local/opt/gettext/include -I/usr/local/opt/libxml2/include -I/usr/local/opt/readline/include -L/usr/local/opt/openssl/lib -L/usr/local/opt/icu4c/lib -L/usr/local/opt/curl/lib -L/usr/local/opt/gettext/lib -L/usr/local/opt/libffi/lib -L/usr/local/opt/libxml2/lib -L/usr/local/opt/readline/lib -L/usr/local/lib -L/System/Library/Frameworks/OpenGL.framework/Versions/Current/Libraries -Wl,-headerpad_max_install_names

clang called with: -qversion
superenv added:    -pipe -Os -march=core2 -isystem/usr/local/include -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers -I/usr/local/opt/openssl/include -I/usr/local/opt/icu4c/include -I/usr/local/opt/curl/include -I/usr/local/opt/gettext/include -I/usr/local/opt/libxml2/include -I/usr/local/opt/readline/include -L/usr/local/opt/openssl/lib -L/usr/local/opt/icu4c/lib -L/usr/local/opt/curl/lib -L/usr/local/opt/gettext/lib -L/usr/local/opt/libffi/lib -L/usr/local/opt/libxml2/lib -L/usr/local/opt/readline/lib -L/usr/local/lib -L/System/Library/Frameworks/OpenGL.framework/Versions/Current/Libraries -Wl,-headerpad_max_install_names
superenv executed: clang -pipe -Os -march=core2 -qversion -isystem/usr/local/include -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers -I/usr/local/opt/openssl/include -I/usr/local/opt/icu4c/include -I/usr/local/opt/curl/include -I/usr/local/opt/gettext/include -I/usr/local/opt/libxml2/include -I/usr/local/opt/readline/include -L/usr/local/opt/openssl/lib -L/usr/local/opt/icu4c/lib -L/usr/local/opt/curl/lib -L/usr/local/opt/gettext/lib -L/usr/local/opt/libffi/lib -L/usr/local/opt/libxml2/lib -L/usr/local/opt/readline/lib -L/usr/local/lib -L/System/Library/Frameworks/OpenGL.framework/Versions/Current/Libraries -Wl,-headerpad_max_install_names

clang called with: conftest.c
superenv added:    -pipe -Os -march=core2 -isystem/usr/local/include -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers -I/usr/local/opt/openssl/include -I/usr/local/opt/icu4c/include -I/usr/local/opt/curl/include -I/usr/local/opt/gettext/include -I/usr/local/opt/libxml2/include -I/usr/local/opt/readline/include -L/usr/local/opt/openssl/lib -L/usr/local/opt/icu4c/lib -L/usr/local/opt/curl/lib -L/usr/local/opt/gettext/lib -L/usr/local/opt/libffi/lib -L/usr/local/opt/libxml2/lib -L/usr/local/opt/readline/lib -L/usr/local/lib -L/System/Library/Frameworks/OpenGL.framework/Versions/Current/Libraries -Wl,-headerpad_max_install_names
superenv executed: clang -pipe -Os -march=core2 conftest.c -isystem/usr/local/include -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers -I/usr/local/opt/openssl/include -I/usr/local/opt/icu4c/include -I/usr/local/opt/curl/include -I/usr/local/opt/gettext/include -I/usr/local/opt/libxml2/include -I/usr/local/opt/readline/include -L/usr/local/opt/openssl/lib -L/usr/local/opt/icu4c/lib -L/usr/local/opt/curl/lib -L/usr/local/opt/gettext/lib -L/usr/local/opt/libffi/lib -L/usr/local/opt/libxml2/lib -L/usr/local/opt/readline/lib -L/usr/local/lib -L/System/Library/Frameworks/OpenGL.framework/Versions/Current/Libraries -Wl,-headerpad_max_install_names

clang called with: -o conftest conftest.c
superenv added:    -pipe -Os -march=core2 -isystem/usr/local/include -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers -I/usr/local/opt/openssl/include -I/usr/local/opt/icu4c/include -I/usr/local/opt/curl/include -I/usr/local/opt/gettext/include -I/usr/local/opt/libxml2/include -I/usr/local/opt/readline/include -L/usr/local/opt/openssl/lib -L/usr/local/opt/icu4c/lib -L/usr/local/opt/curl/lib -L/usr/local/opt/gettext/lib -L/usr/local/opt/libffi/lib -L/usr/local/opt/libxml2/lib -L/usr/local/opt/readline/lib -L/usr/local/lib -L/System/Library/Frameworks/OpenGL.framework/Versions/Current/Libraries -Wl,-headerpad_max_install_names
superenv executed: clang -pipe -Os -march=core2 -o conftest conftest.c -isystem/usr/local/include -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers -I/usr/local/opt/openssl/include -I/usr/local/opt/icu4c/include -I/usr/local/opt/curl/include -I/usr/local/opt/gettext/include -I/usr/local/opt/libxml2/include -I/usr/local/opt/readline/include -L/usr/local/opt/openssl/lib -L/usr/local/opt/icu4c/lib -L/usr/local/opt/curl/lib -L/usr/local/opt/gettext/lib -L/usr/local/opt/libffi/lib -L/usr/local/opt/libxml2/lib -L/usr/local/opt/readline/lib -L/usr/local/lib -L/System/Library/Frameworks/OpenGL.framework/Versions/Current/Libraries -Wl,-headerpad_max_install_names

clang called with: -o conftest conftest.c
superenv added:    -pipe -Os -march=core2 -isystem/usr/local/include -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers -I/usr/local/opt/openssl/include -I/usr/local/opt/icu4c/include -I/usr/local/opt/curl/include -I/usr/local/opt/gettext/include -I/usr/local/opt/libxml2/include -I/usr/local/opt/readline/include -L/usr/local/opt/openssl/lib -L/usr/local/opt/icu4c/lib -L/usr/local/opt/curl/lib -L/usr/local/opt/gettext/lib -L/usr/local/opt/libffi/lib -L/usr/local/opt/libxml2/lib -L/usr/local/opt/readline/lib -L/usr/local/lib -L/System/Library/Frameworks/OpenGL.framework/Versions/Current/Libraries -Wl,-headerpad_max_install_names
superenv executed: clang -pipe -Os -march=core2 -o conftest conftest.c -isystem/usr/local/include -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers -I/usr/local/opt/openssl/include -I/usr/local/opt/icu4c/include -I/usr/local/opt/curl/include -I/usr/local/opt/gettext/include -I/usr/local/opt/libxml2/include -I/usr/local/opt/readline/include -L/usr/local/opt/openssl/lib -L/usr/local/opt/icu4c/lib -L/usr/local/opt/curl/lib -L/usr/local/opt/gettext/lib -L/usr/local/opt/libffi/lib -L/usr/local/opt/libxml2/lib -L/usr/local/opt/readline/lib -L/usr/local/lib -L/System/Library/Frameworks/OpenGL.framework/Versions/Current/Libraries -Wl,-headerpad_max_install_names

clang called with: -c conftest.c
superenv added:    -pipe -Os -march=core2 -isystem/usr/local/include -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers -I/usr/local/opt/openssl/include -I/usr/local/opt/icu4c/include -I/usr/local/opt/curl/include -I/usr/local/opt/gettext/include -I/usr/local/opt/libxml2/include -I/usr/local/opt/readline/include
superenv executed: clang -pipe -Os -march=core2 -c conftest.c -isystem/usr/local/include -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers -I/usr/local/opt/openssl/include -I/usr/local/opt/icu4c/include -I/usr/local/opt/curl/include -I/usr/local/opt/gettext/include -I/usr/local/opt/libxml2/include -I/usr/local/opt/readline/include

clang called with: -c conftest.c
superenv added:    -pipe -Os -march=core2 -isystem/usr/local/include -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers -I/usr/local/opt/openssl/include -I/usr/local/opt/icu4c/include -I/usr/local/opt/curl/include -I/usr/local/opt/gettext/include -I/usr/local/opt/libxml2/include -I/usr/local/opt/readline/include
superenv executed: clang -pipe -Os -march=core2 -c conftest.c -isystem/usr/local/include -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers -I/usr/local/opt/openssl/include -I/usr/local/opt/icu4c/include -I/usr/local/opt/curl/include -I/usr/local/opt/gettext/include -I/usr/local/opt/libxml2/include -I/usr/local/opt/readline/include

clang called with: -c -g conftest.c
superenv added:    -pipe -Os -march=core2 -isystem/usr/local/include -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers -I/usr/local/opt/openssl/include -I/usr/local/opt/icu4c/include -I/usr/local/opt/curl/include -I/usr/local/opt/gettext/include -I/usr/local/opt/libxml2/include -I/usr/local/opt/readline/include
superenv executed: clang -pipe -Os -march=core2 -c -g conftest.c -isystem/usr/local/include -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers -I/usr/local/opt/openssl/include -I/usr/local/opt/icu4c/include -I/usr/local/opt/curl/include -I/usr/local/opt/gettext/include -I/usr/local/opt/libxml2/include -I/usr/local/opt/readline/include

clang called with: -c -g -O2 conftest.c
superenv added:    -pipe -Os -march=core2 -isystem/usr/local/include -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers -I/usr/local/opt/openssl/include -I/usr/local/opt/icu4c/include -I/usr/local/opt/curl/include -I/usr/local/opt/gettext/include -I/usr/local/opt/libxml2/include -I/usr/local/opt/readline/include
superenv executed: clang -pipe -Os -march=core2 -c -g -O2 conftest.c -isystem/usr/local/include -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers -I/usr/local/opt/openssl/include -I/usr/local/opt/icu4c/include -I/usr/local/opt/curl/include -I/usr/local/opt/gettext/include -I/usr/local/opt/libxml2/include -I/usr/local/opt/readline/include

clang called with: -E conftest.c
superenv added:    -isystem/usr/local/include -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers -I/usr/local/opt/openssl/include -I/usr/local/opt/icu4c/include -I/usr/local/opt/curl/include -I/usr/local/opt/gettext/include -I/usr/local/opt/libxml2/include -I/usr/local/opt/readline/include
superenv executed: clang -E conftest.c -isystem/usr/local/include -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers -I/usr/local/opt/openssl/include -I/usr/local/opt/icu4c/include -I/usr/local/opt/curl/include -I/usr/local/opt/gettext/include -I/usr/local/opt/libxml2/include -I/usr/local/opt/readline/include

clang called with: -E conftest.c
superenv added:    -isystem/usr/local/include -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers -I/usr/local/opt/openssl/include -I/usr/local/opt/icu4c/include -I/usr/local/opt/curl/include -I/usr/local/opt/gettext/include -I/usr/local/opt/libxml2/include -I/usr/local/opt/readline/include
superenv executed: clang -E conftest.c -isystem/usr/local/include -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers -I/usr/local/opt/openssl/include -I/usr/local/opt/icu4c/include -I/usr/local/opt/curl/include -I/usr/local/opt/gettext/include -I/usr/local/opt/libxml2/include -I/usr/local/opt/readline/include

clang called with: -E conftest.c
superenv added:    -isystem/usr/local/include -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers -I/usr/local/opt/openssl/include -I/usr/local/opt/icu4c/include -I/usr/local/opt/curl/include -I/usr/local/opt/gettext/include -I/usr/local/opt/libxml2/include -I/usr/local/opt/readline/include
superenv executed: clang -E conftest.c -isystem/usr/local/include -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers -I/usr/local/opt/openssl/include -I/usr/local/opt/icu4c/include -I/usr/local/opt/curl/include -I/usr/local/opt/gettext/include -I/usr/local/opt/libxml2/include -I/usr/local/opt/readline/include

clang called with: -E conftest.c
superenv added:    -isystem/usr/local/include -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers -I/usr/local/opt/openssl/include -I/usr/local/opt/icu4c/include -I/usr/local/opt/curl/include -I/usr/local/opt/gettext/include -I/usr/local/opt/libxml2/include -I/usr/local/opt/readline/include
superenv executed: clang -E conftest.c -isystem/usr/local/include -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers -I/usr/local/opt/openssl/include -I/usr/local/opt/icu4c/include -I/usr/local/opt/curl/include -I/usr/local/opt/gettext/include -I/usr/local/opt/libxml2/include -I/usr/local/opt/readline/include

clang called with: -E conftest.c
superenv added:    -isystem/usr/local/include -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers -I/usr/local/opt/openssl/include -I/usr/local/opt/icu4c/include -I/usr/local/opt/curl/include -I/usr/local/opt/gettext/include -I/usr/local/opt/libxml2/include -I/usr/local/opt/readline/include
superenv executed: clang -E conftest.c -isystem/usr/local/include -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers -I/usr/local/opt/openssl/include -I/usr/local/opt/icu4c/include -I/usr/local/opt/curl/include -I/usr/local/opt/gettext/include -I/usr/local/opt/libxml2/include -I/usr/local/opt/readline/include

clang called with: -E conftest.c
superenv added:    -isystem/usr/local/include -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers -I/usr/local/opt/openssl/include -I/usr/local/opt/icu4c/include -I/usr/local/opt/curl/include -I/usr/local/opt/gettext/include -I/usr/local/opt/libxml2/include -I/usr/local/opt/readline/include
superenv executed: clang -E conftest.c -isystem/usr/local/include -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers -I/usr/local/opt/openssl/include -I/usr/local/opt/icu4c/include -I/usr/local/opt/curl/include -I/usr/local/opt/gettext/include -I/usr/local/opt/libxml2/include -I/usr/local/opt/readline/include

clang called with: -c conftest.c -o conftest2.o
superenv added:    -pipe -Os -march=core2 -isystem/usr/local/include -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers -I/usr/local/opt/openssl/include -I/usr/local/opt/icu4c/include -I/usr/local/opt/curl/include -I/usr/local/opt/gettext/include -I/usr/local/opt/libxml2/include -I/usr/local/opt/readline/include
superenv executed: clang -pipe -Os -march=core2 -c conftest.c -o conftest2.o -isystem/usr/local/include -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers -I/usr/local/opt/openssl/include -I/usr/local/opt/icu4c/include -I/usr/local/opt/curl/include -I/usr/local/opt/gettext/include -I/usr/local/opt/libxml2/include -I/usr/local/opt/readline/include

clang called with: -c conftest.c -o conftest2.o
superenv added:    -pipe -Os -march=core2 -isystem/usr/local/include -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers -I/usr/local/opt/openssl/include -I/usr/local/opt/icu4c/include -I/usr/local/opt/curl/include -I/usr/local/opt/gettext/include -I/usr/local/opt/libxml2/include -I/usr/local/opt/readline/include
superenv executed: clang -pipe -Os -march=core2 -c conftest.c -o conftest2.o -isystem/usr/local/include -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers -I/usr/local/opt/openssl/include -I/usr/local/opt/icu4c/include -I/usr/local/opt/curl/include -I/usr/local/opt/gettext/include -I/usr/local/opt/libxml2/include -I/usr/local/opt/readline/include

cc called with: -c conftest.c
superenv added:    -pipe -Os -march=core2 -isystem/usr/local/include -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers -I/usr/local/opt/openssl/include -I/usr/local/opt/icu4c/include -I/usr/local/opt/curl/include -I/usr/local/opt/gettext/include -I/usr/local/opt/libxml2/include -I/usr/local/opt/readline/include
superenv executed: clang -pipe -Os -march=core2 -c conftest.c -isystem/usr/local/include -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers -I/usr/local/opt/openssl/include -I/usr/local/opt/icu4c/include -I/usr/local/opt/curl/include -I/usr/local/opt/gettext/include -I/usr/local/opt/libxml2/include -I/usr/local/opt/readline/include

cc called with: -c conftest.c -o conftest2.o
superenv added:    -pipe -Os -march=core2 -isystem/usr/local/include -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers -I/usr/local/opt/openssl/include -I/usr/local/opt/icu4c/include -I/usr/local/opt/curl/include -I/usr/local/opt/gettext/include -I/usr/local/opt/libxml2/include -I/usr/local/opt/readline/include
superenv executed: clang -pipe -Os -march=core2 -c conftest.c -o conftest2.o -isystem/usr/local/include -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers -I/usr/local/opt/openssl/include -I/usr/local/opt/icu4c/include -I/usr/local/opt/curl/include -I/usr/local/opt/gettext/include -I/usr/local/opt/libxml2/include -I/usr/local/opt/readline/include

cc called with: -c conftest.c -o conftest2.o
superenv added:    -pipe -Os -march=core2 -isystem/usr/local/include -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers -I/usr/local/opt/openssl/include -I/usr/local/opt/icu4c/include -I/usr/local/opt/curl/include -I/usr/local/opt/gettext/include -I/usr/local/opt/libxml2/include -I/usr/local/opt/readline/include
superenv executed: clang -pipe -Os -march=core2 -c conftest.c -o conftest2.o -isystem/usr/local/include -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers -I/usr/local/opt/openssl/include -I/usr/local/opt/icu4c/include -I/usr/local/opt/curl/include -I/usr/local/opt/gettext/include -I/usr/local/opt/libxml2/include -I/usr/local/opt/readline/include

clang called with: -E conftest.c
superenv added:    -isystem/usr/local/include -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers -I/usr/local/opt/openssl/include -I/usr/local/opt/icu4c/include -I/usr/local/opt/curl/include -I/usr/local/opt/gettext/include -I/usr/local/opt/libxml2/include -I/usr/local/opt/readline/include
superenv executed: clang -E conftest.c -isystem/usr/local/include -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers -I/usr/local/opt/openssl/include -I/usr/local/opt/icu4c/include -I/usr/local/opt/curl/include -I/usr/local/opt/gettext/include -I/usr/local/opt/libxml2/include -I/usr/local/opt/readline/include

clang called with: -E conftest.c
superenv added:    -isystem/usr/local/include -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers -I/usr/local/opt/openssl/include -I/usr/local/opt/icu4c/include -I/usr/local/opt/curl/include -I/usr/local/opt/gettext/include -I/usr/local/opt/libxml2/include -I/usr/local/opt/readline/include
superenv executed: clang -E conftest.c -isystem/usr/local/include -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers -I/usr/local/opt/openssl/include -I/usr/local/opt/icu4c/include -I/usr/local/opt/curl/include -I/usr/local/opt/gettext/include -I/usr/local/opt/libxml2/include -I/usr/local/opt/readline/include

clang called with: -c -g -O2 conftest.c
superenv added:    -pipe -Os -march=core2 -isystem/usr/local/include -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers -I/usr/local/opt/openssl/include -I/usr/local/opt/icu4c/include -I/usr/local/opt/curl/include -I/usr/local/opt/gettext/include -I/usr/local/opt/libxml2/include -I/usr/local/opt/readline/include
superenv executed: clang -pipe -Os -march=core2 -c -g -O2 conftest.c -isystem/usr/local/include -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers -I/usr/local/opt/openssl/include -I/usr/local/opt/icu4c/include -I/usr/local/opt/curl/include -I/usr/local/opt/gettext/include -I/usr/local/opt/libxml2/include -I/usr/local/opt/readline/include

clang called with: -E conftest.c
superenv added:    -isystem/usr/local/include -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers -I/usr/local/opt/openssl/include -I/usr/local/opt/icu4c/include -I/usr/local/opt/curl/include -I/usr/local/opt/gettext/include -I/usr/local/opt/libxml2/include -I/usr/local/opt/readline/include
superenv executed: clang -E conftest.c -isystem/usr/local/include -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers -I/usr/local/opt/openssl/include -I/usr/local/opt/icu4c/include -I/usr/local/opt/curl/include -I/usr/local/opt/gettext/include -I/usr/local/opt/libxml2/include -I/usr/local/opt/readline/include

clang called with: -E conftest.c
superenv added:    -isystem/usr/local/include -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers -I/usr/local/opt/openssl/include -I/usr/local/opt/icu4c/include -I/usr/local/opt/curl/include -I/usr/local/opt/gettext/include -I/usr/local/opt/libxml2/include -I/usr/local/opt/readline/include
superenv executed: clang -E conftest.c -isystem/usr/local/include -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers -I/usr/local/opt/openssl/include -I/usr/local/opt/icu4c/include -I/usr/local/opt/curl/include -I/usr/local/opt/gettext/include -I/usr/local/opt/libxml2/include -I/usr/local/opt/readline/include

clang called with: -o conftest -g -O2 conftest.c
superenv added:    -pipe -Os -march=core2 -isystem/usr/local/include -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers -I/usr/local/opt/openssl/include -I/usr/local/opt/icu4c/include -I/usr/local/opt/curl/include -I/usr/local/opt/gettext/include -I/usr/local/opt/libxml2/include -I/usr/local/opt/readline/include -L/usr/local/opt/openssl/lib -L/usr/local/opt/icu4c/lib -L/usr/local/opt/curl/lib -L/usr/local/opt/gettext/lib -L/usr/local/opt/libffi/lib -L/usr/local/opt/libxml2/lib -L/usr/local/opt/readline/lib -L/usr/local/lib -L/System/Library/Frameworks/OpenGL.framework/Versions/Current/Libraries -Wl,-headerpad_max_install_names
superenv executed: clang -pipe -Os -march=core2 -o conftest -g -O2 conftest.c -isystem/usr/local/include -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers -I/usr/local/opt/openssl/include -I/usr/local/opt/icu4c/include -I/usr/local/opt/curl/include -I/usr/local/opt/gettext/include -I/usr/local/opt/libxml2/include -I/usr/local/opt/readline/include -L/usr/local/opt/openssl/lib -L/usr/local/opt/icu4c/lib -L/usr/local/opt/curl/lib -L/usr/local/opt/gettext/lib -L/usr/local/opt/libffi/lib -L/usr/local/opt/libxml2/lib -L/usr/local/opt/readline/lib -L/usr/local/lib -L/System/Library/Frameworks/OpenGL.framework/Versions/Current/Libraries -Wl,-headerpad_max_install_names

clang called with: -c -g -O2 conftest.c
superenv added:    -pipe -Os -march=core2 -isystem/usr/local/include -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers -I/usr/local/opt/openssl/include -I/usr/local/opt/icu4c/include -I/usr/local/opt/curl/include -I/usr/local/opt/gettext/include -I/usr/local/opt/libxml2/include -I/usr/local/opt/readline/include
superenv executed: clang -pipe -Os -march=core2 -c -g -O2 conftest.c -isystem/usr/local/include -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers -I/usr/local/opt/openssl/include -I/usr/local/opt/icu4c/include -I/usr/local/opt/curl/include -I/usr/local/opt/gettext/include -I/usr/local/opt/libxml2/include -I/usr/local/opt/readline/include

clang called with: -c -g -O2 conftest.c
superenv added:    -pipe -Os -march=core2 -isystem/usr/local/include -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers -I/usr/local/opt/openssl/include -I/usr/local/opt/icu4c/include -I/usr/local/opt/curl/include -I/usr/local/opt/gettext/include -I/usr/local/opt/libxml2/include -I/usr/local/opt/readline/include
superenv executed: clang -pipe -Os -march=core2 -c -g -O2 conftest.c -isystem/usr/local/include -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers -I/usr/local/opt/openssl/include -I/usr/local/opt/icu4c/include -I/usr/local/opt/curl/include -I/usr/local/opt/gettext/include -I/usr/local/opt/libxml2/include -I/usr/local/opt/readline/include

clang called with: -c -g -O2 conftest.c
superenv added:    -pipe -Os -march=core2 -isystem/usr/local/include -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers -I/usr/local/opt/openssl/include -I/usr/local/opt/icu4c/include -I/usr/local/opt/curl/include -I/usr/local/opt/gettext/include -I/usr/local/opt/libxml2/include -I/usr/local/opt/readline/include
superenv executed: clang -pipe -Os -march=core2 -c -g -O2 conftest.c -isystem/usr/local/include -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers -I/usr/local/opt/openssl/include -I/usr/local/opt/icu4c/include -I/usr/local/opt/curl/include -I/usr/local/opt/gettext/include -I/usr/local/opt/libxml2/include -I/usr/local/opt/readline/include

clang called with: -c -g -O2 conftest.c
superenv added:    -pipe -Os -march=core2 -isystem/usr/local/include -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers -I/usr/local/opt/openssl/include -I/usr/local/opt/icu4c/include -I/usr/local/opt/curl/include -I/usr/local/opt/gettext/include -I/usr/local/opt/libxml2/include -I/usr/local/opt/readline/include
superenv executed: clang -pipe -Os -march=core2 -c -g -O2 conftest.c -isystem/usr/local/include -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers -I/usr/local/opt/openssl/include -I/usr/local/opt/icu4c/include -I/usr/local/opt/curl/include -I/usr/local/opt/gettext/include -I/usr/local/opt/libxml2/include -I/usr/local/opt/readline/include

clang called with: -c -g -O2 conftest.c
superenv added:    -pipe -Os -march=core2 -isystem/usr/local/include -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers -I/usr/local/opt/openssl/include -I/usr/local/opt/icu4c/include -I/usr/local/opt/curl/include -I/usr/local/opt/gettext/include -I/usr/local/opt/libxml2/include -I/usr/local/opt/readline/include
superenv executed: clang -pipe -Os -march=core2 -c -g -O2 conftest.c -isystem/usr/local/include -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers -I/usr/local/opt/openssl/include -I/usr/local/opt/icu4c/include -I/usr/local/opt/curl/include -I/usr/local/opt/gettext/include -I/usr/local/opt/libxml2/include -I/usr/local/opt/readline/include

clang called with: -c -g -O2 conftest.c
superenv added:    -pipe -Os -march=core2 -isystem/usr/local/include -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers -I/usr/local/opt/openssl/include -I/usr/local/opt/icu4c/include -I/usr/local/opt/curl/include -I/usr/local/opt/gettext/include -I/usr/local/opt/libxml2/include -I/usr/local/opt/readline/include
superenv executed: clang -pipe -Os -march=core2 -c -g -O2 conftest.c -isystem/usr/local/include -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers -I/usr/local/opt/openssl/include -I/usr/local/opt/icu4c/include -I/usr/local/opt/curl/include -I/usr/local/opt/gettext/include -I/usr/local/opt/libxml2/include -I/usr/local/opt/readline/include

clang called with: -c -g -O2 conftest.c
superenv added:    -pipe -Os -march=core2 -isystem/usr/local/include -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers -I/usr/local/opt/openssl/include -I/usr/local/opt/icu4c/include -I/usr/local/opt/curl/include -I/usr/local/opt/gettext/include -I/usr/local/opt/libxml2/include -I/usr/local/opt/readline/include
superenv executed: clang -pipe -Os -march=core2 -c -g -O2 conftest.c -isystem/usr/local/include -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers -I/usr/local/opt/openssl/include -I/usr/local/opt/icu4c/include -I/usr/local/opt/curl/include -I/usr/local/opt/gettext/include -I/usr/local/opt/libxml2/include -I/usr/local/opt/readline/include

clang called with: -c -g -O2 conftest.c
superenv added:    -pipe -Os -march=core2 -isystem/usr/local/include -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers -I/usr/local/opt/openssl/include -I/usr/local/opt/icu4c/include -I/usr/local/opt/curl/include -I/usr/local/opt/gettext/include -I/usr/local/opt/libxml2/include -I/usr/local/opt/readline/include
superenv executed: clang -pipe -Os -march=core2 -c -g -O2 conftest.c -isystem/usr/local/include -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers -I/usr/local/opt/openssl/include -I/usr/local/opt/icu4c/include -I/usr/local/opt/curl/include -I/usr/local/opt/gettext/include -I/usr/local/opt/libxml2/include -I/usr/local/opt/readline/include

clang called with: -c -g -O2 conftest.c
superenv added:    -pipe -Os -march=core2 -isystem/usr/local/include -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers -I/usr/local/opt/openssl/include -I/usr/local/opt/icu4c/include -I/usr/local/opt/curl/include -I/usr/local/opt/gettext/include -I/usr/local/opt/libxml2/include -I/usr/local/opt/readline/include
superenv executed: clang -pipe -Os -march=core2 -c -g -O2 conftest.c -isystem/usr/local/include -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers -I/usr/local/opt/openssl/include -I/usr/local/opt/icu4c/include -I/usr/local/opt/curl/include -I/usr/local/opt/gettext/include -I/usr/local/opt/libxml2/include -I/usr/local/opt/readline/include

clang called with: -c -g -O2 conftest.c
superenv added:    -pipe -Os -march=core2 -isystem/usr/local/include -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers -I/usr/local/opt/openssl/include -I/usr/local/opt/icu4c/include -I/usr/local/opt/curl/include -I/usr/local/opt/gettext/include -I/usr/local/opt/libxml2/include -I/usr/local/opt/readline/include
superenv executed: clang -pipe -Os -march=core2 -c -g -O2 conftest.c -isystem/usr/local/include -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers -I/usr/local/opt/openssl/include -I/usr/local/opt/icu4c/include -I/usr/local/opt/curl/include -I/usr/local/opt/gettext/include -I/usr/local/opt/libxml2/include -I/usr/local/opt/readline/include

clang called with: -E conftest.c
superenv added:    -isystem/usr/local/include -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers -I/usr/local/opt/openssl/include -I/usr/local/opt/icu4c/include -I/usr/local/opt/curl/include -I/usr/local/opt/gettext/include -I/usr/local/opt/libxml2/include -I/usr/local/opt/readline/include
superenv executed: clang -E conftest.c -isystem/usr/local/include -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers -I/usr/local/opt/openssl/include -I/usr/local/opt/icu4c/include -I/usr/local/opt/curl/include -I/usr/local/opt/gettext/include -I/usr/local/opt/libxml2/include -I/usr/local/opt/readline/include

clang called with: -c -g -O2 conftest.c
superenv added:    -pipe -Os -march=core2 -isystem/usr/local/include -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers -I/usr/local/opt/openssl/include -I/usr/local/opt/icu4c/include -I/usr/local/opt/curl/include -I/usr/local/opt/gettext/include -I/usr/local/opt/libxml2/include -I/usr/local/opt/readline/include
superenv executed: clang -pipe -Os -march=core2 -c -g -O2 conftest.c -isystem/usr/local/include -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers -I/usr/local/opt/openssl/include -I/usr/local/opt/icu4c/include -I/usr/local/opt/curl/include -I/usr/local/opt/gettext/include -I/usr/local/opt/libxml2/include -I/usr/local/opt/readline/include

clang called with: -o conftest -g -O2 conftest.c -R /usr/lib
superenv added:    -pipe -Os -march=core2 -isystem/usr/local/include -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers -I/usr/local/opt/openssl/include -I/usr/local/opt/icu4c/include -I/usr/local/opt/curl/include -I/usr/local/opt/gettext/include -I/usr/local/opt/libxml2/include -I/usr/local/opt/readline/include -L/usr/local/opt/openssl/lib -L/usr/local/opt/icu4c/lib -L/usr/local/opt/curl/lib -L/usr/local/opt/gettext/lib -L/usr/local/opt/libffi/lib -L/usr/local/opt/libxml2/lib -L/usr/local/opt/readline/lib -L/usr/local/lib -L/System/Library/Frameworks/OpenGL.framework/Versions/Current/Libraries -Wl,-headerpad_max_install_names
superenv executed: clang -pipe -Os -march=core2 -o conftest -g -O2 conftest.c -R /usr/lib -isystem/usr/local/include -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers -I/usr/local/opt/openssl/include -I/usr/local/opt/icu4c/include -I/usr/local/opt/curl/include -I/usr/local/opt/gettext/include -I/usr/local/opt/libxml2/include -I/usr/local/opt/readline/include -L/usr/local/opt/openssl/lib -L/usr/local/opt/icu4c/lib -L/usr/local/opt/curl/lib -L/usr/local/opt/gettext/lib -L/usr/local/opt/libffi/lib -L/usr/local/opt/libxml2/lib -L/usr/local/opt/readline/lib -L/usr/local/lib -L/System/Library/Frameworks/OpenGL.framework/Versions/Current/Libraries -Wl,-headerpad_max_install_names

clang called with: -o conftest -g -O2 conftest.c -Wl,-rpath,/usr/lib
superenv added:    -pipe -Os -march=core2 -isystem/usr/local/include -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers -I/usr/local/opt/openssl/include -I/usr/local/opt/icu4c/include -I/usr/local/opt/curl/include -I/usr/local/opt/gettext/include -I/usr/local/opt/libxml2/include -I/usr/local/opt/readline/include -L/usr/local/opt/openssl/lib -L/usr/local/opt/icu4c/lib -L/usr/local/opt/curl/lib -L/usr/local/opt/gettext/lib -L/usr/local/opt/libffi/lib -L/usr/local/opt/libxml2/lib -L/usr/local/opt/readline/lib -L/usr/local/lib -L/System/Library/Frameworks/OpenGL.framework/Versions/Current/Libraries -Wl,-headerpad_max_install_names
superenv executed: clang -pipe -Os -march=core2 -o conftest -g -O2 conftest.c -Wl,-rpath,/usr/lib -isystem/usr/local/include -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers -I/usr/local/opt/openssl/include -I/usr/local/opt/icu4c/include -I/usr/local/opt/curl/include -I/usr/local/opt/gettext/include -I/usr/local/opt/libxml2/include -I/usr/local/opt/readline/include -L/usr/local/opt/openssl/lib -L/usr/local/opt/icu4c/lib -L/usr/local/opt/curl/lib -L/usr/local/opt/gettext/lib -L/usr/local/opt/libffi/lib -L/usr/local/opt/libxml2/lib -L/usr/local/opt/readline/lib -L/usr/local/lib -L/System/Library/Frameworks/OpenGL.framework/Versions/Current/Libraries -Wl,-headerpad_max_install_names

clang called with: -dumpversion
superenv added:    -pipe -Os -march=core2 -isystem/usr/local/include -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers -I/usr/local/opt/openssl/include -I/usr/local/opt/icu4c/include -I/usr/local/opt/curl/include -I/usr/local/opt/gettext/include -I/usr/local/opt/libxml2/include -I/usr/local/opt/readline/include -L/usr/local/opt/openssl/lib -L/usr/local/opt/icu4c/lib -L/usr/local/opt/curl/lib -L/usr/local/opt/gettext/lib -L/usr/local/opt/libffi/lib -L/usr/local/opt/libxml2/lib -L/usr/local/opt/readline/lib -L/usr/local/lib -L/System/Library/Frameworks/OpenGL.framework/Versions/Current/Libraries -Wl,-headerpad_max_install_names
superenv executed: clang -pipe -Os -march=core2 -dumpversion -isystem/usr/local/include -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers -I/usr/local/opt/openssl/include -I/usr/local/opt/icu4c/include -I/usr/local/opt/curl/include -I/usr/local/opt/gettext/include -I/usr/local/opt/libxml2/include -I/usr/local/opt/readline/include -L/usr/local/opt/openssl/lib -L/usr/local/opt/icu4c/lib -L/usr/local/opt/curl/lib -L/usr/local/opt/gettext/lib -L/usr/local/opt/libffi/lib -L/usr/local/opt/libxml2/lib -L/usr/local/opt/readline/lib -L/usr/local/lib -L/System/Library/Frameworks/OpenGL.framework/Versions/Current/Libraries -Wl,-headerpad_max_install_names

clang called with: -no-cpp-precomp -c conftest.c
superenv added:    -pipe -Os -march=core2 -isystem/usr/local/include -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers -I/usr/local/opt/openssl/include -I/usr/local/opt/icu4c/include -I/usr/local/opt/curl/include -I/usr/local/opt/gettext/include -I/usr/local/opt/libxml2/include -I/usr/local/opt/readline/include
superenv executed: clang -pipe -Os -march=core2 -no-cpp-precomp -c conftest.c -isystem/usr/local/include -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers -I/usr/local/opt/openssl/include -I/usr/local/opt/icu4c/include -I/usr/local/opt/curl/include -I/usr/local/opt/gettext/include -I/usr/local/opt/libxml2/include -I/usr/local/opt/readline/include

clang called with: -o conftest -g -O2 -fvisibility=hidden -no-cpp-precomp conftest.c
superenv added:    -pipe -Os -march=core2 -isystem/usr/local/include -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers -I/usr/local/opt/openssl/include -I/usr/local/opt/icu4c/include -I/usr/local/opt/curl/include -I/usr/local/opt/gettext/include -I/usr/local/opt/libxml2/include -I/usr/local/opt/readline/include -L/usr/local/opt/openssl/lib -L/usr/local/opt/icu4c/lib -L/usr/local/opt/curl/lib -L/usr/local/opt/gettext/lib -L/usr/local/opt/libffi/lib -L/usr/local/opt/libxml2/lib -L/usr/local/opt/readline/lib -L/usr/local/lib -L/System/Library/Frameworks/OpenGL.framework/Versions/Current/Libraries -Wl,-headerpad_max_install_names
superenv executed: clang -pipe -Os -march=core2 -o conftest -g -O2 -fvisibility=hidden -no-cpp-precomp conftest.c -isystem/usr/local/include -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers -I/usr/local/opt/openssl/include -I/usr/local/opt/icu4c/include -I/usr/local/opt/curl/include -I/usr/local/opt/gettext/include -I/usr/local/opt/libxml2/include -I/usr/local/opt/readline/include -L/usr/local/opt/openssl/lib -L/usr/local/opt/icu4c/lib -L/usr/local/opt/curl/lib -L/usr/local/opt/gettext/lib -L/usr/local/opt/libffi/lib -L/usr/local/opt/libxml2/lib -L/usr/local/opt/readline/lib -L/usr/local/lib -L/System/Library/Frameworks/OpenGL.framework/Versions/Current/Libraries -Wl,-headerpad_max_install_names

